### ISSUE TITLE
Refactor remaining logic in aragon-cli/src/lib

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1005]
In the v7 refactor, we extracted logic from commands into aragon-cli/src/lib, and then into the new toolkit package. However, some logic didn't move from the lib folder into the toolkit package because we weren't sure we wanted to expose it in the new package's API.

We should review all logic that remained in aragon-cli, including files in and outside of the lib folder, and tidy it up a bit.

**Comment by 0xGabi** [comment]
Solved with #1214 #1214 #1203 and #1236
