### ISSUE TITLE
Refine API in new toolkit package

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1043]
With the release of SDK v7, the toolkit package now exposes a programmatic interface for the CLI. This API is the result of extracting the logic that previously resided directly in yargs commands within the CLI package. However, the logic was simply extracted without consideration of what the API will look like, or if it's ready for usage in a consistent and polished way.

An interesting way of refining the API is using the examples folder, which is useful to visualize rough edges in the current interface of the toolkit.

**Comment by 0xGabi** [comment]
Part of #1236
