### ISSUE TITLE
Implement analytics

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1049]
TBD

Toolkit or CLI?

**Comment by macor161** [comment]
IMO I would implement it into the CLI. Having analytics in a library is a little bit less common I think. 
Related to #850

**Comment by sohkai** [comment]
Agreed; I think it's only useful at the end user application. Library analytics can be drawn from downloads and documentation views.

Should we close for #850?

**Comment by 0xGabi** [comment]
Make sense, let's keep only #850
