### ISSUE TITLE
Protype power CLI interface

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1055]
Basic spec here: https://docs.google.com/document/d/1k0n-hIlqA7fzDfLORYt6mMYj_wYnuNWYLk9iYqiFFLw/edit?usp=sharing

**Comment by dapplion** [comment]
So far we have used `yargs` which takes care of all the command line parsing/logic for us.

I've spent 30-45 minutes researching javascript CLI projects, frameworks, etc and I haven't found anything that remotely looks like what is being proposed in the document.

- Are you aware of any Javascript project / framework that has implemented CLI navigation / arg detection, and all the features outlined in the document?
- If there is no such framework, should we implement this from scratch? Without having worked on it, it seems really complex and so we should really think if there is a significant ROI on this route. Just having a clear API with good options, remembering parameters, etc would be a great improvement that requires a way lower investment than developing a custom cli-ish UI solution.
