### ISSUE TITLE
IPFS process closed on “aragon ipfs start”

### ISSUE THREAD

**Issue by macor161** [aragon/aragon-cli#1065]
## 🐛 Bug Report

`aragon ipfs start` seems to close the IPFS process as soon as the command finishes. 

## To Reproduce

- Make sure IPFS is not running: `aragon ipfs stop`
- Run `aragon ipfs start`
- IPFS is not running on ports `8080` neither on `5001`

**Comment by 0x6431346e** [comment]
Closed by #1072 
https://github.com/aragon/aragon-cli/pull/1072/files#diff-d93ebc9c2bb4c3eab093acad21f7bae5R139

**Comment by macor161** [comment]
Nice! Thanks a lot @0x6431346e ! I wonder if we should set the `detached` option to `true` by default 🤔

**Comment by macor161** [comment]
Fixed by #1072 🙌

**Comment by 0x6431346e** [comment]
> I wonder if we should set the `detached` option to `true` by default

That makes sense. I initially set it to `true`, but to keep backwards compability I changed it. 

Perhaps we should keep it to `false` one more version to let people get used to this feature. :man_shrugging:
