### ISSUE TITLE
Verify if the update to truffle 5 can break things

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1080]

**Comment by macor161** [comment]
Inconclusive for now due to #1092

**Comment by macor161** [comment]
The CLI doesn't seem backward compatible with projects using truffle 4. E.g. `aragon run` doesn't work on any of the open-enterprise app https://github.com/AutarkLabs/open-enterprise

**Comment by 0xGabi** [comment]
The compatibility issue was solved on #1163
