### ISSUE TITLE
Support apps using truffle 4

### ISSUE THREAD

**Issue by macor161** [aragon/aragon-cli#1104]
`aragon run` currently breaks with apps using `truffle 4`. It should probably support those projects.

**Comment by 0xGabi** [comment]
Can you share which app. I test it on the old boilerplates and it worked for me 🤔

**Comment by macor161** [comment]
Maybe it's only a problem on my laptop. I tested all the open enterprise apps: http://github.com/autarkLabs/open-enterprise
Will try again today on a clean vm.

**Comment by 0xGabi** [comment]
I think it might be the `truffle-config` file each project is using. We might need to check if they have an old truffle configuration and made some transformation
