### ISSUE TITLE
Ipfs propagate hangs forever fetching the gateways

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#1114]
## 🐛 Bug Report

TBD

**Comment by dapplion** [comment]
Are we sure that this technique actually works for propagating content through IPFS? I considered using a similar approach for DAppNode but couldn't prove if requesting content through public gateways actually increases its propagation

**Comment by macor161** [comment]
When I had to propagate content last year for Espresso, it seemed to work but was far from a perfect solution. Did you end up finding a better way?

**Comment by dapplion** [comment]
> @dapplion When I had to propagate content last year for Espresso, it seemed to work but was far from a perfect solution. Did you end up finding a better way?

No, I didn't, we now focus on running a cluster of IPFS nodes and distribute the content ourselves. We should design an experiment to deterministically find out if big public nodes like `ipfs.io` actually cache the content when queried and for how long. Otherwise, we'll be spending network resources without any noticeable gain.

**Comment by 0x6431346e** [comment]
The `propagate` command does not ensure that the content is cached/saved forever on remote nodes, especially public gateways that might have the garbage collector interval `GCPeriod` set to `0`: https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#datastore

People can use the `propagate` command to debug **content discovery** within a network: perhaps querying the DHT is slow and other nodes cannot figure out who has the requested hash, perhaps your node is behind a firewall, or most importantly, perhaps only the root directory was pinned and the links do not resolve. I'm not sure if running a cluster increases content discovery more than running a single node, but it shouldn't hurt :man_shrugging: .

For **content retention** though, an ipfs cluster or a pinning service (filecoin/storj/pinata) sounds like the way to go.
