### ISSUE TITLE
Not able to create a permission using kernel address (using aragonId works fine)

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#1115]
## 🐛 Bug Report

```
npx dao acl create 0x495b44c5baa999a1d91a672764cec5dca  0x282bf7746eA3ce22C7e0E6Aa39aB0808ab0ABb9d MODIFY_ROLE 0xea73bb3445d12fc700c3033b313d2c66ca09db2d 0x3A73fe61a50491EC7AF76c32835f3E9dCB32702B --environment rinkeby --use-frame 
✖ This contract object doesn't have address set yet, please set an address first
```

Using the aragonId of the org works fine.

Estimated time: 2h

**Comment by macor161** [comment]
Hey @0xGabi `0x495b44c5baa999a1d91a672764cec5dca` doesn't seem to be a DAO. Do you have its aragonId?

**Comment by 0xGabi** [comment]
I think this was solved or most likely I point the wrong address as you mentioned cause I tested again and it works fine 🙌

**Comment by macor161** [comment]
Thanks for re-checking this @0xGabi  🙌
