### ISSUE TITLE
Create a contract and pass its address to a DAO template

### ISSUE THREAD

**Issue by vporton** [aragon/aragon-cli#1119]
## 🚀 Feature

I see no way for `npm start` to create a non-Aragon contract and then pass its contract address to a template contract.

This (create a contract and pass its address to a DAO template) feature is needed?

## Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes.

## Motivation

It is necessary for debugging DAO that control non-Aragon contracts.

**Comment by macor161** [comment]
Hi @vporton, you can use `truffle migrate` or a truffle script and then pass the contract address to the `initialize` function of the app with `--app-init-args`. You can find the doc here: https://hack.aragon.org/docs/cli-main-commands#aragon-run
Feel free to ask me more details in the chat 🙂

**Comment by vporton** [comment]
@macor161 But how to determine the contract address created by `truffle migrate` to pass it to `npm start`?

**Comment by vporton** [comment]
@macor161 More importantly, if I run `truffle migrate` before `npm start` is run, i get:

```
Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 7545
    - network_id > *
```

**Comment by ajsantander** [comment]
Agreed that it's not trivial to accomplish this with the current tools. It can be done as @macor161 stated. 

Fortunately, we're working on new tools that will make this, and many other things, much easier. The start command is being deprecated from the CLI and moving to the buidler-aragon plugin, so closing the issue.
