### ISSUE TITLE
`npm install @aragon/cli` hangs

### ISSUE THREAD

**Issue by vporton** [aragon/aragon-cli#1122]
## 🐛 Bug Report

`npm install @aragon/cli` hangs on this stage:
```
$ npm install @aragon/cli 
[            ......] - extract:@aragon/aragen: sill extract @aragon/aragen@6.0.0-beta.1 extracted to /home/porton/Projects/courts/node_modules/.staging/@aragon/aragen-bf20d8d2
```

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes.

#### Environment

- Ubuntu 19.10
- NPM 6.11.3

**Comment by vporton** [comment]
It happenss when run in https://github.com/vporton/courts/tree/533ac6a94fbea98bbbf6a16503c9567ddf056302

**Comment by sembrestels** [comment]
I use to solve it by adding the `--unsafe-perm` flag,  calling: 
```
sudo npm install @aragon/cli --unsafe-perm=true
```

**Comment by 0xGabi** [comment]
Be sure to follow this guidelines as well: https://hack.aragon.org/docs/cli-intro.html#installation-pre-requisites

Will close this issue for now.
