### ISSUE TITLE
'node --no-deprecation’: No such file or directory

### ISSUE THREAD

**Issue by vporton** [aragon/aragon-cli#1123]
## 🐛 Bug Report

```
$ npx aragon --version
/usr/bin/env: ‘node --no-deprecation’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes.

#### Environment

- OS and OS version: Ubuntu 19.10
- `aragon/cli@7.0.2`

**Comment by sembrestels** [comment]
Same for me. I fixed it by editing the `./node_modules/.bin/aragon` file and removing the `--no-deprecation` flag.

**Comment by macor161** [comment]
I can confirm this. The `--no-deprecation` is breaking the CLI on Linux.
