### ISSUE TITLE
"connection not open on send()" error on publish

### ISSUE THREAD

**Issue by macor161** [aragon/aragon-cli#1136]
## 🐛 Bug Report

Several users have reported the following error when running `aragon apm publish`:
```
connection not open on send()
✖ Error inspecting DAO
❯ Error: Provided daoAddress is not a DAO
```
Environment and network info seems to be correct for every user.

#### Mainnet or testnet?

Mainnet and rinkeby

**Comment by nivida** [comment]
This was an issue the WS provider had in web3.js and is fixed since I have refactored all the providers there.
