### ISSUE TITLE
Rename 'apm' alias to 'aragonpm' and update tutorials and documentation

### ISSUE THREAD

**Issue by sethfork** [aragon/aragon-cli#114]
I'd imagine this will be an issue for anyone who uses Atom
```$ npm i -g @aragon/cli```
```
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> scrypt@6.0.3 preinstall /usr/local/lib/node_modules/@aragon/cli/node_modules/scrypt
> node node-scrypt-preinstall.js

/usr/local/bin/aragon -> /usr/local/lib/node_modules/@aragon/cli/dist/cli.js
/usr/local/bin/dao -> /usr/local/lib/node_modules/@aragon/cli/aliases/dao
npm ERR! path /usr/local/bin/apm
npm ERR! code EEXIST
npm ERR! Refusing to delete /usr/local/bin/apm: /Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm symlink target is not controlled by npm /usr/local/bin
npm ERR! File exists: /usr/local/bin/apm
npm ERR! Move it away, and try again.
```

**Comment by sohkai** [comment]
Ouch... did not realize AtomPM was going to be installed as `apm` as well.

@izqui Maybe something we can do is rename the alias to `aragonpm`?

**Comment by izqui** [comment]
As we discussed offline and proposed by @sohkai above, the `apm` alias needs to be renamed to `aragonpm` to avoid clashing with the Atom Package Manager CLI tool.

**Comment by Quazia** [comment]
Would arapm be an option?

**Comment by izqui** [comment]
While I really like `arapm`, we decided on `aragonpm` for consistency with `aragonpm.eth` and aragonpm.com. A closer proposal in terms of support was to simply drop the alias and have it only accessible at `aragon apm` as it currently is.

**Comment by luisivan** [comment]
I think just dropping the alias is a good idea. `dao` is a great alias anyway.
