### ISSUE TITLE
Missing Aragon Fundraising artifacts

### ISSUE THREAD

**Issue by osarrouy** [aragon/aragon-cli#1146]
## 🐛 Bug Report

The latest version of the CLI comes with some pre-published version of the Aragon Fundraising app suites. This is great excepts that IPFS artifacts are missing for `tap`, `bancor-formula` and `batched-bancor-market-maker`. This is tricky because when we try to publish a new local version for tests purposes the 'Fetching latest version from aragonPM...' step takes 10 minutes before it times out and actually enable you to publish the new version …

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes

## Context

This happens on local testnet [the `aragen` one].

#### Organization

None.

#### Environment

- OS and OS version: macOS 10.15

## To Reproduce

Just run `npm run publish` from one of the aforementioned fundraising package.

## Expected behavior

Fetch latest package's artifacts and move ahead to publish.

## Actual Behavior

Block on  'Fetching latest version from aragonPM...' for like 10 minutes [the `ipfsTimeout`].

## Reproducible Demo

Irrelevant

**Comment by macor161** [comment]
Thanks for submitting this @osarrouy, I will have a look at it this week.

**Comment by 0xGabi** [comment]
Fixed on `@aragen@5.4.3` we need to update it on the CLI
