### ISSUE TITLE
Cherry pick legacy hot fixes to develop

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1148]
Do we want any commits form the legacy branch cherry picked into develop or master?

**Comment by 0xGabi** [comment]
TODO:

- [x] https://github.com/aragon/aragon-cli/pull/1208

- [x] https://github.com/aragon/aragon-cli/pull/1105

- [ ] https://github.com/aragon/aragon-cli/pull/863

- [ ] https://github.com/aragon/aragon-cli/pull/845

- [ ] https://github.com/aragon/aragon-cli/pull/842
