### ISSUE TITLE
Fix publish with intent on local development

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1150]
Related to an AragonJS and the following comment: https://github.com/aragon/aragon-cli/blob/develop/packages/cli/src/commands/apm_cmds/publish.js#L559

Estimated time: 8h

**Comment by macor161** [comment]
Is this related to the following command?: https://github.com/aragon/aragon-cli/blob/develop/packages/cli/src/commands/apm_cmds/publish.js#L559

**Comment by 0xGabi** [comment]
Yes, exactly. @macor161 we can jump on a quick call to discuss about it 👍

**Comment by 0xGabi** [comment]
Solved with #1424
