### ISSUE TITLE
Review issue and PR boilerplates

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1157]
Right now, they don't seem to be very helpful, resulting in bloated and uninformative content being entered in the description (PR more than issues).

Also, would like to add a section to PRs about the rationale of the change/fix, so that we don't only see what was done, but what was the idea or strategy behind the change.

**Comment by 0xGabi** [comment]
Done by @macor161 💪

**Comment by macor161** [comment]
I have not modified the new PR and issue templates. Maybe someone else? I will re-open this issue until we figure out if this was really solved.

**Comment by 0xGabi** [comment]
My mistake
