### ISSUE TITLE
IPFS install doesn't work on linux

### ISSUE THREAD

**Issue by sembrestels** [aragon/aragon-cli#1160]
## 🐛 Bug Report

Trying to install IPFS using the aragon-cli throws an error on Ubuntu.

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes

#### Mainnet or testnet?

N/A

#### Organization

N/A

#### Environment

- OS and OS version: Ubuntu 19.04
- Aragon CLI v7.0.2
- IPFS not installed via snap

## To Reproduce

`npx aragon ipfs install`

## Expected behavior

It should install IPFS.

## Actual Behavior

```
sem@tormenta:~/P/committees$ npx aragon ipfs install
ℹ Preparing:
  ✔ Determine platform and architecture
  ✔ Determine golang distribution
  ✔ Determine location
✖ Cannot read property 'replace' of undefined
```

Also when applying the `--local` flag.

## Reproducible Demo

N/A

**Comment by 0xGabi** [comment]
Hey @sembrestels thanks for the feedback this was already fixed. We will be releasing a patch today.
