### ISSUE TITLE
No known way to install several apps in a template

### ISSUE THREAD

**Issue by vporton** [aragon/aragon-cli#1175]
## 🐛 Bug Report

The documentation is unclear on the following issue:

Is it possible to create a package that would use a template to install several apps in separate subdirectories. If possible, how?

I tried to use Lerna, but have this issue:
https://forum.aragon.org/t/how-to-deploy-an-app-in-a-subdirectory/1721

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes

**Comment by 0xGabi** [comment]
This would become a much more straight forward if we decide to include this new feature to the buidler plugin: https://github.com/aragon/buidler-aragon/pull/36
