### ISSUE TITLE
arapp overrides per network

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-cli#119]
At the moment, the `arapp` file is a unique representation of the app state which becomes a problem when someone is publishing an app to many networks. The main two problems are:

- `appId`: Which needs to be in a registry available in the network that the dev has permissions to publish to. It may vary depending on network and may change (going from `open.aragonpm.eth` to the main registry)

- `version`: Which needs to be cohesive with what versions have been previously published, else an 'invalid bump' error can occur. For the `aragon run` command, we currently completely ignore this value and always publish a new major version as a workaround. On this issue, what is the reason to have the version number in package description files such as `package.json` (cc @sohkai @bpierre) besides being able to process them in a server? I'm thinking that we could drop the version value from `arapp.json` altogether, replacing it with an argument to `apm publish` in which you specify the type of bump or version number you want to publish.

My initial idea is that in the truffle configuration file, we could read an `arapp` key per network and then override those values.

**Comment by sohkai** [comment]
> what is the reason to have the version number in package description files such as package.json

AFAIK we include versions in the `package.json` so we can publish them onto npm, in case another package needs the contract interface or etc.

One is for publishing to npm, the `arapp.json` versions are for publishing to whichever APM instance you desire.

----------------

My thinking around this is that we'll need to extend the `arapp.json` format to allow for multiple networks and APM instances. Each network may have multiple APM instances, and each of them should include the last version they were published with (and maybe the HEAD commit hash at that time if it's available?).

**Comment by sohkai** [comment]
> Is there still the apm limitation where you can not release a patch or minor version after releasing a major? Ex. v2.0.5 after v3.0.0.

Yes, we're still working on a new iteration of the package manager which won't have this limitation.

**Comment by perissology** [comment]
> Really like the registries! We could probably move everything (e.g. roles, appName) but the APM version number (and repo address?) out of that scope and onto the top level.

appName probably needs to be on a per registry basis right? Different registries may be a different ens root.

Why is the `version` even necessary in `arapp.json`? `aragon apm publish` already accepts a `bump` param. We could easily determine the correct version to publish for the given registry. 

`arapp.json` could be something like:

```
{
  "roles": [
    {
      "name": "Increment the counter",
      "id": "INCREMENT_ROLE",
      "params": []
    },
    {
      "name": "Decrement the counter",
      "id": "DECREMENT_ROLE",
      "params": []
    }
  ],
  "path": "contracts/CounterApp.sol",
  "networks": {
    "development": {
      "registries": {
        "0x5f6f7e8cc7346a11ca2def8f827b7a0b612c56a1": {
          "appName": "test.aragonpm.eth"
        }
      }
    }
  }
}
```

**Comment by sohkai** [comment]
Good points @perissology, I think that's valid. It think having version numbers does help developer experience, but it's already handled by things like the `package.json`.

**Comment by izqui** [comment]
This looks great @perissology!

Maybe we can introduce the concept of `environment` that would have a registry address (in case it is not the default one for the network), app name and network, that could be referred directly when executing commands like publishing: `aragon apm publish --environment staging`.

```
{
  "roles": [
    {
      "name": "Increment the counter",
      "id": "INCREMENT_ROLE",
      "params": []
    },
    {
      "name": "Decrement the counter",
      "id": "DECREMENT_ROLE",
      "params": []
    }
  ],
  "path": "contracts/CounterApp.sol",
  "environments": {
    "staging": {
      "registry": "0x5f6f7e8cc7346a11ca2def8f827b7a0b612c56a1",
      "appName": "test.aragonpm.eth",
      "network": "development"
    },
    "staging": {
      "registry": "0xfbae32d1cde62858bc45f51efc8cc4fa1415447e",
      "appName": "my-app.open.aragonpm.eth",
      "network": "rinkeby"
    },
    "production": {
      "appName": "my-app.aragonpm.eth",
      "network": "mainnet"
    }
  }
}
```

**Comment by perissology** [comment]
@izqui I like the idea of `environments`.

I assume we would deprecate the `--network` flag in favor of `--environment`.

`aragon run --environment rinkeby-my-apm`

is cleaner then 

`aragon run --network rinkeby --apm.ens-registry 0xXXXXX`

**Comment by izqui** [comment]
I agree. I think once we get this in we can deprecate `--network` but we will need backwards compatibility for some time.
