### ISSUE TITLE
Weird error message in a weird case

### ISSUE THREAD

**Issue by vporton** [aragon/aragon-cli#1190]
## 🐛 Bug Report

```
  ✔ Check port
  ✔ Start IPFS
  ✔ Start IPFS
  ✔ Start a local Ethereum network
  ✔ Setup before publish
  ✔ Prepare for publish
  ✔ Publish app to aragonPM
  ✔ Fetch published repo
  ❯ Deploy Template
    ✔ Compile contracts
    ✖ Deploy 'Template' to network
      → Returned error: execution error: undefined
      Generate deployment artifacts
    Create Organization
    Start Client
✖ Returned error: execution error: undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

So, it produces a meaningless error message and under weird conditions (see below).

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes.

#### Mainnet or testnet?

RPC

#### Environment

- OS and OS version: Ubuntu 19.10

## To Reproduce

1. Download https://github.com/vporton/courts/tree/90698f55eed29c1648a4cbb73fa1ff9902ce4945

1. `npm start` does work.

1. Uncomment two `/* */` comments marked as `// uncomment`

1. Now quite weirdly `npm start` does not work.

## Expected behavior

Uncommenting the comments should have no effect on the behavior of the software.

I thought that the bug is caused by a too deep stack, but my attempt to flatten the calls does not work.

**Comment by macor161** [comment]
Hi @vporton, thanks for submitting this. Can you share a link to the file and line where those comments are?

**Comment by vporton** [comment]
Hi @macor161,
https://github.com/vporton/courts/blob/90698f55eed29c1648a4cbb73fa1ff9902ce4945/contracts/Template.sol

**Comment by macor161** [comment]
Reproducible demo: https://github.com/vporton/courts/tree/weird-bug

**Comment by macor161** [comment]
Hi @vporton, your template bytecode size exceeds the [EIP-170](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-170.md) limit. I will close this but don't hesitate to reach out in the Aragon chat if you need help reducing the size of your template.

**Comment by macor161** [comment]
Here is a good command to know the bytecode size of a specific contract: `cat build/contracts/<YourContractName>.json | jq '.deployedBytecode' | wc -m | xargs -I {} echo "{} / 2 - 1" | bc`
