### ISSUE TITLE
Consider if we should start ipfs on all needed commands

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#1192]
During [v7 refactor](https://github.com/aragon/aragon-cli/pull/951/files#diff-72c73fc10b9d14701bc153f8e841ff0bL191) we remove all the checks that started the IPFS daemon if it was not detected. 

Currently when running commands like `dao install` and there is no IPFS running we output:
```
Get Repo [started]
Get Repo [failed]
→ Cannot find artifacts in aragonPM repo. Please make sure the package is published and IPFS or your HTTP server running.
Fetching katalyst.open.aragonpm.eth@latest [failed]
→ Cannot find artifacts in aragonPM repo. Please make sure the package is published and IPFS or your HTTP server running.
✖ Error: Cannot find artifacts in aragonPM repo. Please make sure the package is published and IPFS or your HTTP server running.
```

We should consider if introduce again something like we add in `aragon run` [here](https://github.com/aragon/aragon-cli/blob/develop/packages/cli/src/commands/run.js#L238).

**Comment by macor161** [comment]
I would be interested to know what was the reasoning behind removing the `start ipfs` task from the commands but I would definitely add them back.

**Comment by 0xGabi** [comment]
@0x6431346e 👆

I think we thought having ipfs daemon always running was going to be the default 🤔
