### ISSUE TITLE
Leverage yarn or fix npm instalation

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#1194]
### @aragon/cli instalation

Using node v12 and npm: `6m 20s`

Using yarn: `2m 7s`

**Note**: Yarn was much more efficient on building the needed packages (srcypt, keccak, secp256k1, web3, etc). Also worth notice that the output displayed during installation is a LOT more friendly.

At the same time it seems to be some kind of dependency issue at the moment of installation using node that always default to installing dev dependencies 🤔

### create-aragon-app

Bootstrapping project and installing dependencies: `11m 33s` 🤕

npm run start:`1m 30s`

The current bootstrapping process is taking forever, we should take a care look what we are actually installing and leverage yarn or figure out why node is always installing dev dependencies.

**Comment by 0xGabi** [comment]
Other advantages of yarn are: 

- [Plug and play](https://next.yarnpkg.com/features/pnp)
- [Yarn lock](https://classic.yarnpkg.com/en/docs/yarn-lock/)

**Comment by 0xGabi** [comment]
We will wait a bit more for this one.

**Comment by sohkai** [comment]
We may still want to use yarn internally for development though :).

Not sure how shrinkwraps and yarn play together, but it may be useful to start using yarn and adding `yarn.lock` to the repo.

**Comment by macor161** [comment]
One thing to keep in mind if we decide to use yarn as well is that it can be error prone to support both a `yarn.lock` and an `npm-shrinkwrap.json` file since we have to make sure that the files stay synchronized. 

Yarn supports importing from `package-lock.json` quite well but I'm not sure about `npm-shrinkwrap.json`.

**Comment by 0xGabi** [comment]
Great, thanks for the feedback. I'll try to move away from shrinkwrap and start using yarn with yarn.lock instead.
