### ISSUE TITLE
Proper generation of app artifacts

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1206]
Right now, the buidler plugin simply copies artifacts generated by the CLI for the Counter app, into the dist folder. The plugin should use the toolkit to generate these artifacts dynamically.

Artifacts are used by the client, and should contain the following:
* env (selected environment object)
* appName (e.g. agent.aragonpm.eth)
* appId
* abi
* deployment (deployment artifacts information)
* functions
* deprecatedFunctions

They are currently generated by the prepareForPublish sub-task of the publish task in the CLI.

**Comment by 0xGabi** [comment]
The logic of the artifact generation was extracted to a pure function on the toolkit on #1222
