### ISSUE TITLE
Fresh clone npm install fails

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1264]
Atm, attempting to install the project after clone fails, because this needs to be linked to @aragon/toolkit in aragon/aragon-cli#develop with the workaround described in this repo's README.

A solution would be to make a release in the toolkit, but similar problems may arise in the future by this repo using bleeding edge features in aragon/aragon-cli#develop. A permanent solution is needed. Something like moving toolkit to its own repo too, and having a github npm dependency for @aragon/toolkit.

**Comment by 0xGabi** [comment]
No longer an issue
