### ISSUE TITLE
apm publish to existing repo

### ISSUE THREAD

**Issue by macor161** [aragon/aragon-cli#1266]
## 🐛 Bug Report

**This is a new bug that was introduced in the `develop` branch. It should be fixed before publishing a new release.**

When running `apm publish major` on an existing repository (repo that has been already published at least once), the command fails with the following message: 

```
Transaction would not succeed ("Returned error: VM Exception while processing transaction: revert REPO_INVALID_VERSION")
```

**Comment by 0xGabi** [comment]
Solved with #1391
