### ISSUE TITLE
Warn user if their mainnet ENS registry configuration points to the old registry

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#1295]
See [ENS migration](https://medium.com/the-ethereum-name-service/ens-registry-migration-bug-fix-new-features-64379193a5a).

Many old Aragon app repos will undoubtedly have the old ENS registry hardcoded in their `arapp.json` configuration.

We should detect this for mainnet configurations and:

1. Switch to the new registry address
2. Warn the user that they should update their configuration to use the new registry address.

**Comment by 0xGabi** [comment]
Solved  with #1390
