### ISSUE TITLE
Migrate ENS contracts and notify dependents

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1296]
See https://medium.com/the-ethereum-name-service/ens-registry-migration-bug-fix-new-features-64379193a5a

* We should upgrade any places where we have the old ENS registry address on mainnet (e.g. arapp.jsons in the boilerplate, etc).
* We may also want to submit PRs to dependents of the CLI on github to correct their ENS registry addresses.
* And a fix for newer versions: https://github.com/aragon/aragon-cli/issues/1295

**Comment by 0xGabi** [comment]
We already open several PRs updating ENS registry address on known projects. Once #1390 is merged we can consider this issue addressed

**Comment by 0xGabi** [comment]
Solved with #1390
