### ISSUE TITLE
Recover the examples folder

### ISSUE THREAD

**Issue by sembrestels** [aragon/aragon-cli#1308]
## 💥 Proposal

In the `development` branch you have renamed the `examples` folder into the new `test-examples`. I think that testing the examples is awesome, but having executable scripts that people can use only changing some parameters can be very useful and educational at the same time.

I did a repo with a pair of examples (atomic payments and atomic SAI-to-DAI swap) that could be included in this repo as well. I would recommend to recover the `examples` folder so it is easier for people to use them.

And because #1288 it is using a weird `node index.js <params> | sh` command, but ideally it should go with the toolkit `exec` function, not with the pipe to `sh` .

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes

**Comment by 0xGabi** [comment]
Closed with #1482
