### ISSUE TITLE
solidity-extractor is only run on the main contract file, not the entire inheritance tree

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#133]
See https://github.com/aragon/aragon.js/issues/118 for an example where this is a problem. Ideally we'd look through the entire inheritance tree for external methods to add to the artifact.json.

**Comment by izqui** [comment]
I was about to start working on an improved extractor and found a PR adding this to truffle, which would make notice strings available in truffle build artifacts https://github.com/trufflesuite/truffle/pull/1221

Still thinking about whether it would make sense to have a standalone extractor that wouldn't depend on truffle, which would just extract all the notice strings from a contract.

**Comment by sohkai** [comment]
> Still thinking about whether it would make sense to have a standalone extractor that wouldn't depend on truffle

I think the most robust way of extracting this info would just be compiling a contract and extracting the natspec from the solc output. However, doing this compilation requires tools like truffle for resolving files, etc.

**Comment by izqui** [comment]
Yep, that's what I meant, having a extractor that would use solc to get the `userdoc`. My question was whether we should build that as a standalone tool or depend on truffle for that.

**Comment by sohkai** [comment]
Given that we currently bundle truffle and use it to compile / test / etc, I think we should initially just use truffle's artifact output and add support for other methods when/if someone needs that functionality.

**Comment by izqui** [comment]
Truffle has already merged it into their `next` branch, so it will be released with version 5

**Comment by Quazia** [comment]
Moving to close assuming changes to truffle resolve this issue.

**Comment by sohkai** [comment]
Looks like this was done with truffle@5, so it would be a good reason to upgrade to it :+1:.

**Comment by 0xGabi** [comment]
Related to #395

**Comment by 0xGabi** [comment]
related to #719

**Comment by 0xGabi** [comment]
Now that we update to truffle 5 I'll close this one

**Comment by sohkai** [comment]
@0xGabi Just wanted to confirm, are we using the AST when the project is using truffle@5 now?
