### ISSUE TITLE
Manually deploy bases in Buidler plugin

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1331]
As a result, we should be able to use the Buidler plugin without having to start aragen.

Functionality should be minimal to be able to create a Repo and use it to install an app in it. It should not support installing core apps in templates. This should be supported once we are able to insert persistent snapshots in the buidlerevm.

### Checklist
- [ ] Apply bases and manage to pass tests without an aragen running.
- [ ] Update .travis.yml to not install and start aragen before starting the test scripts.

**Comment by sohkai** [comment]
> As a result, we should be able to use the Buidler plugin without having to start aragen.

The client still needs to look up the repo using ENS, so at least ENS + a bare aragonPM needs to be deployed.
