### ISSUE TITLE
Avoid aragonOS imports in Buidler projects

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1353]
Atm, projects like aragon-buidler-boilerplate, require an Imports.sol file with all the same imports that the plugin uses to do stuff with aragonOS. Not sure why this is needed... perhaps its a nuance in Buidler that can be avoidad. Discuss with Pato.

**Comment by sohkai** [comment]
> Atm, projects like aragon-buidler-boilerplate, require an Imports.sol file with all the same imports that the plugin uses to do stuff with aragonO

This was primarily an artifact of Truffle; when we requested contract artifacts during contract tests, Truffle wouldn't compile and build contracts that were not explicitly specified in the `contracts/` folder via an import.
