### ISSUE TITLE
Reset devchain after updating the cli

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-cli#137]
Given that updates to the cli can bring new kits or apps, the devchain should be restarted when we detect that the version has changed.

Quick way to do it is to append the cli version to the snapshot directory, which will also allow to go back to a previous snapshot when downgrading.

If we want to do a proper wipe every time, we could save a file in the `~/.aragon` directory (`~/.aragon/version`) where we write the version number every time devchain is started. If when starting the devchain, we detect the version has changed, we should force a `reset`.

**Comment by 0x6431346e** [comment]
Fixes: #214
