### ISSUE TITLE
Restore CI actions that were disabled

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#1381]
Some inconsistencies were causing our CI flow to be erratic and unreliable. This was making us lose a LOT of time trying to figure out why CI builds were failing, and so we decided to disable most of the CI checks and restore them progressively from the ground up, in a way that we can actually continue working.

Inconsistencies:
- Travis builds often needed re-triggering to pass.
- GH actions builds often needed re-triggering to pass.
- GH actions for mac took 40m, while they took 8m for linux.
- Codecov was causing builds to fail because of minute coverage decreases. That's cool, but it's too early for us to worry on those details right now.

So, we disabled:
- codecov.yaml, project and patch statuses where turned off
- deleted .travis.yml in e0c6c1781ce8cd1730aa27ad419bd3b4cb11ae8a
- Removed node 10, 12 and mac builds from .github/workflows/continuous-integration.yml
- Disabled checks from branch protections in aragon-cli

**Comment by sohkai** [comment]
> Removed node 10, 12 and mac builds from .github/workflows/continuous-integration.yml

These sound like something we could run once a night rather than on every PR.
