### ISSUE TITLE
Codeowners configuration not working

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#1418]

**Comment by ajsantander** [comment]
@0xGabi what is the expected behavior? Lets sync on this because both @macor161 and I have been tweaking this.

**Comment by 0xGabi** [comment]
This feature allow to automate how new PRs assign reviewers. So you can specify pieces of the codebase to a particular codeowner.

[Official documentation.](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners)
[Our current configuration file.](https://github.com/aragon/aragon-cli/blob/develop/.github/CODEOWNERS)
