### ISSUE TITLE
Supporting pre-transactions in the CLI

### ISSUE THREAD

**Issue by lkngtn** [aragon/aragon-cli#1423]
## 🐛 Bug Report

I am trying to adjust a parameter that does not have a UI using the CLI's `dao exec` command:

``` 
$ dao exec radspec --env aragon:mainnet --use-frame 0x3a0f6ff356ca08c567052b428195db53eb334d9e changeSpamPenaltyFactor 10000000000000000 --ipfs-gateway https://ipfs.eth.aragon.network/ipfs
  ⠴ Executing changeSpamPenaltyFactor on radspec.aragonid.eth
  ✖ Executing changeSpamPenaltyFactor on radspec.aragonid.eth
    → Returned error: {"id":4,"jsonrpc":"2.0","error":"Frame provider error while getting gas: gas required exceeds allowance (9970051) or always failing transaction"}
✖ Returned error: {"id":4,"jsonrpc":"2.0","error":"Frame provider error while getting gas: gas required exceeds allowance (9970051) or always failing transaction"} 
``` 

I have had success with this before, but this organization is using the dandelion template and is configured such that in order to create a vote the user must lock tokens using the time lock app. In order to lock tokens the user must first sign an approve pre-transaction before signing the forward transaction. This flow works as expected in the Client but it does not appear to work as expected with `dao exec`

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

- [ ] Yes

## To Reproduce

Deploy an dandelion organization at preview.1hive.org, try and use `dao exec` to perform an action that requires going through a vote. 

## Expected behavior

I thought two transactions would be signed and the action would go through just as it does on the Client. 

## Actual Behavior

Got the following error:

``` 
$ dao exec radspec --env aragon:mainnet --use-frame 0x3a0f6ff356ca08c567052b428195db53eb334d9e changeSpamPenaltyFactor 10000000000000000 --ipfs-gateway https://ipfs.eth.aragon.network/ipfs
  ⠴ Executing changeSpamPenaltyFactor on radspec.aragonid.eth
  ✖ Executing changeSpamPenaltyFactor on radspec.aragonid.eth
    → Returned error: {"id":4,"jsonrpc":"2.0","error":"Frame provider error while getting gas: gas required exceeds allowance (9970051) or always failing transaction"}
✖ Returned error: {"id":4,"jsonrpc":"2.0","error":"Frame provider error while getting gas: gas required exceeds allowance (9970051) or always failing transaction"}

```

#### Mainnet or testnet?

Both

#### Organization

mainnet.aragon.org/#/radspec

#### Environment

- OS and OS version: [e.g. Linux Mint 18.0]
- Browser and browser version: [e.g. Firefox 64.0]
- Add any other context about the problem here.

**Comment by sohkai** [comment]
Ohh interesting; we are definitely not supporting pre-transactions in the CLI at the moment (but we should).

In the short term, this is something you may be able to solve with the in-app console.

**Comment by lkngtn** [comment]
This seems to work and is a totally acceptable workaround, I agree the CLI should support pre-transactions but since the console works we don't need to consider this a blocking bug!
