### ISSUE TITLE
Attempt to fetch current version artifact.json instead of generating it when publishing only content

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-cli#143]
Instead of generating the artifact again for upgrades that don't change the smart contract code, the CLI should try to fetch the artifact for the current version instead of generating it and publish it.

The version in the artifact file has to be modified to the actual version being published.

**Comment by sohkai** [comment]
@izqui I believe this is either fixed or unnecessary now?

**Comment by sohkai** [comment]
@0x6431346e @0xGabi Could you double check if this is still an issue?

**Comment by 0xGabi** [comment]
This was tested and fixed with https://github.com/aragon/aragon-cli/pull/426
