### ISSUE TITLE
IPFS logic should not live on the toolkit

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#1435]
Users using toolkit are going to connect to an existent ipfs node or we can assume they will have an ipfs node running locally (e.g. using aragonCLI)

Righ now the IPFS logic on the toolkit is only used by aragonCLI. We should decide where we want to put this logic

**Comment by dapplion** [comment]
Definitely the toolkit should not manage an IPFS node. It should exclusively consume it as a client if applicable.

**Comment by 0xGabi** [comment]
There was consensus on moving the node side of the logic out of the toolkit.
Once we move to a power-user cli it also be irrelevant to offer node logic as user will connect to existing nodes.

We can decide if moving the logic to buidler plugin is the right thing to do or just relay on existing libraries.

**Comment by dapplion** [comment]
The existing logic has reported unsolved bugs associated with it, so I would recommend considering a different approach an implementing from scratch in the builder plugin
