### ISSUE TITLE
Toolkit: Segmented exports

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#1452]
TODO:

- [x] Refactor folder structure #1480 

- [x] Polish utils module #1481 

- [x] Polish helpers

- [x] Polish apm module

- [x] Polish dao module

**Comment by dapplion** [comment]
What would be the benefit for the consumers of this repo? This technique makes sense for libraries such as `lodash` https://www.npmjs.com/package/lodash which has 0 dependencies and 100,000 dependants, most front-end who benefit from importing 30KB instead of 1000KB.

**Comment by sohkai** [comment]
@dapplion This would be nice for using small parts of the toolkits in other places, like a frontend or the buidler plugin.

The dependencies are going to be trickiest to solve, and we should explore how feasible this effort is if we can't isolate dependencies easily.

**Comment by 0xGabi** [comment]
Close with #1488
