### ISSUE TITLE
Illegal char error when using illegal ENS chars in app name during aragon init

### ISSUE THREAD

**Issue by jtremback** [aragon/aragon-cli#147]
Getting this after running `yarn start` in a project bootstrapped with `aragon init`

```
~/work/src/github.com/althea-mesh/try_aragon/my_app_name34
$ yarn start
yarn start v0.24.6
$ aragon run 
 ✔ Start a local Ethereum network
 ✔ Check IPFS
 ❯ Publish app to APM
   ✔ Deploy contract
   ↓ Automatically bump version [skipped]
     → Starting from initial version
   ✔ Determine contract address for version
   ✔ Building frontend
   ✔ Prepare files for publishing
   ✖ Generate application artifact
     → Illegal char _
     Publish my_app_name34.aragonpm.eth
     Fetch published repo
   Create DAO
   Open DAO
 ✖ Illegal char _

```

**Comment by jtremback** [comment]
I'm guessing this is because of the underscore in the app name. Might be good to catch that in `aragon init`. I'm currently trying with `aragon init MyAppName34.aragonpm.eth` to see if that works.

**Comment by Quazia** [comment]
Did you determine whether this was an issue with the underscore or get any more conclusive information on this issue?

**Comment by jtremback** [comment]
Pretty sure it was an underscore thing

**Comment by sohkai** [comment]
cc @0xGabi This is likely still an issue with `create-aragon-app`, and we should check the user input for invalid chars.

**Comment by 0xGabi** [comment]
Yes, I just checked and is still an issue

**Comment by 0x6431346e** [comment]
> cc @0xGabi This is likely still an issue with `create-aragon-app`, and we should check the user input for invalid chars (e.g. see [similar functionality in aragon/aragon](https://github.com/aragon/aragon/pull/473#discussion_r233657706)).

@sohkai 	would it make sense to publish the `web3-utils` file as a package in `aragon.js`, to get the `isValidEnsName` fn from there?

**Comment by sohkai** [comment]
@0x6431346e I'd be inclined against it for now, to avoid too many different repos / packages. That one function in particular is quite easy to move around (and it does not actually support all ENS names, since you have can unicode characters in IRIs).
