### ISSUE TITLE
Caching issues

### ISSUE THREAD

**Issue by jtremback** [aragon/aragon-cli#149]
I initialize an aragon app with

```
$ aragon init baz
$ cd baz
$ aragon run
```
The app opens up correctly. I go into `app/App.js` and change the label on the "Decrement" to "Lower". Refresh the app to see if it has hot reloading or something. Nope, but that's OK. There aren't really any instructions on how to do a partial rebuild of just the frontend, so I shut down and restart `aragon run`. No change on the frontend. Looking at `package.json`, I see that there's a `build` script. I run `yarn run build` and it does some stuff. Then I do `aragon run` again. Still no change.

I start a new aragon project with `aragon init bao`. Instead of doing `aragon run` right away, I make a frontend change first, then do `aragon run`.

This time my change shows up! So parts of the frontend code must be persisting across builds in a bad way. There's a `dist` folder which looks to contain the built frontend in `main.5db0137f.js`.

I make another change to the frontend and restart `aragon run` again. No change to the frontend again. Looking in the `dist` folder, I see a new `main.5405520e.js`. Opening up `index.html`, I see it still references `main.5db0137f.js`. Looks like whatever this cache-busting scheme is isn't working right.

I delete `dist`, and re run `aragon run`. This time the app does not work at all. `index.html` is still trying to load `main.5db0137f.js`, which doesn't exist any more. 

I delete `dist` and `.cache`. This time it works. I think something is wrong with your cache-busting.

**Comment by jtremback** [comment]
Trying to find a workable solution before this issue gets answered, I change the `build` script in `package.json` to `"rm ./.cache/* && npm run compile && npm run sync-assets && npm run build:app && npm run build:script"`. Then, while `aragon run` is still running, I run `yarn run build` in another terminal. Frontend still doesn't change.

Deciding to try the nuclear option, I change the `start` script to `"rm -rf ./.cache/ && rm -rf ./dist/ && aragon run"`. This works, but it takes around a minute from when I make a change to the frontend to see it in my browser (this is on a fast Linux computer as well).

**Comment by jtremback** [comment]
Upgrading parcel to 1.9.3 seems to solve this issue

**Comment by jtremback** [comment]
I'm closing this in favor of https://github.com/aragon/aragon-react-boilerplate/issues/15

**Comment by sohkai** [comment]
@jtremback thanks for looking into this; I haven't had time to update the parcel requirements of all of our repos that rely on it. 1.9.x was a huge improvement in terms of their file watcher and hot reloading strategy.
