### ISSUE TITLE
Verbose mode

### ISSUE THREAD

**Issue by jtremback** [aragon/aragon-cli#152]
Is there a verbose mode? I don't see it documented. It would be really helpful to see the logs of all the things that Aragon calls.

**Comment by izqui** [comment]
I agree this would be nice to have. If you run it in debug mode (`DEBUG=true aragon x`) some extra logging is done already, but we could log more info.

**Comment by PascalPrecht** [comment]
I think that to get verbosity in Aragon specific calls, there's a bit of work to do in preparing the codebase accordingly. However, if this is about getting more output from whatever is happening in the CLI in general, and also getting proper outputs when console logging and similar things, there's a VerboseRenderer that can be used for that: https://github.com/SamVerschueren/listr-verbose-renderer

I pipes everything through that goes to stdout.
