### ISSUE TITLE
Hanging on contract compile

### ISSUE THREAD

**Issue by jtremback** [aragon/aragon-cli#153]
Aragon has started hanging while trying to compile contracts. Oddly, I have not touched the contracts at all yet.

`aragon run` outputs
```
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Start a local Ethereum network
 ✔ Check IPFS
 ❯ Publish app to APM
   ❯ Deploy contract
     ⠏ Compile contracts
       Deploy 'CounterApp' to network
     Automatically bump version
     Determine contract address for version
     Building frontend
     Prepare files for publishing
     Generate application artifact
     Publish bao.aragonpm.eth
     Fetch published repo
   Create DAO
   Open DAO
```
`aragon contract compile` outputs

```
 ℹ Passing the command to Truffle
```

**Comment by jtremback** [comment]
This goes away when init'ing a new folder

**Comment by jtremback** [comment]
Here is the repo that has this issue: https://github.com/althea-mesh/aragon-node-list

**Comment by izqui** [comment]
Does this still hang if you run the command with truffle directly with `npx truffle compile`?

I have gotten some random hangs compiling with truffle in the past in some projects and I was never able to get to the root of the issue, but removing the truffle artifacts directory (`./build`) before compiling makes the issue go away.

**Comment by jtremback** [comment]
Yea, so just some details- the ./build directory had already been removed and it was hanging. Running `npx truffle compile` actually fixed it, so thanks. Not sure if this should be closed or not. Seems like it's still an issue.

**Comment by Quazia** [comment]
Yeah until we know what's causing the issue it's going to be hard to fix. I'll try with that repo and if I can get the behavior to repeat we'll keep the issue open. Otherwise, I think it's going to be too hard to pinpoint what's causing it.

**Comment by jtremback** [comment]
Yea, definitely. I will try to get more logs if it comes up again.
