### ISSUE TITLE
[Feature] Add postCompile hook

### ISSUE THREAD

**Issue by vporton** [aragon/aragon-cli#1556]
## 🚀 Feature

Please add postCompile hook which would be always run after compilation of contracts and other components.

## Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes.

## Motivation

I need it for my project in order to extract API from contract JSON files and store the extracted part of the JSON into `app/public/` directory.

There may be other uses, too.

**Comment by macor161** [comment]
Hi @vporton, thanks for submitting this feature request. You could currently achieve this by creating an npm script that runs `truffle compile` and your post-compilation logic.
E.g. :
```js
   "compile": "truffle compile && ...",
```

**Comment by vporton** [comment]
@macor161 This script is not what I need because it does not run during e.g. `npm start`.

**Comment by 0xGabi** [comment]
We are deprioritizing adding new features to the aragonCLI. This should be already possible using aragon-buidler plugin.
