### ISSUE TITLE
apm publish error on Rinkeby

### ISSUE THREAD

**Issue by macor161** [aragon/aragon-cli#1589]
## 🐛 Bug Report

Using `aragon apm publish major --environment rinkeby` returns the following error:

```
connection not open on send()
  ❯ Publish test123.open.aragonpm.eth
    ✖ Executing newVersion on 0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa
      → Provided daoAddress is not a DAO
✖ Provided daoAddress is not a DAO
```

The error is occurring on `v7.1.2`, `v7.1.1` and `v7.1.0`

`v7.0.4` is ok 

### Question

Why didn't we receive any bug report about this until now?

**Comment by macor161** [comment]
Fixed by #1590

**Comment by sohkai** [comment]
> Why didn't we receive any bug report about this until now?

Most likely because publishing to a real network is not that common, but based on the changes in #1590, I wonder why it was working before, if it did.

**Comment by macor161** [comment]
After discussing with Gabi, the change was introduced in `v7.1.0` to support transaction paths when publishing but it seems that it never worked. We have to check next week if the publish logic of the buidler plugin supports transaction paths or if it has the same problem.

**Comment by 0xGabi** [comment]
Hey this actually worked. I think there is some kind of race condition on aragon.js that makes fetching AragonPM DAO not being detected. 
We also got two different error messages on this same issue:
