### ISSUE TITLE
Improve UX of init command when project folder already exists

### ISSUE THREAD

**Issue by PascalPrecht** [aragon/aragon-cli#163]
When running the `init` command with a project name that happens to be used by another folder in the current working directory, aragon CLI errors out in a user unfriendly fashion:

```
~/projects/machinelabs
❯ aragon init machinelabs.aragonpm.eth
 ✖ Clone template
   → 'git clone' failed with status 128
   Preparing template
   Install package dependencies
 ✖ 'git clone' failed with status 128
```

Since there's already a folder `machinelabs` (which also happens to be a git repo), `init` fails but it's not very obvious at this point, why it fails.

I guess it'd be better if CLI would check whether the project (or a folder with that name) already exists, and if that's the case, either provide a meaningful error message, or let the user decide to wipeout/override the original project folder.

**Comment by PascalPrecht** [comment]
Happy to provide a PR to iterate over if maintainers agree :)

**Comment by luisivan** [comment]
Great catch @PascalPrecht. A PR would be more than welcome :)

**Comment by izqui** [comment]
I think providing a meaningful error message is the way to go, and then let the user decide whether they want to delete the directory on their own or try again with another app name.
