### ISSUE TITLE
`apm versions` shouldn't fail if one of the repo version's contentURI is invalid

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-cli#167]
Currently if one of the published versions in a repo had a badly formatted content URI, doing `aragon apm versions` for the repo results in:

```
✖ Invalid content URI (expected format was "<provider>:<identifier>")
```

The CLI should show the versions that have a correct format as usual, and print a warning sign and the contentURI string for the ones that have an invalid format.

This will require making changes in https://github.com/aragon/apm.js as well, so it doesn't just throw an error when one of the version's content URI is bad.

**Comment by sohkai** [comment]
Directly dependent on https://github.com/aragon/apm.js/issues/20.

**Comment by sohkai** [comment]
<img width="774" alt="screen shot 2018-08-15 at 5 40 01 pm" src="https://user-images.githubusercontent.com/4166642/44157235-46f6c380-a0b2-11e8-8799-e37e0d4c8d4a.png">
