### ISSUE TITLE
Add command to setup dev environment with ENS and APM deployment 

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-cli#17]
Instead of working in a custom deploy flow for our own development environment for Aragon apps, we should generalize this at the `aragon-dev-cli` level to setup a complete environment.

```
$ aragon-dev-cli setup [--registry-name Domain name for registry (default: aragonpm.test)]
```

Steps needed:

- Deploy an ENS instance a create the needed subnodes until `registryName` is owned by the sender.
- Deploy an APM instance with the rootnode for `registryName`. Call `apm.setResolver()`.

This [migration file](https://github.com/aragon/apm-contracts/blob/master/migrations/2_deploy_registry.js) for APM where all this steps are performed can be used for reference.

We need a way to save both the ENS and the registry name so that following `aragon-dev-cli` executions automatically use them (maybe add them to a config file that gets read if no flags are provided?).

**Comment by onbjerg** [comment]
I edited your comment to standardize the flag name (`--registry-name` as oppposed to `--registryName`).

**Comment by izqui** [comment]
New ENS and APM Factories should make this task way easier :) https://github.com/aragon/aragonOS/tree/dev/contracts/factory

**Comment by izqui** [comment]
Irrelevant thanks to https://github.com/aragon/aragen
