### ISSUE TITLE
Document the ~/.aragon directory and how aragon/aragon is installed

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#172]
See https://github.com/aragon/aragon/issues/321; we could document how we use `~/.aragon` and what users should, and should not, do with it.

**Comment by galactusss** [comment]
Is this https://github.com/aragon/specs/tree/master/client a good place to document it?

**Comment by sohkai** [comment]
@galactusss Actually it turns out this has been documented already in https://hack.aragon.org/docs/cli-usage.html#the-aragon-directory :).
