### ISSUE TITLE
Problem linking aragon-cli from source

### ISSUE THREAD

**Issue by ethene** [aragon/aragon-cli#1750]
installed from sources, built

~/aragon-cli$ sudo npm link
npm WARN lifecycle @aragon/cli-monorepo@~prepare: cannot run in wd @aragon/cli-monorepo@ lerna bootstrap (wd=/home/strky/aragon-cli)
audited 839 packages in 10.711s

27 packages are looking for funding
  run `npm fund` for details

found 16 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
/usr/lib/node_modules/@aragon/cli-monorepo -> /home/strky/aragon-cli

~/aragon-cli$ node -v
v10.21.0

**Comment by macor161** [comment]
Hi @ethene, thanks for submitting this. There are indeed a few low security vulnerabilities reported by npm. However they shouldn't pose any major problem to aragonCLI's usage or development until they are fixed.

**Comment by ethene** [comment]
When I am trying to link the 'aragon' is still not available

>sudo npm link --no-audit
npm WARN lifecycle @aragon/cli-monorepo@~prepare: cannot run in wd @aragon/cli-monorepo@ lerna bootstrap (wd=/Users/dmitrystakhin/aragon-cli)
up to date in 2.787s

27 packages are looking for funding
  run `npm fund` for details

>aragon
-bash: /usr/local/bin/aragon: No such file or directory

**Comment by macor161** [comment]
Got it, thanks for the clarification. I'm going to look into this.

**Comment by macor161** [comment]
Ah! After reading your command again, there is a small mistake in it. Since `@aragon/cli ` is a package inside a monorepo, you either have to run the command inside the package directory (`cd packages/cli && npm link`) or run our npm script: `npm run link`.
