### ISSUE TITLE
dao install responds with Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by ethene** [aragon/aragon-cli#1751]
## 🐛 Bug Report

Cannot install token request app according the instruction:
>aragon dao install <dao-address> token-request.aragonpm.eth --app-init-args <vault-address> <token-manager-address>

## To Reproduce

1. Retrieve dao apps command. Looks OK:
 aragon dao apps stablefund.aragonid.eth --environment aragon:mainnet
  ⠹ Inspecting DAO
  ✔ Inspecting DAO
✔ Successfully fetched DAO apps for 0xedce78b7f8945a92974ea1587c5f8856b1b87a41
│ App                  │ Proxy address                              │ Content                                             │
│ kernel               │ 0xedce78b7f8945a92974ea1587c5f8856b1b87a41 │ (No UI available)                                   │
│ acl                  │ 0xe0f35ac8e6c8b8ab88d4798becc0865496d623ba │ (No UI available)                                   │
│ evmreg               │ 0x3b207dab13a033205c5d678fd82f427c8a3d3343 │ (No UI available)                                   │
│ token-manager@v2.1.9 │ 0xc1ee97ce717c1dfed21543ca56f23303c1d5dffc │ ipfs:QmVTZuEn61Txfmjyp8UgKMibGbweJG315A8HBRCzaH2qsL │
│ vault@v3.1.0         │ 0xe8aa182d10252bed21cbe35a1f8cac9b0d9458a7 │ ipfs:QmNhG1DctzrzDWrcAsbhHp184Tt3iCG33LJDfZPbj6WG3k │
│ finance@v2.1.10      │ 0x2be72a3db610bb6d280818503c94e8c9b6db787c │ ipfs:QmWssF9eT1z4gDF9xZkW6BNhEs2ukGsmT6tXZkB8gKryys │
│ voting@v2.1.9        │ 0x241b27133d78177f1fb37ea26645bff0d1e1bbad │ ipfs:QmZurkAwfTPGtiDCQr2mEv3fQ8171Yn4QNcA2FC7JUk22U │
│ address-book@v0.0.5  │ 0x4b6d83235cb0ab1cdce298b6d7b5082f9486c1fe │ ipfs:QmYWjFR3xecabRF92JGPED2UwpeNqT9DDdmG5sUvFPY3E9 │
│ allocations@v1.0.0   │ 0x6f4f713fcf63ec4d16de98e8aa52ab48c1b67545 │ ipfs:QmSfRFFU23NEBnkCCQj523ycQrLtxpCKS328MuMj9UynrJ │
│ dot-voting@v0.0.8    │ 0x5a85207224d849b268bccc94600f7793b157ec3b │ ipfs:QmRDvsbtpchWSmzdff9EsERbYG54F2aCZA1zKbuqjEE8RC │
│ projects@v0.0.10     │ 0x5feeb0f6260eed3d11ac2e35aca5bce4f26047db │ ipfs:QmYUiLYQDZbd5J64weWmPUSVokor3BUw4B7wiSf771CH8o │
│ rewards@v0.0.8       │ 0x5ef9a4ae569307c833f4a164733223e2416f3bdd │ ipfs:QmPFGTLGJSCTz2v1BFdyHWD7Q7mPSv9ABVxSMB5ehptEZm │

2. Trying to run the aragon dao install command ends up with an error as per description:
aragon dao install stablefund.aragonid.eth token-request.aragonpm.eth --app-init-args 0xe8aa182d10252bed21cbe35a1f8cac9b0d9458a7 0xc1ee97ce717c1dfed21543ca56f23303c1d5dffc --environment aragon:mainnet
  ✔ Fetching token-request.aragonpm.eth@latest
  ↓ Checking installed version [skipped]
    → Installing the first instance of token-request.aragonpm.eth in DAO
  ✖ Deploying app instance
    → Cannot read property 'replace' of undefined
    Fetching deployed app
✖ Invalid initialization params for app. Check the arguments passed with the --app-init-args flag
Cannot read property 'replace' of undefined

Same result appears when using another parameter format as per docs for --app-init-args:
aragon dao install stablefund.aragonid.eth token-request.aragonpm.eth --app-init-args ["'0xe8aa182d10252bed21cbe35a1f8cac9b0d9458a7', '0xc1ee97ce717c1dfed21543ca56f23303c1d5dffc'"] --environment aragon:mainnet

## Expected behavior

I expect the aragon-cli to respond with a better explanation of what should happen and if the parameters are correct or not

## Actual Behavior

aragon-cli responds with the same error, not allowing to understand what is wrong with the parameters, aragon-cli or the dao

Cannot read property 'replace' of undefined

Same result appears when using another parameter format as per docs for --app-init-args:
aragon dao install stablefund.aragonid.eth token-request.aragonpm.eth --app-init-args ["'0xe8aa182d10252bed21cbe35a1f8cac9b0d9458a7', '0xc1ee97ce717c1dfed21543ca56f23303c1d5dffc'"] --environment aragon:mainnet

Error handling should be improved, documentation adjusted with proper examples

## Context

Mainnet

(Which network you are using the app with.)

#### Organization

stablefund.aragonid.eth

#### Environment

- OS and OS version: [e.g. Linux Mint 18.0]
MacOS 10.14.6
- Browser and browser version: [e.g. Firefox 64.0]
- Add any other context about the problem here.
Aragon-cli from NPM

**Comment by macor161** [comment]
Hi @ethene, thanks for reporting thing. It seems the instructions for the Token Request app may be outdated a little bit. The initialization takes [3 parameters](https://github.com/1Hive/token-request-app/blob/master/contracts/TokenRequest.sol#L78): `address,address,address[]`. So you probably need to add an empty array as the third parameter: 

```
aragon dao install stablefund.aragonid.eth token-request.aragonpm.eth --app-init-args 0xe8aa182d10252bed21cbe35a1f8cac9b0d9458a7 0xc1ee97ce717c1dfed21543ca56f23303c1d5dffc "[]" --environment aragon:mainnet
```

**Comment by ethene** [comment]
Looks better, but it is still failing later:

aragon dao install stablefund.aragonid.eth token-request.aragonpm.eth --app-init-args 0xe8aa182d10252bed21cbe35a1f8cac9b0d9458a7 0xc1ee97ce717c1dfed21543ca56f23303c1d5dffc "[]" --environment aragon:mainnet
  ✔ Fetching token-request.aragonpm.eth@latest
  ✔ Fetching token-request.aragonpm.eth@latest
  ↓ Checking installed version [skipped]
    → Installing the first instance of token-request.aragonpm.eth in DAO
  ❯ Deploying app instance
    ✖ Executing newAppInstance(bytes32,address,bytes,bool) on 0xedce78b7f8945a92974ea1587c5f8856b1b87a41
      → transaction underpriced
    Fetching deployed app
✖ transaction underpriced

**Comment by macor161** [comment]
Could you try with a higher gas price with the following option?: `--gas-Price`

**Comment by macor161** [comment]
Closing this issue. Let us know if it still doesn't work and we'll reopen it.

**Comment by ethene** [comment]
Looks good now, thanks!

**Comment by ethene** [comment]
Now it went further and executed some transaction but the app is still not deployed after everything. 
Please, suggest if I need to open a new ticket:

aragon dao install stablefund.aragonid.eth token-request.aragonpm.eth --app-init-args 0xe8aa182d10252bed21cbe35a1f8cac9b0d9458a7 0xc1ee97ce717c1dfed21543ca56f23303c1d5dffc "[]" --environment aragon:mainnet --gas-price 37
  ✔ Fetching token-request.aragonpm.eth@latest
  ✔ Fetching token-request.aragonpm.eth@latest
  ↓ Checking installed version [skipped]
    → Installing the first instance of token-request.aragonpm.eth in DAO
  ✔ Deploying app instance
  ↓ Fetching deployed app [skipped]
    → App wasn't deployed in transaction.

ℹ Successfully executed: "Execute desired action as a token holder"

TX: 
https://etherscan.io/tx/0x11911c9abc21ab2f9545088276fcfbca6a237a3328a377e335d3ddc105194092

App is not seen in the configuration, on UI or 'aragon dao apps'
