### ISSUE TITLE
Update react-kit documentation

### ISSUE THREAD

**Issue by galactusss** [aragon/aragon-cli#193]
Reading documentation I notice the react-kit boilerplate is outdated in these webpages: 

[https://hack.aragon.org/docs/cli-usage.html](url)
[https://hack.aragon.org/docs/kits-intro.html](url)

When I try to init an app with `aragon init test react-kit` I get: "No template named react-kit exists"

I believe this is the new react boilerplate: [https://github.com/aragon/aragon-react-kit-boilerplate](url)

**Comment by sohkai** [comment]
@galactusss Did you try this with the latest `@aragon/cli` version (`4.2.1`)? The `react-kit` alias was only added in `4.2.0`.

**Comment by galactusss** [comment]
You are right I had an older version of `@aragon/cli`. I update and works perfect. My bad 😄
