### ISSUE TITLE
feat(apm/version): bump version based on latest published version on chain

### ISSUE THREAD

**Issue by PascalPrecht** [aragon/aragon-cli#196]
Instead of just incrementing the version number stored in an app's manifest (`arapp.json`), `apm version` should reach out to the latest published version on chain, increase from there and sync the value back into the app's manifest.

Most of the reasoning for this change has been discussed in https://github.com/aragon/aragon-cli/issues/195#issuecomment-420203443

**Comment by sohkai** [comment]
#230 has solved this differently.
