### ISSUE TITLE
Introduce option use custom locally installed Aragon client

### ISSUE THREAD

**Issue by PascalPrecht** [aragon/aragon-cli#199]
This came up as I was implementing #198. In order to implement #198, we need to make changes in aragon/aragon's npm scripts as it should look for a newly introduced `ARAGON_CLIENT_PORT` env variable.

While setting custom env variables through the CLI works, there's no easy way to verify whether the installed Aragon client (wrapper) actually consumes that env variable. 

To verify this, we need a way to make CLI use a custom, locally installed version of Aragon client that hasn't been published yet (similar to what we do with npm link). After discussing this with @izqui, we decided to introduce a new option (maybe `---client-path`) that lets users point the CLI to an already locally installed version of the client:

```
$ aragon run --client-path=~/project/some/path --client-port=4000
```

**Comment by PascalPrecht** [comment]
Related: https://github.com/aragon/aragon/pull/352

**Comment by sohkai** [comment]
Really like the `--client-path`!
