### ISSUE TITLE
apm version command should throw if no version bump type is given

### ISSUE THREAD

**Issue by PascalPrecht** [aragon/aragon-cli#202]
Running

```
$ aragon apm version
```

within any aragon app repository results in `New version: 1.0.0`.

It shouldn't be possible to call `$ apm version` without a release type in the first place.

**Comment by Quazia** [comment]
Right now it just logs the current version, it would make sense to change the docs and keep the command as is so it logs `Current version: *current version*"` so there's a way to check current version from the cli.

**Comment by Quazia** [comment]
Ok, so should `aragon apm version` error?

**Comment by izqui** [comment]
The reason it doesn't error is because `aragon apm version` accepts either a bump type (major, minor, patch) or a version number directly, and if nothing is specified then it defaults to `1.0.0`.

Removing the default value and making the argument required would solve the issue.

**Comment by sohkai** [comment]
@0x6431346e @0xGabi I think `aragon apm version` has changed significantly since this issue was created and should error on bad input. Could you double check?

**Comment by 0xGabi** [comment]
`aragon app version` was deprecated and will always error:
1. Cause you have environment configure
2. If you don't have environment will give schemas error.
