### ISSUE TITLE
Improving developer environment setup

### ISSUE THREAD

**Issue by luisivan** [aragon/aragon-cli#203]
With a 30MB/s connection and a i7 laptop, it takes:
- 1 minute to `npm i -g aragon-cli`
- 1 minute and 30 seconds to `aragon init`
- 1 minute to `aragon run` until downloading the client
- 1 minute and 30 seconds to download the client and install its dependencies
- 30 seconds to start the client

Which adds up to **5 minutes and 30 seconds**. Plus whatever it takes to install IPFS.
I'm guessing lots of devs will drop out in the process. This could also be worse in places in the world where they cannot afford fast computers and lots of bandwidth.

Thought of some suggestions on how to improve it.
#### Expected time gain: 1 minute
Devs are installing `aragon-cli`, only to install it again when they `aragon run`. If a dev wants to pin their package to a specific `aragon-cli` version, they could add it manually. But I think as default it creates a lot of overhead and also is inconsistent, since I'd expect to use the same version of the tool if they are asking me to install it globally.
_PRs: https://github.com/aragon/aragon-bare-boilerplate/pull/10 https://github.com/aragon/aragon-react-boilerplate/pull/26 https://github.com/aragon/aragon-react-kit-boilerplate/pull/14_

#### Expected time gain: 30 seconds to 1 minute

Spin off `aragon init` into `create-aragon-app`, so users can just use `npx create-aragon-app <name> <boilerplate>` rather than having to install `@aragon/cli` globally.

#### Expected time gain: 2 minutes
The client has a lot of dependencies, but if you are not using your own one, it doesn't add anything to have to download them all. If you are using the default one, it doesn't even make sense that you have to compile it locally. We could offer the final build of the client, which would remove the need of installing dependencies and compiling the client.

#### Expected time gain: 30 seconds
Installing `go-ipfs` is not very easy because it's not in npm, therefore people need to jump to a website and figure out how to install it. We could use `js-ipfs`, which took a minute to install in my machine.
_Deprecated in favor of pre-bundling `go-ipfs`_

#### Expected time gain: 2 minutes
We could include the binaries in a build, and download them when installing `aragon-cli`. If we detect they are already installed, we could skip this step.
_PR: https://github.com/aragon/aragon-cli/pull/205_

#### Expected time gain: 1 minute
We should pre-package the known roles when building the CLI, so users don't have to install all aragon-apps.
_PR: https://github.com/aragon/aragon-cli/pull/209_

#### Expected time gain: 1 minute
That way, dependencies don't need to be installed each time. We can use https://zeit.co/blog/ncc

**Comment by izqui** [comment]
Another notable improvement for reducing install time for the CLI would be to clean up some of the dependencies it has.

Some low hanging fruit would be removing the dependencies on our apps (`@aragon/apps-*`) which are only used to have the role names that these apps define so they are displayed when doing `dao acl`. These roles can be found in the published app's artifacts, so there is no need to have the dependency. Installing the app's dependencies takes quite a bit of time (specially now that the webapp is installed too), so removing them will be a great improvement.

**Comment by 0xGabi** [comment]
I think we can close this one, what you think @luisivan ?

**Comment by sohkai** [comment]
@0xGabi Yep, let's close it :).

Before you do so though, can you run through a clean environment and replicate the same steps, to see what the current benchmark is? E.g.

1. `create-aragon-app`
2. `npm install`
3. `npm run start`

**Comment by autonome** [comment]
Did a run on a clean machine:

> npx create-aragon-app my-aragon-app

Would be great if the output actually specified the next steps, eg "The
bones of your Aragon app are ready, but you still need to add the muscle
and bring it to life with: `cd my-aragon-app` and run `npm install` and
then `npm start`" or something like that.

> twerkworker-5935:my-aragon-coop dietrich$ npm install

Some warnings and 30 low severity vulns.

> npm start

First time failed at:

> Deploy 'CounterApp' to network
>        → connection not open

But the *second* time... IT WORKED!

**Comment by sohkai** [comment]
> Would be great if the output actually specified the next steps

Great ideas! Put this into its own issue: https://github.com/aragon/aragon-cli/issues/831

> First time failed at:

This must be a timeout issue with the devchain not available yet; @0xGabi we should block until we know the chain has started.

**Comment by 0xGabi** [comment]
## Benchmarks

### `@aragon/cli` instalation

Using node v12 and npm: `6m 20s`

Using yarn: `2m 7s`

**Note**: Yarn was much more efficient on building the needed packages (srcypt, keccak, secp256k1, web3, etc). Also worth notice that the output displayed during installation is a LOT more friendly.

At the same time it seems to be some kind of dependency issue at the moment of installation using node that always default to installing dev dependencies 🤔

### `create-aragon-app`

Bootstrapping project and installing dependencies: `11m 33s` 🤕

npm run start:`1m 30s`

We should look to leverage yarn and try to figure out why node is always installing dev dependencies.
