### ISSUE TITLE
Detect local IPFS version and warn if it's too old

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#213]
Some old IPFS versions have weird behaviours, and if we depend on a particular bug fixes in certain versions, it would be good to warn the user that they can't use a version that's too old.

**Comment by izqui** [comment]
After #207 is released this should no longer be an issue since the IPFS binary is a dependency to the CLI

**Comment by sohkai** [comment]
What if I already have ipfs installed locally though?
