### ISSUE TITLE
Permissions are not setup correctly for the Counter app(?)

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#214]
To reproduce this:
1. `aragon init foo`
2. `aragon run`  (pin `parcel-bundler` to `v1.9.3` if running fails)
3. Press `increment` in the counter app

![image](https://user-images.githubusercontent.com/26041347/46221567-5fffbf00-c356-11e8-8f91-60dec4a78c5f.png)

Browser console logs:
`transaction bag {transaction: undefined, path: Array(0), accept: ƒ, reject: ƒ}`

4. Add a new permission
![image](https://user-images.githubusercontent.com/26041347/46222727-e8339380-c359-11e8-86ec-1a76a5b713f6.png)

What happens next is that the permission is granted and the confirmation(?) fails:
![image](https://user-images.githubusercontent.com/26041347/46222846-43fe1c80-c35a-11e8-8ef0-9cf57a159f04.png)

5. Trying to increment gives the same error

Note: 
- Running `dao acl [dao-address]` throws `Cannot find module '@aragon/apps-token-manager/arapp'`

Environment:
`aragon-cli` version 5.0.0

Any thoughts on how to debug this?

**Comment by izqui** [comment]
Just to confirm, the network and the account are properly set in Metamask right?

**Comment by cjyabraham** [comment]
I got the same issue and yes, I've set the Metamask account correctly I think.

**Comment by 0x6431346e** [comment]
@izqui this was resolved by deleting `.aragon/ganache-db-8545`

Maybe we should consider having a different ganache folder for each aragon os version ? :thinking:

**Comment by luisivan** [comment]
That'd make a lot of sense @0x6431346e

**Comment by sohkai** [comment]
@0x6431346e Should we close this for #137?

**Comment by 0x6431346e** [comment]
Yep
