### ISSUE TITLE
"aragon ipfs" hangs if 8080 port is already used by another service 

### ISSUE THREAD

**Issue by kartojal** [aragon/aragon-cli#219]
Was trying to setup an aragon kit and found that was not capable to do "aragon ipfs" or "aragon run ...", it always hangs forever, with the output at "Starting ipfs at port 5001" at my machine, so investigating a bit more decided to run my own ipfs installed daemon.

Found the IPFS gateway uses the port 8080, so if you have something using that common port, like an nginx service, the aragon cli just hangs forever, without throwing an error.

Will make a pull request,  to throw an error if the ipfs daemon itself throws while starting.

**Comment by luisivan** [comment]
Thanks for reporting! Looking forward to that PR :+1:

**Comment by 0x6431346e** [comment]
This might be fixed by #211

**Comment by perissology** [comment]
looks like this is fixed now. An error is thrown

**Comment by sohkai** [comment]
Should be fixed by #211 and #245.
