### ISSUE TITLE
"aragon run" hangs on "Start IPFS"

### ISSUE THREAD

**Issue by jtremback** [aragon/aragon-cli#224]
There is another issue (https://github.com/aragon/aragon-cli/issues/219) where the poster believes this is due something already using port 8080. I have found that it hangs even if nothing is on 8080. The only thing that fixes it is running "ipfs daemon" separately.

**Comment by sohkai** [comment]
@jtremback Going to close this, since we've improved our handling of IPFS (#211 and #245).
