### ISSUE TITLE
Make it easy to switch between environments

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-cli#23]
We have an issue right now where packages are named e.g. `foo.aragonpm.test`, but this makes it cumbersome to publish the package to the live APM repositories (e.g. `foo.aragonpm.eth`).

We should think about how we want to do this. One idea would be to only have `foo.aragonpm`, as it denotes the package name and the repository, but the TLD would be computed from the chain ID.

For example, for mainnet the computed package name from `foo.aragonpm` would be `foo.aragonpm.eth`. Likewise, for something like `foo.0xpackages` on the mainnet, it would compute to `foo.0xpackages.eth`.

**Comment by onbjerg** [comment]
@izqui I know we talked a bit about this, but do you think this is a viable solution?

**Comment by izqui** [comment]
We definitely need a way to support multiple environments.

I think just changing the TLD isn't enough, and we should allow to publish the same package to different registries even on the same chain.

We could have a json file where we keep track of different registries and networks (similar to a truffle.js config file). We could probably also store the ENS address there, as I discuss in the last paragraph of #17.

**Comment by onbjerg** [comment]
In #22 I will add support for an `rc` (`.aragonrc`) file and also for adding configuration to `package.json`, so we could store it there.

**Comment by izqui** [comment]
Using truffle networks in v4.0.0, making it easy for context switching
