### ISSUE TITLE
Add `Check IPFS` step to `aragon dao new`

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-cli#237]
When `dao new` is used to deploy a DAO using a kit, if IPFS is not running, the artifacts of the kit cannot be fetched and results in the following error:

```
env DEBUG=true dao new --network rpc --kit democracy-kit --fn newDemoInstance --fn-args my-demo-dao
 ❯ ["/usr/local/Cellar/node@8/8.11.2/bin/node","/usr/local/bin/aragon","dao","new","--network","rpc","--kit","democracy-kit","--fn","newDemoInstance","--fn-args","my-demo-dao"]
 ✔ Fetching kit democracy-kit.aragonpm.eth@latest
 ✖ Create new DAO from kit
   → Cannot read property 'apply' of undefined
   Checking DAO
 ✖ Cannot read property 'apply' of undefined
 ❯ TypeError: Cannot read property 'apply' of undefined
    at Task._callee$ (/Users/jorge/provident/aragon-cli/dist/commands/dao_cmds/new.js:119:76)
```

The error can be bypassed by manually starting `aragon ipfs` and then running the command, but it would be nicer to directly start IPFS if needed as part of the command execution (as we do in `aragon apm publish` for example).

**Comment by drexpp** [comment]
Hello Jorge, I was having a look on this issue, I would like to know if the proposed changed is about adding a new task to the TaskList in "src/commands/dao_cmds/new.js" as it is done in the TaskList of the file "src/commands/apm_cmds/publish.js"(lines 282 tp 284), as well as the import required and the yarg message.


Thanks for your time.
