### ISSUE TITLE
publish: Add warning if aragon app solidity code initializes any global variable

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-cli#26]
Because of our use of Proxies, child contracts won't initialize global variables when created. In case an app being published does this, we should at least warn the developer.

```.js
contract MyFancyApp is App {
  uint initialState = 1;
}
```

In the above example, when used behind a proxy, `initialState` will be 0, even though the expectation reading the code is that it will be 1.

We should encourage the developer to make it something like: 

```.js
contract MyFancyApp is App {
  uint initialState;

  function initialize() onlyInit { initialState = 1; }
}
```

Edit: this should apply to logic in constructors too

**Comment by izqui** [comment]
This should also make it in the documentation

**Comment by onbjerg** [comment]
Should be fairly simple to do with solidity-parser. Obviously constants are excluded as they're not written to storage.

For the docs I think an illustration would be helpful. Storage *is* initialized, but just not for the proxy, which is the storage we care about.
