### ISSUE TITLE
Enviroment flags doesn't take effect, defaults to default enviroment

### ISSUE THREAD

**Issue by sebohe** [aragon/aragon-cli#266]
command:
`aragon deploy --enviroment infura`

Error: 
```
✖ Web3 cannot connect using the network provider.

Make sure 'aragon devchain' is running or your provider settings are correct.
```

Now I start `aragon devchain` and then do `aragon deploy --enviroment infura`. This successfully deploys the counter app  to the devchain, but not on rinkeby. I expected it to actually deploy to rinkeby.

Here is my repo: https://github.com/sebohe/someappname

```
$ aragon --version
5.2.0
```

**Comment by sebohe** [comment]
I guess the reason for me to use the --enviroment flag is because i get this error when I use the --network flag:
```
$ aragon deploy --network development
 ℹ Use of `--network` is deprecated and has been replaced with `--environment`. You may need to update your arapp.json
 ✖ Your arapp.json contains an `environments` property. The use of '--network' is deprecated and '--environment' should be used instead.
```

**Comment by Quazia** [comment]
At the very least this is indicative of a documentation issue. I'll look into this more and see what I can find. Do you have any logs or any more information on what happens when you run `aragon deploy --enviroment rinkeby`? How are you checking if the contract was deployed to Rinkeby or not?

**Comment by sebohe** [comment]
@Quazia,

I found the issue. The flag `--environment` has a typo. Missing the letter n. I will never forget how to spell that word ever again. 

Maybe `aragon` should tell you that the flag isn't the right one? A lot of dead ends could have been avoided because I think that the command is correct! but it errors out as if something else is wrong.

Thanks for your help! I will close this issue and maybe open a new one that forces `yargs` to be more strict.

**Comment by sohkai** [comment]
@sebohe Hmm, yes, we should definitely warn about an unknown parameter, and maybe exit printing the help message.
