### ISSUE TITLE
Can't manually publish an aragon app to devchain

### ISSUE THREAD

**Issue by sebohe** [aragon/aragon-cli#267]
Steps:
- 1
`aragon devchain`
- 2
 `ipfs daemon`
- 3
```
$ aragon deploy
 ✔ Compile contracts
 ✔ Deploy 'CounterApp' to network
 ✔ Generate deployment artifacts
 ✔ Successfully deployed CounterApp at: 0x48e9d06106F9B65963472965245F4c676fBD72d6
 ℹ Transaction hash: 0x1255de9bfd5ee8bff8ed6ec26d151f571aaf3844bc5a36a551f22c926a6d04e2
```
- 4
```
$ aragon apm publish 0x48e9d06106F9B65963472965245F4c676fBD72d6
 ✔ Check IPFS
 ✖ Applying version bump (0x48e9d06106F9B65963472965245F4c676fBD72d6)
   → Invalid initial version, it can only be 0.0.1, 0.1.0 or 1.0.0.
   Determine contract address for version
   Building frontend
   Prepare files for publishing
   Generate application artifact
   Publish someappname.aragonpm.eth
   Fetch published repo
```
I would like to run this against a different environment, but because of this https://github.com/aragon/aragon-cli/issues/266 I haven't been able to run `aragon apm publish` on anything besides the devchain
```
$ aragon --version
5.2.0
```

**Comment by Quazia** [comment]
Just add a <bump> tag `1.0.0` or `major` like this... `aragon apm publish major 0x48e9d06106F9B65963472965245F4c676fBD72d6` also you shouldn't have to start IPFS seperately the devchain should do that for you. Let me know if you're still having these issues. Also whatsup @sebohe long time no see!

**Comment by sebohe** [comment]
Well, that worked. I hate when this happens :sweat_smile: 

I didn't expect you around here. thanks for the help!
