### ISSUE TITLE
Spin off `aragon init` as `create-aragon-app`

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#275]
There's been some community support around using one-time commands with `npx` to generate boilerplates.

An ideal flow would be `npx create-aragon-app <name> <boilerplate>` so that users don't have to install a global version of the CLI just to init the project (which often includes its own dependency of `@aragon/cli`).

**Comment by galactusss** [comment]
My plan for solving this issue:
1. I'll change init.js command: `init <name> [template]` for `create-aragon-app <name> <boilerplate>`
2. I'll create an alias for aragon create-aragon-app to make it fully command line
  2.1. Add create-aragon-app on .aliases
  2.2. Update pckage.json: 
```
"bin": {
    "create-aragon-app": "./aliases/create-aragon-app",
    ...
}
```

@0x6431346e, @sohkai What do you think?

**Comment by 0x6431346e** [comment]
The init command needs to be extracted in it's own repo, completely separated from the cli and published as a npm package called `create-aragon-app`.
This package can use yargs just like the cli and export a binary called `create-aragon-app` like you mentioned in 2.2.

Otherwise the user would still need to install the cli globally to use it

**Comment by galactusss** [comment]
Great, I wasn't sure about that. Thank you Daniel

**Comment by galactusss** [comment]
I created a repo on my repositories: https://github.com/galactusss/create-aragon-app
I also published the package on npm: https://www.npmjs.com/package/create-aragon-app

In this case we should create a new repo on aragon @sohkai?

**Comment by galactusss** [comment]
TODO:

- [ ] Remove `aragon init` from cli

- [ ] Update documentation

**Comment by galactusss** [comment]
I'll create a repo under AragonDAC here: https://github.com/AragonDAC/create-aragon-app

**Comment by galactusss** [comment]
Close with #323 and [create-aragon-app](https://github.com/AragonDAC/create-aragon-app) published on npm
