### ISSUE TITLE
Wrong options provided by `--help` for subcommands

### ISSUE THREAD

**Issue by osarrouy** [aragon/aragon-cli#282]
The `aragon devchain --help` command is misleading users by displaying generic options the devchain actually does not take into account: notably `network` and `environment`.

This is due to the fact that these options are defined at the root of the `yargs` entry point and not on a per-command basis:

https://github.com/aragon/aragon-cli/blob/389b08d94b9b0644f7e9a2634180910ee124b8b3/src/cli.js#L85

**Comment by sohkai** [comment]
@0x6431346e @0xGabi This seems like something that could be low hanging and high value. Could you double check the commands to see if their `--help` descriptions aren't correct?

**Comment by 0xGabi** [comment]
Agree 💯, last week I spent some time looking the problem on `dao` command, will try to generalize a solution for the rest of subcommands.

**Comment by 0xGabi** [comment]
We will tackle this one once we refactor to a per package monorepo

**Comment by 0xGabi** [comment]
Solved with #848 😎
