### ISSUE TITLE
Live Reload

### ISSUE THREAD

**Issue by wcisco17** [aragon/aragon-cli#285]
Thank you for your amazing work. I had a question regarding Hot Reload, and how it could be implemented in the kit boilerplate. 

I installed react-hot-loader

and did this 

`import { hot } from 'react-hot-loader'

`const Application = hot(module)(ConnectedApp)

ReactDOM.render(
  <Application />,
  document.getElementById('root')
)
`

I tried Several times to reload the application live and unfortunately had no luck in doing so.
Any work around for this?

**Comment by wcisco17** [comment]
Gotcha, that clears it up. Thanks for you help, I'll do some digging on the vault app.

**Comment by wcisco17** [comment]
Yes, I ran `npm run start:app` first. That command works, I'm just having trouble with running `start:aragon:http`.

**Comment by galactusss** [comment]
@wcisco17 As quick fix you can try using
```
aragon run --http localhost:8001 --http-served-from ./dist
```
Instead of the npm script

**Comment by galactusss** [comment]
Temporary fix
```
aragon init app react-kit
cd app
npm i -D @aragon/cli@5.2.0
npm i -D ganache-core@2.2.1
nom run start:app
npm run start:aragon:http:kit
```

**Comment by galactusss** [comment]
Will be solve when this PR merge aragon/aragon-react-kit-boilerplate#21
