### ISSUE TITLE
Conflicting versions of the CLI

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#291]
Main issue:
- If you follow the tutorial from `hack.aragon.org`, you are advised to install the CLI globally, currently: `5.2.1`
- If you use `aragon init foo` to start a new project you will get a new copy of the `aragon-react-boilerplate` which comes with a `package-lock.json` pinning the CLI to `5.0.0`. (Note: the other boilerplates, `bare` and `react-kit` don't come with a lockfile)

Now, the fun happens, because when you init a project with `5.2.x` you get this `arapp.json`:
```
{
  "roles": [ .. ],
  "path": "contracts/CounterApp.sol",
  "environments": {
    "default": {
      "network": "development",
      "appName": "foo.aragonpm.eth"
    }
  }
}
```
and then when you run `npm run start:aragon:http` you get:
```
> app-name@1.0.0 start:aragon:http
> aragon run --http localhost:8001 --http-served-from ./dist

 ✔ Start a local Ethereum network
 ✔ Check IPFS
 ❯ Publish app to APM
   ✔ Deploy contract
   ↓ Automatically bump version [skipped]
     → Starting from initial version
   ✔ Determine contract address for version
   ✔ Check for --http-served-from argument and copy manifest.json to destination
   ✔ Generate application artifact
   ✖ Publish undefined
     →           - You are deploying a version higher than the one in the chain
     Fetch published repo
   Create DAO
   Open DAO
 ✖ TypeError: Cannot read property 'includes' of undefined
This is usually one of these reasons, maybe:
          - An existing version of this package was already deployed, try running 'aragon version' to bump it
          - You are deploying a version higher than the one in the chain
```
This is because, npm uses the locally installed version of the CLI, `5.0.0`, which expects an `arapp.json` of this kind:
```
{
  "appName": "app.aragonpm.eth",
  "version": "1.0.0",
  "roles": [ .. ],
  "path": "contracts/CounterApp.sol"
}
```

Short-term solution:
- Remove the CLI from the boilerplate's dependency or at least the lockfile
- Advise everyone to *only* use the globally installed CLI

Long-term solution:
- #275 
- Advise people to *only* use the locally installed CLI, otherwise they can run into hard to debug issues, especially when working within a monorepo

Other possible improvements:
- Validate `arapp.json` (in this case `module.appName` was `undefined`), maybe using something like JSON schema which would also integrate nicely with various editors to provide intellisense and auto complete. See https://github.com/aragon/hack/issues/23 https://github.com/aragon/aragon-cli/issues/243
- Whenever you run a CLI command, start/end the log with: `AragonCLI version X` 
- Whenever you run a CLI command (or every x amount of hours), check for newer versions, and warn the users to upgrade. See https://github.com/aragon/aragon-cli/issues/322

**Comment by galactusss** [comment]
Close with [create-aragon-app]( https://github.com/AragonDAC/create-aragon-app). We will create a monorepo with this package and the current cli.

Relevant improvement move to: https://github.com/aragon/aragon-cli/issues/322
