### ISSUE TITLE
Minime Deployment from CLI

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#296]
from @lkngtn:

If you want to deploy a token manager app, it depends on having a Minime token. However, there is no option from the CLI in order to deploy this dependency. For a developer who is familiar with deploying arbitrary code this would be a minor annoyance as it would require them to deploy the Minime token separately–but for a power user who understands Aragon Apps but isn’t an experienced solidity developer this is a blocking issue.

I recommend providing an option for deploying minime token instances using the CLI.

**Comment by Quazia** [comment]
I think this should look something like `aragon dao token <TOKENNAME> <DECIMALUNITS> <SYMBOL> <TRANSFERSENABLED> `. Not sure if it would be worth providing default values for some of these and making them optional.
