### ISSUE TITLE
Permissions cannot be created

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#298]
from @lkngtn:

After installing an app from the CLI the permissions must be initialized using `dao acl create [dao] [app] [role] [entity] [manager]` however this command fails when trying to set the `[entity]` and `[manager]` to the the account which the `CREATE_PERMISSIONS_ROLE` with the error `Cannot find transaction path for executing action`.

**Comment by lkngtn** [comment]
I believe this may be related to #297 and probably resolved by those same fixes. I think with 297 those permissions are being initialized to 0xFFF.., and because of that it is impossible to create the permissions. Once that issue is fixed I believe this will also go away. 👍

**Comment by 0x6431346e** [comment]
> I believe this may be related to #297 and probably resolved by those same fixes. I think with 297 those permissions are being initialized to 0xFFF.., and because of that it is impossible to create the permissions. Once that issue is fixed I believe this will also go away.

You're right, it should be fixed now.
