### ISSUE TITLE
Cannot read property 'map' of undefined - how to run the app without redeploying?

### ISSUE THREAD

**Issue by stefek99** [aragon/aragon-cli#307]
https://hack.aragon.org/docs/cli-usage.html

Everytime I run `npm run start` it is deploying everything. That is correct, that is what the documentation says:

> aragon run by default will replicate Aragon's production environment and publish your app using IPFS. However, when developing the webapp part of your Aragon app, using IPFS would require you to repeat the entire publishing process every time you make a change and want to try it out.
> Using the HTTP mode for running your app requires starting an HTTP server to serve your app files before executing aragon run or aragon apm publish

That is why I run `aragon run --http localhost:8001 --http-served-from ./dist`

That is getting me some error: 

```
aragon run --http localhost:8001 --http-served-from ./dist
 ↓ Start a local Ethereum network [skipped]
   → Connected to the provided Ethereum network
 ✔ Check IPFS
 ✔ Publish app to APM
 ✖ Create DAO
   → Cannot read property 'map' of undefined
   Open DAO
 ✖ Cannot read property 'map' of undefined
```

Can you please advise how to fix it? 

The reason why I do not want redeployment is that I've already added permission to counter, already incremented it, don't want set it each time .

**Comment by stefek99** [comment]
Cool, thanks, it kind of works...

See the video: https://youtu.be/67FPgCCTiPc

It is redeploying the contracts, the DAO address is new between restarts, maybe it is by design, thanks anyway.

**Comment by galactusss** [comment]
@stefek99 I close this issue cause this error is fixed. 

About your question there are several things:
1. When you execute `aragon run` you delpoy your dao to a local devchain, except you use the option --reset this information are store.
2. If you only want to make changes on your app you should run `npm run start:app` and this will hot reload your changes on http://localhost:8001
3. If you want to use the dao you already deployed, you can run `npm run start:aragon:ipfs:kit` and then select the addres of your dao: http://localhost:3000/#/DAO_ADDRESS

Anyway `aragon run` should not deploy new dao instance everytime. I'll open a new issue related to that problem.
