### ISSUE TITLE
aragon run add error messaging if you try to use a network other than local rpc

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#308]
```
aragon run --debug --environment staging                                                  
Start a local Ethereum network [started]
Start a local Ethereum network [failed]
→ Cannot read property '_url' of undefined
```

**Comment by sohkai** [comment]
I think `aragon run` was definitely designed to only be run on a local network, due to how many transactions it might make and how long it would take to mine them. Maybe we can add some error messaging if you try to use a different network?

**Comment by dapplion** [comment]
@0xGabi Do you believe the best place to check this is the environment middleware? After reviewing similar issues I'm unsure if it's best to parse the `argv._` array and check on the middleware, or do the check directly on that specific command module file, before running the tasks.

**Comment by 0xGabi** [comment]
>Do you believe the environment middleware is the best place to check this?

Actually I think this should be better as a check on the specific command cause we are not doing a global config as we have with [`configureNetwork`](https://github.com/aragon/aragon-cli/blob/master/packages/aragon-cli/src/middleware/environment.js#L24)

Would like to know others opinions either way, @macor161 @ajsantander

**Comment by dapplion** [comment]
> I suggest that we wait after the refactoring to fix this issue.

Sounds good. I'll close the PR for now

**Comment by 0xGabi** [comment]
@dapplion @ajsantander is this one still relevant with the buidler plugin?

**Comment by dapplion** [comment]
Probably not. The simplification of the options may not allow it to even happen, but it's not fully defined yet.
