### ISSUE TITLE
Problems trying to run aragon app (npm run start:local)

### ISSUE THREAD

**Issue by PJColombo** [aragon/aragon-cli#317]
I created an aragon app following the tutorial. When I try to run it  using 

`aragon run`

I get this (I try to delete the ~/.aragon directory but I'm still getting the error): 

` Opening http://localhost:3000/#/0xF5752896F514DaA719deB22657e593565F586BBe to view your DAO
(node:13072) UnhandledPromiseRejectionWarning: Error: Error: Command failed: npm run start:local
"scripts" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aragon@0.6.0 start:local: `scripts/launch-local.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aragon@0.6.0 start:local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USUARIO\AppData\Roaming\npm-cache\_logs\2019-01-03T02_22_20_254Z-debug.log

> aragon@0.6.0 start:local C:\Users\USUARIO\.aragon\wrapper-2d79d2b9373d8b89bb28a7ecd613fb6373ac2d43
> scripts/launch-local.sh

    at C:\Users\USUARIO\Documents\GitHub\aragon\testing\node_modules\@aragon\cli\dist\commands\run.js:412:29
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:13072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:13072) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by PJColombo** [comment]
Same problem @galactusss 

`
C:\Users\USUARIO\Documents\GitHub\aragon>npx create-aragon-app testing.aragonpm.eth react
npx: installed 1 in 4.125s
Path must be a string. Received undefined
npx: installed 124 in 27.791s
C:\Users\USUARIO\AppData\Roaming\npm-cache\_npx\3732\node_modules\create-aragon-app\dist\cli.js
 √ Preparing initialization
 √ Cloning app template
 √ Preparing template
 √ Installing package dependencies
 √ Created new application testing.aragonpm.eth in testing

C:\Users\USUARIO\Documents\GitHub\aragon>cd testing

C:\Users\USUARIO\Documents\GitHub\aragon\testing>npx aragon run
npx: installed 1 in 9.137s
Path must be a string. Received undefined
C:\Users\USUARIO\Documents\GitHub\aragon\testing\node_modules\@aragon\cli\dist\cli.js
 √ Start a local Ethereum network
 √ Check IPFS
 √ Publish app to APM
 √ Create DAO
 √ Open DAO
 i You are now ready to open your app in Aragon.
 i Here are some Ethereum accounts you can use.
  The first one will be used for all the actions the CLI performs.
  You can use your favorite Ethereum provider or wallet to import their private keys.

Address #1:  0xb4124cEB3451635DAcedd11767f004d8a28c6eE7 (this account is used to deploy DAOs, it has more permissions)
Private key: a8a54b2d8197bc0b19bb8a084031be71835580a01e70a45a13babd16c9bc1563
Address #2:  0x8401Eb5ff34cc943f096A32EF3d5113FEbE8D4Eb
Private key: ce8e3bda3b44269c147747a373646393b1504bfcbb73fc9564f5d753d8116608
 i The accounts were generated from the following mnemonic phrase:
explain tackle mirror kit van hammer degree position ginger unfair soup bonus


 i This is the configuration for your development deployment:
    Ethereum Node: ws://localhost:8545
    ENS registry: 0x5f6f7e8cc7346a11ca2def8f827b7a0b612c56a1
    APM registry: aragonpm.eth
    DAO address: 0x5b6a3301a67A4bfda9D3a528CaD34cac6e7F8070

    Opening http://localhost:3000/#/0x5b6a3301a67A4bfda9D3a528CaD34cac6e7F8070 to view your DAO
(node:11244) UnhandledPromiseRejectionWarning: Error: Error: Command failed: npm run start:local
"scripts" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aragon@0.6.0 start:local: `scripts/launch-local.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aragon@0.6.0 start:local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USUARIO\AppData\Roaming\npm-cache\_logs\2019-01-04T22_05_51_672Z-debug.log


> aragon@0.6.0 start:local C:\Users\USUARIO\.aragon\wrapper-2d79d2b9373d8b89bb28a7ecd613fb6373ac2d43
> scripts/launch-local.sh


    at C:\Users\USUARIO\Documents\GitHub\aragon\testing\node_modules\@aragon\cli\dist\commands\run.js:412:29
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:11244) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:11244) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by galactusss** [comment]
Oh @PJColombo I just notice that you are running on a Windows PC. Unfortunately unless you want to refactor the shell script to [be in node](https://github.com/aragon/aragon/blob/master/scripts/launch-local.sh) is not supported.

If you have the chance to run a virtual matching with linux I recommend that insteed.

I close this cause is not an issue.

**Comment by PJColombo** [comment]
@galactusss 

I don't get it, I recall creating an aragon app following the tutorial  step by step with no problem months ago

**Comment by galactusss** [comment]
We use a shell script to launch the local Aragon client but this should be changed to be a node script. Something like [this](https://github.com/joejordan/aragon/commit/4557f3f58be7df362489febe61b07867903647e7)

**Comment by PJColombo** [comment]
I'll use a virtual machine then 

Thanks for your help tho 👍
