### ISSUE TITLE
Cannot create dao with ganache-core@2.3

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#321]
Doing `aragon dao new` on `master` gets stuck after sending the transaction:
```
 ✔ Fetching kit bare-kit.aragonpm.eth@latest
 ⠇ Create new DAO from kit
   Checking DAO
```
This works fine with `v5.2.2`.
Looking at the [diff](https://github.com/aragon/aragon-cli/compare/v5.2.2...master) I suspect is because of #302 . Maybe aragen needs to be rebuilt?

**Comment by galactusss** [comment]
In case aragen is rebuild would be great opportunity to include the changes needed to solve: https://github.com/aragon/aragon-cli/pull/246

**Comment by sohkai** [comment]
@0x6431346e could you double check by pinning ganache-core to the old version and seeing if it still works?

We should bump the version of ganache in aragen and release it with https://github.com/aragon/aragen/pull/24.

**Comment by 0x6431346e** [comment]
@sohkai It works with pinning the old version.

**Comment by galactusss** [comment]
@sohkai , @0x6431346e I bump the version of ganache on aragon/aragen#24 then I tested aragonCLI locally doing `npm link` to the updated aragen branch...but I'm still getting this bug. Not sure if there are other changes I need to do to replicate the new aragen release

**Comment by sohkai** [comment]
@galactusss You'd have to copy the snapshot that gets generated by aragen into the appropriate ~/.aragon folder.

This definitely seems like a really good reason to bump aragen now :+1:.

**Comment by sohkai** [comment]
I've renamed this issue so we can keep this open as we try to upgrade aragen to ganache-core@2.3 to see if this is still an issue.

**Comment by sohkai** [comment]
@0xGabi Wondering if we can close this now that I think we've bumped the version used by aragen? Or if we haven't, should we try to update its `ganache-core` now?

**Comment by 0xGabi** [comment]
@sohkai this is still an issue on `ganache-core@v2.5.5`. 

```
/Users/gabrielgarcia/Code/Aragon/aragen/node_modules/ganache-core/lib/utils/gasEstimation.js:88
      rootBegin: steps.systemOps[begin][0],
                                       ^
TypeError: Cannot read property '0' of undefined
    at findRootScope (/Users/gabrielgarcia/Code/Aragon/aragen/node_modules/ganache-core/lib/utils/gasEstimation.js:88:40)
```

Note: We bump the version with green-keeper but we will need to pin it back. The new aragonCLI release still on `ganache-corev2.2.1`

**Comment by 0xGabi** [comment]
I check with `ganache-corev@v5.3.0` and seems to be working.

**Comment by sohkai** [comment]
It might be worth creating an issue over at `ganache-core` with some of the debug trace on `v2.5.5` to help them.

**Comment by 0x6431346e** [comment]
I need to update dependencies in `aragen` as well.
(@sohkai would you mind enabling `greenkeeper` to that repo as well?)

After that we can test the new `ganache-core` and `web3` versions, because now they're being deduped:
```
daniel@zen5-ub:~/r/aragon/aragon-cli$ npm ls -g ganache-core
/home/daniel/.npm-global/lib
└─┬ @aragon/cli@5.8.0
  ├─┬ @aragon/aragen@4.1.0
  │ └── ganache-core@2.2.1  deduped
  └── ganache-core@2.2.1 

daniel@zen5-ub:~/r/aragon/aragon-cli$ npm ls -g web3
/home/daniel/.npm-global/lib
└─┬ @aragon/cli@5.8.0
  ├─┬ @aragon/aragen@4.1.0
  │ └── web3@1.0.0-beta.34  deduped
  ├─┬ @aragon/os@4.2.0
  │ └─┬ truffle-hdwallet-provider@0.0.3
  │   ├── web3@0.18.4 
  │   └─┬ web3-provider-engine@8.6.1
  │     └── web3@0.16.0 
  ├─┬ @aragon/wrapper@5.0.0-rc.7
  │ ├─┬ ethereum-ens@0.7.4
  │ │ └── web3@0.19.1 
  │ └── web3@1.0.0-beta.33 
  ├─┬ ganache-core@2.2.1
  │ └── web3@1.0.0-beta.34 
  ├─┬ truffle-hdwallet-provider@1.0.9
  │ └── web3@1.0.0-beta.37 
  ├─┬ truffle-hdwallet-provider-privkey@0.3.0
  │ └── web3@0.20.7 
  └── web3@1.0.0-beta.34 
```

**Comment by sohkai** [comment]
@0x6431346e Greenkeeper is now enabled on `aragen` as well.

**Comment by 0xGabi** [comment]
This is fixed with https://github.com/aragon/aragen/pull/41
