### ISSUE TITLE
Problem installing dependencies @aragon/cli (node-gyp rebuild)

### ISSUE THREAD

**Issue by PJColombo** [aragon/aragon-cli#328]
I'm using debian 9.6.0 on a virtual machine when I run `npm install -g @aragon/cli` I get this (there's some problem when executing node-gyp rebuild): 

`> keccak@1.4.0 rebuild /home/paulo/.nvm/versions/node/v11.6.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/keccak
> node-gyp rebuild

make: Entering directory '/home/paulo/.nvm/versions/node/v11.6.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/keccak/build'
  CXX(target) Release/obj.target/keccak/src/addon.o
make: g++: Command not found
keccak.target.mk:119: recipe for target 'Release/obj.target/keccak/src/addon.o' failed
make: *** [Release/obj.target/keccak/src/addon.o] Error 127
make: Leaving directory '/home/paulo/.nvm/versions/node/v11.6.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/keccak/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/paulo/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/home/paulo/.nvm/versions/node/v11.6.0/bin/node" "/home/paulo/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/paulo/.nvm/versions/node/v11.6.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/keccak
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paulo/.npm/_logs/2019-01-06T01_49_03_631Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.

> scrypt@6.0.3 install /home/paulo/.nvm/versions/node/v11.6.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/scrypt
> node-gyp rebuild

make: Entering directory '/home/paulo/.nvm/versions/node/v11.6.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/scrypt/build'
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
make: g++: Command not found
copied_files.target.mk:22: recipe for target 'Release/obj.target/copied_files.node' failed
make: *** [Release/obj.target/copied_files.node] Error 127
make: Leaving directory '/home/paulo/.nvm/versions/node/v11.6.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/paulo/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/home/paulo/.nvm/versions/node/v11.6.0/bin/node" "/home/paulo/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/paulo/.nvm/versions/node/v11.6.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/scrypt
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paulo/.npm/_logs/2019-01-06T01_49_09_670Z-debug.log`

**Comment by galactusss** [comment]
Hi @PJColombo If I remember correctly [this solution](https://github.com/nodejs/node-gyp/wiki/Updating-npm%27s-bundled-node-gyp) might help you

**Comment by sohkai** [comment]
I've been seeing this issue as well recently, but I've only seen it on macOS machines without xcode installed and running `npm@5`.

It seems you should be on `npm@6` (unless you manually installed `npm@5`), so it's likely related to something else. Looking at the error log, it looks like you probably need to install some compilers:

```
make: g++: Command not found
```

**Comment by galactusss** [comment]
I close this issue. Isn't a problem with `aragonCLI`. More related to how setup `node-gyp`
