### ISSUE TITLE
Don't use already open port

### ISSUE THREAD

**Issue by autonome** [aragon/aragon-cli#333]
Aragon ran on port 3000 even though I already had something running on that port.

It should check to see if there's anything on the port first, before picking which to use.

**Comment by dapplion** [comment]
What command were you using when the port collision happen? @0xGabi the CLI should already check if the port is taken with https://github.com/aragon/aragon-cli/blob/e4ccf6c543100ac25f75efb5d5c424e22f017061/packages/aragon-cli/src/util.js#L41, is this util used in all instances that a port is required?

**Comment by sohkai** [comment]
We may be able to close this; it may have been fixed later but we forgot to close this issue.

**Comment by dapplion** [comment]
Please @0xGabi, close when possible
