### ISSUE TITLE
Able to install non-app with `dao acl create`

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#344]
**Describe the bug**
App install went wrong: 
```
Uncaught Error: No method named getCode on 0x8c06aebf29f20a2e09b32f5d44cea49db3ec2ee0
    at e.call (index.js:47)
    at Promise.all.t.call.catch (index.js:314)
```
Now it's stuck at _Loading apps..._
**Mainnet or testnet?**
Rinkeby

**Organization**
https://rinkeby.aragon.org/#/showcase.aragonid.eth/

**To Reproduce**
Can't really tell, but there is a stack trace in the console.

**Expected behavior**
Load the apps even if one of them is faulty.

**Additional context**
```
 % dao apps showcase --all --environment aragon:rinkeby
 ⠸ Inspecting DAO
   → Fetching apps for showcase.aragonid.eth...
   Fetching permissionless apps
/home/daniel/repos/aragon/aragon-cli/node_modules/rxjs/util/subscribeToResult.js:43
            root_1.root.setTimeout(function () { throw err; });
                                                 ^

Error: No method named getCode on 0x8c06aebf29f20a2e09b32f5d44cea49db3ec2ee0
    at Proxy.call (/home/daniel/repos/aragon/aragon-cli/node_modules/@aragon/wrapper/dist/core/proxy/index.js:2:501)
    at Promise.all.appProxy.call.catch (/home/daniel/repos/aragon/aragon-cli/node_modules/@aragon/wrapper/dist/index.js:119:2)
```

**Comment by 0x6431346e** [comment]
More details here: https://github.com/aragon/aragon/issues/577

**Comment by sohkai** [comment]
The immediate error is actually an issue with aragon.js: https://github.com/aragon/aragon.js/pull/236.

However, I'm not sure what we should do in this case, outside of https://github.com/aragon/aragon/issues/577's suggestion to add more validation to the CLI:

> If possible CLI should validate that the entity is valid (has role, has getcode function), or if not possible provide an option to forcible remove invalid permissions after they have been added without needing to call getcode.

Will discuss in https://github.com/aragon/aragon/issues/577.

**Comment by sohkai** [comment]
@0x6431346e @0xGabi Should we keep this issue open to track the CLI doing validation for non-apps?
