### ISSUE TITLE
dao new fails due to gasLimit on mainnet and rinkeby

### ISSUE THREAD

**Issue by lkngtn** [aragon/aragon-cli#346]
``` 
$ dao --use-frame --environment aragon:mainnet new
 ✔ Fetching kit bare-kit.aragonpm.eth@latest
 ✖ Create new DAO from kit
   → Returned error: {"id":5,"jsonrpc":"2.0","error":"exceeds block gas limit"}
   Checking DAO
 ✖ Returned error: {"id":5,"jsonrpc":"2.0","error":"exceeds block gas limit"} 

```

It should be possible to deploy a bare organization within the gas limit.

**Comment by 0x6431346e** [comment]
I can confirm, I tried the following change, but now is stuck on "Creating DAO from kit"
```diff
+        const gas = await newInstanceTx.estimateGas({ from: ctx.accounts[0] })

          const { events } = await newInstanceTx.send({
            from: ctx.accounts[0],
-           gas: 15e6,
+           gas,
          })
```

Possible useful information, gas is estimated at:
- rinkeby: 1737713
- devchain: 1786988

I also tried with 2737713 on rinkeby, no luck.

**Comment by lkngtn** [comment]
Mainnet appeared to work with 7e6, and while not consistent, @bingen was able to deploy to rinkeby with `dao new` using 6e6: https://aragon.chat/channel/dev-help?msg=Rx8fAqexcdD4nqMuQ

**Comment by lkngtn** [comment]
I tried changing  to 5e6, it still hangs on `dao new` but if you wait a bit, then cancel the transaction, you can see that the transaction goes through successfully and you can examine it to find the dao address. 

I'm not sure what the gas should be set, or why the CLI hangs and doesnt detect it as a success though.

**Comment by stellarmagnet** [comment]
@lkngtn can you explain what file we need to dig into to change the gas limit?

**Comment by lkngtn** [comment]
https://github.com/aragon/aragon-cli/blob/dfd6caaebf63b0a8523ec93b8260b79147cd39e5/src/commands/dao_cmds/new.js#L105

**Comment by stellarmagnet** [comment]
where is that file located on my machine? I only see it inside application
folders, and i dont have the token manager app locally. i didnt think i
needed to?
ᐧ

**Comment by lkngtn** [comment]
you'll need to clone the repo:

`git clone https://github.com/aragon/aragon-cli.git`

then you can find the file in the repo and make the change. 

then compile and link by running these commands from the repo directory:

`npm install`
`npm link`

disclaimer: I don't know npm that well so their may be a better way to do that, but was able to get it working that way. 

Also even with that fix it the CLI will probably still hang on `dao new` so you'll need to go on etherscan and look for the transaction and find the dao address. 

eg: 
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/4986634/51556631-b71b2980-1e48-11e9-9048-f541b902794f.png">

The first address in "to:" should be the dao's address.

**Comment by chrishobcroft** [comment]
I just ran `dao new --environment aragon:rinkeby` and it worked without issue for me.

```
chrishobcroft@thinkpad:~$ dao new --environment aragon:rinkeby
 ✔ Fetching template bare-kit.aragonpm.eth@latest
 ✔ Create new DAO from template
 ✔ Checking DAO
 ✔ Created DAO: 0xF89cdxxxB5796xxxBa24xxxB82xxx228fxxx7B14
chrishobcroft@thinkpad:~$ aragon -version
5.7.1
```
