### ISSUE TITLE
Claiming an aragonid

### ISSUE THREAD

**Issue by lkngtn** [aragon/aragon-cli#347]
Not sure if this belongs in the CLI, but currently if you create and deploy an organization with the CLI you are not able to claim an aragonid as you would if creating an organization using the standard onboarding process. 

It would be nice if organization created using the CLI could be accessed in the same way (eg  mainnet.aragon.org/#/[id].aragonid.eth

**Comment by lkngtn** [comment]
It looks like we could interact with aragonid directly 

https://etherscan.io/tx/0xa8dccbdc3a29229f3b6fa87889cbae7a4131861d033a3fca3e1e6ade2841c05b

- subnode is the keccak256 hash of the name you want
- owner should be the kernel addr

cc: @izqui

**Comment by luisivan** [comment]
+1, this should be built into the CLI, seems like a quick win

**Comment by sohkai** [comment]
@lkngtn Yes, you can interact with the `aragonid` registrar directly (see https://github.com/aragon/deployments for the addresses of it on each environment). It operates on a first-in-first-register basis right now.

**Comment by 0xGabi** [comment]
Reuse Brett tool: https://github.com/sohkai/assign-aragon-id
