### ISSUE TITLE
Document aragon publish command on how to publish just "dist" folder to ipfs instead of the whole project

### ISSUE THREAD

**Issue by ottodevs** [aragon/aragon-cli#348]
The title is just self explanatory, but here are some proofs of that: 
https://ipfs.eth.aragon.network/ipfs/Qmb4PuxVRwE9ZNMrRqaz2rk6yRtRxxHiNUMrT8u23VUJD7
https://ipfs.eth.aragon.network/ipfs/QmaYZUv2SVzjTMCPbEkGW4DppkqC71SHR5kDcQ71R5JXyH
https://ipfs.eth.aragon.network/ipfs/QmULX5QS7xLAmAYqfWcSJXZ8Hwyoi38dKhjmbUZM9pvhaD

If that is the expected behavior, then I think it is not really efficient, I don't see why is it needed to duplicate the manifest files into dist folder or to upload even package.json to load the aragon app into the wrapper... I think it was only uploading the dist folder in previous versions.

**Comment by sohkai** [comment]
It's hard for the tool to know how you'd like to set up your published directory, so a safe default is to publish the entire directory. We could probably add some more [documentation to the command](https://hack.aragon.org/docs/cli-usage.html#aragon-apm-publish) about its default behaviour and what recommended usage is.

You can target a particular directory to publish, using `--files` (e.g. we always publish apps with `aragon apm publish <version> --environment <environment> --files app/build`)

**Comment by 0xGabi** [comment]
Fixed in #364
