### ISSUE TITLE
aragon ipfs command use is obscure and undocumented

### ISSUE THREAD

**Issue by ottodevs** [aragon/aragon-cli#349]
What are the benefits against just using the regular ipfs command? What is it doing internally? It should have some documentation, even if the developer should not trust and be responsible of checking the code to know what is exactly doing.

**Comment by sohkai** [comment]
[It is documented](https://hack.aragon.org/docs/cli-usage.html#aragon-ipfs), but perhaps we could add a few more details to it?

Running `aragon ipfs` basically sets some configuration details to be compatible with aragonCLI and then adds some required files from the local chain so it doesn't have to try and fetch them over the network.

**Comment by 0xGabi** [comment]
Fixed in #364
