### ISSUE TITLE
"gas required exceeds allowance or always failing transaction" when calling dao acl grant

### ISSUE THREAD

**Issue by lkngtn** [aragon/aragon-cli#350]
I was attempting to clean up permissions in an organization on rinkeby using `dao acl grant` and got  the following error:

```
$ dao --environment aragon:rinkeby acl grant 0x4458d2cad6bf149eef653f9bcadd1daba38e6fda 92f2b71bbf45e26dd105b19794cc2541a5fc9785 CREATE_PERMISSIONS_ROLE 0xB8C80B8d36C072Bc4cFf0bC8E08D111f80b96F13
 ✔ Generating transaction
 ✖ Sending transaction
   → gas required exceeds allowance or always failing transaction
 ✖ gas required exceeds allowance or always failing transaction
```

When performing  this same operation from the UI through the permission app, I do not see the error, so this can be worked around by using the UI but not sure why it would fail here. 

`dao acl grant` seems to work for other permissions, but consistently gets that error for `CREATE_PERMISSIONS_ROLE`

**Comment by 0xGabi** [comment]
I test it with the last last version (`5.9.4`) and is working correctly. Will close the issue for now.
