### ISSUE TITLE
E2E tests with sharness

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#358]
The CLI can break unexpectedly due to external dependencies (like https://github.com/aragon/aragon-cli/issues/274 and https://github.com/aragon/aragon-cli/issues/215) or changes in the environment (node/os).

Library: [sharness](https://github.com/chriscool/sharness)
Examples: [ipfs-sharness-tests](https://github.com/ipfs/ipfs-sharness-tests)

Note: There is huge value in having this set up, and the most important commands like `create-aragon-app` and `aragon run` tested, but not so much in having everything tested, although it make sense to do it with the help of the community as these are really great first issues.

Commands to test:
- [x] aragon ipfs
- [ ] aragon devchain
- [ ] aragon run
- [x] create-aragon-app
- TBD

**Comment by 0xGabi** [comment]
After discussion in #363 we decide to migrate tests to node
