### ISSUE TITLE
Allow to skip arapp.json checks in `aragon apm publish`

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-cli#362]
Currently `aragon.aragonpm.eth` which is a frontend-only package cannot be published using the CLI as its arapp is lacking both `roles` and `path`, I found this while publishing another contract-less package today.

I think this is a good behavior in general, although we should have a flag (`--skip-arapp-check`) to skip this check and just move forward.

**Comment by sohkai** [comment]
This has been fixed on master (https://github.com/aragon/aragon-cli/pull/351).
