### ISSUE TITLE
Analyze role and role params against actual contract usage

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#370]
The CLI should warn (perhaps at `apm publish`?) if it detects that the roles set in `arapp.json` don't match those in the contract.

**Comment by dapplion** [comment]
@0xGabi Is there already a contract parser that extracts roles or it has to be built?

**Comment by 0xGabi** [comment]
@dapplion No, I don't think we have that functionality implemented on the CLI yet. Is this already available on other parts of the stack @sohkai ? 

We should include it on the [`solidity-extractor`](https://github.com/aragon/aragon-cli/blob/master/packages/aragon-cli/src/helpers/solidity-extractor.js).

**Comment by macor161** [comment]
@dapplion One way I think it would be possible is to find the roles in the generated artifact and then compare them with what is in the `arapp.json`. Somewhere around here: https://github.com/aragon/aragon-cli/blob/master/packages/aragon-cli/src/commands/apm_cmds/publish.js#L409

**Comment by dapplion** [comment]
@sohkai @0xGabi @macor161 We don't we use the `ast` from the truffle build artifacts instead of parsing the source code with regex? I believe it would be much reliable.

@sohkai The validation that could be done against arapp.json is the name of the role and the number of parameters. You that be enough? The information provided in arapp.json is not enough to match each param individually.
```json
    {
      "name": "Create new payments",
      "id": "CREATE_PAYMENTS_ROLE",
      "params": [
        "Token address",
        "Receiver address",
        "Token amount",
        "Payment interval",
        "Max repeats",
        "Initial payment time"
      ]
    }
```
```java
authP(CREATE_PAYMENTS_ROLE, _arr(_token, _receiver, _amount, MAX_UINT256, uint256(1), getTimestamp()))
```

**Comment by macor161** [comment]
@dapplion 

> Why don't we use the ast from the truffle build artifacts instead of parsing the source code with regex? I believe it would be much reliable.

Good question. I will have to confirm this but perhaps it was just simpler to do a couple of regex than to go through the whole AST tree.

Please also note that we will temporarily halt merging pull requests so we can refactor the code a little bit.

**Comment by sohkai** [comment]
> Why don't we use the ast from the truffle build artifacts instead of parsing the source code with regex? I believe it would be much reliable.

Truffle before v5 would not include the natspec as part of its ast, so we had to parse it manually before.

**Comment by dapplion** [comment]
Awesome, thank you @sohkai for the clarification. Then, this PR https://github.com/aragon/aragon-cli/pull/863 satisfies your last comment.

However, let's revisit it after the refactor.

**Comment by 0xGabi** [comment]
We should handle this on the `generateApplicationArtifact` function of the toolkit.
