### ISSUE TITLE
Merge default environments if there is an arapp.json

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#373]
This issue was funded with **45 DAI**, see more issues on our dao [projects app](https://rinkeby.aragon.org/#/meshteam.aragonid.eth/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8).
---
The CLI should warn you that if you have an `arapp.json` file in your current working directory, the default environments (e.g.: `aragon:rinkeby`) are not available, you can only use what you have in `arapp.json`.

Or, instead of warning, we could "merge" these environments.

**Comment by dapplion** [comment]
So, should the environments be merged or show a warning?

**Comment by 0xGabi** [comment]
Probably better if we can merge them so is a better UX. Otherwise a warning is nice. 

What would be great is to have a interactive list of the available environments the user could choose from...nevertheless I wonder if we want this to be the main flow and how to have a way to choose the default.
