### ISSUE TITLE
Nonce too low issue

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#378]
From #dev-help, experienced by a couple of users:

```
PS C:\Users\daniel> aragon dao new --environment aragon:rinkeby
 √ Fetching kit bare-kit.aragonpm.eth@latest
 × Create new DAO from kit
   → nonce too low
   Checking DAO
 × nonce too low
```

Possible workarounds:
- https://github.com/levelkdev/aragon-cli/commit/0c707948642c09ca68c433942a344c118e0dc355
- https://github.com/levelkdev/aragon-cli/commit/4f472164e995d7a232327c0e31173c407a945315
- "I switched nodes and it was fixed."

**Comment by 0xGabi** [comment]
@0x6431346e we should close this? The problem was fix, it was a problem with Infura node
