### ISSUE TITLE
Avoid installing IPFS binary if user has already installed IPFS

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#380]
This issue was funded with **120 DAI**, see more issues on our dao [projects app](https://rinkeby.aragon.org/#/meshteam.aragonid.eth/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8).
---
Perhaps instead of using an `npm` dependency, which makes installing the CLI slower, we could only download and install IPFS if we can't find a user-installed IPFS binary the first time we need to use it?

**Comment by 0x6431346e** [comment]
> Perhaps instead of using an `npm` dependency, which makes installing the CLI slower, we could only download and install IPFS if we can't find a user-installed IPFS binary the first time we need to use it?

I think users are also kind of "forced" to install the binary themselves if they want to use `ipfs add` or any commands other than `aragon ipfs`
