### ISSUE TITLE
Gracefully handle IPFS binary being unavailable

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#381]
See https://github.com/aragon/aragon-apps/issues/694; IPFS being unavailable blocks installs for users in projects that include `@aragon/cli` as a dependency.

**Comment by 0x6431346e** [comment]
Any idea of how we could handle this? If we skip it how would the user retry?

**Comment by sohkai** [comment]
I was thinking we could combine this with #380; if we try to use a command that requires IPFS, and downloading IPFS doesn't work, we tell them that the functionality can't be accessed and they need to install IPFS themselves.

Perhaps this could be done similarly to how we clone and install the client in `aragon run`?
