### ISSUE TITLE
apm publish results in: Transaction would not succeed

### ISSUE THREAD

**Issue by mikehoff** [aragon/aragon-cli#388]
I am trying to run
`aragon apm publish major --environment staging
`
with the following result
```
✖ Publish soton.open.aragonpm.eth
   → Transaction would not succeed ("gas required exceeds allowance or always failing transaction")
```

not even sure where to start with troubleshooting this? thanks!

**Comment by sohkai** [comment]
@mikehoff I don't think we have `open.aragonpm.eth` deployed on staging since we use it mostly internally before releasing client builds. However, this is something we should open up, to make the "official" rinkeby one more "official" :).

**Comment by sohkai** [comment]
Closing for https://github.com/aragon/deployments/issues/54.

**Comment by 0x6431346e** [comment]
@sohkai I don't think he was referring to the default [`aragon:staging`](https://github.com/aragon/aragon-cli/blob/master/packages/aragon-cli/config/environments.default.json#L5) environment, but rather the [`staging`](https://github.com/aragon/aragon-react-boilerplate/blob/master/arapp.json#L19) environment that comes with the boilerplate. I can see how this will be causing confusion though...

@mikehoff did you work it out?
I can see there's something published at `soton.open.aragonpm.eth` now:
```
PS C:\Users\daniel> aragon apm info soton.open.aragonpm.eth --environment aragon:rinkeby
 √ Fetching soton.open.aragonpm.eth@latest
{
  "contractAddress": "0xd9D3a5b7f8924B5D6441C13eb0f735e020D3E2A2",
  "version": "1.0.0"
}
```

**Comment by sohkai** [comment]
@0x6431346e Those two should be the same environment though; @mikehoff's trying to push `soton.open.aragonpm.eth` to an ENS rooted at `0x98df287b6c145399aaa709692c8d308357bc085d` but we don't have `open.aragonpm.eth` registered on that ENS registry.
