### ISSUE TITLE
Unable to use "your first aragon app"

### ISSUE THREAD

**Issue by DiegoCoyote** [aragon/aragon-cli#391]
Hi. I’m quite new in this world of blockchain and Aragon apps. In fact, I'm also new in this platform so I may have write this problem in an inappropate place. (Please tell me if I must ask this issue in another place).

I’m using Windows 10, 64 bits home edition. I’ve already installed all the necessary packages and programmes to start with Aragon, but I can’t run the tutorial properly. I mean that I can compile and run it, but it doesn’t work as it was supposed to do. The app appears in a tab in my Firefox browser and the “Counter” App appears in it. But the only things I can see are the buttons to increment and decrement the counter and the three dots I wrote in the “index.html” file. That is, the same as opening only the html file in my browser. I can't even see the text "The counter is 0", as I can read in the tutorial.

I’ve followed the tutorial step by step, but as I’ve not much experience with these languages I wonder if I may have written something wrong or in an inappropriate place. What’s more, the file “CounterApp.sol” contains quite different code from the code that I read in the tutorial. While in the tutorial “value +=1” is used to increment the counter in 1, in the file that I got, the “SafeMath” library and the code “value = value.add(step)” are used to increment the counter the amount of “step”, so I don’t know whether I’ve made some mistake due to this kind of differences or to my lack of knowledge, although I think this is not the problem.

The most difficult point I’ve found is where to put the line to build the script into “package.json” file, because I don’t know whether I have to replace any existing line or where to write it. In fact, I've tried several options to change this "package.json" file, but the outcome has been always the same.
I'm not running anything else, such as Metamask, because I understand this is for running the app from an HTTP service as it is said in the tutorial, and I don't want to do this until I get de "counter" working properly.

I’m attaching a zip file with the files I’ve changed according to the tutorial (not the files that needed no changes), and a screenshot of what I get when I run de app, hoping somebody here can read what I’ve written and help me to launch correctly the app, because I think it will help me to learn how to build Aragon apps.

Thanks a lot for your help.

**Comment by 0x6431346e** [comment]
It's a *very* dangerous security practice to open files from unknown sources as they can contain malware. Please remove this archive.
I'd be happy to assist you in uploading it to GitHub.

**Comment by DiegoCoyote** [comment]
Hi. Thanks for the warning. I'm ashamed for having published mi first issue in such a bad way...
I have edited the previous comment and deleted the link to the zip file, and deleted that comment. (But I don't know how to delete the file itself).
Please, assist me in getting help. Where and how can I upload the files I want to share to be helped? Should I just copy the files content here? There are too many code lines...
I don't want to make more mistakes, so I'd be grateful if you could help me.

**Comment by 0x6431346e** [comment]
> Hi. Thanks for the warning. I'm ashamed for having published mi first issue in such a bad way...
> I have edited the previous comment and deleted the link to the zip file, and deleted that comment. (But I don't know how to delete the file itself).
> Please, assist me in getting help. Where and how can I upload the files I want to share to be helped? Should I just copy the files content here? There are too many code lines...
> I don't want to make more mistakes, so I'd be grateful if you could help me.

No problem. It's an opportunity to learn which is nothing to be ashamed of, IMO.

1. Before uploading them to GitHub you would need to [create a public repository](https://help.github.com/en/articles/create-a-repo).
2. When prompted with the Quick setup screen, you can choose to upload files:
![image](https://user-images.githubusercontent.com/26041347/53727292-87fccc80-3e78-11e9-8033-8e0556787a9d.png)
3. After selecting the files you want to upload, you commit your changes and that's it. 😄

**Comment by DiegoCoyote** [comment]
Hi! Thanks for the advice. I've create mi first repository [https://github.com/DiegoCoyote/To-learn-repository](url)
I've uploaded the files, and explained my problem in the "Readme.md" file. But I don't know what to do next to be helped, although I suppose I've to close this thread and wait to be helped. But if there is anything else I have to do, ask for it and I'll do it asap.

**Comment by DiegoCoyote** [comment]
Downloaded and executed the fixed tutorial. It runs perfectly. Thanks a lot! Now it's time for me to learn from it.

**Comment by 0x6431346e** [comment]
> Downloaded and executed the fixed tutorial. It runs perfectly. Thanks a lot! Now it's time for me to learn from it.

Awesome! 
Thank you for reporting it!
