### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#395]
Remove unused dependencies:

- [x]  `@aragon/templates-beta`

Update:

- [x] `@aragon` packages to new stable versions

Unpin:

- [x] `truffle`

- [x] `yargs`

- [x] `ganache-core` https://github.com/aragon/aragon-cli/issues/321

- [x] `web3` https://github.com/ethereum/web3.js/issues/2800 #354 

## Status

#431
- removes `bignumber` which looks like is not used, was introduced [here](https://github.com/aragon/aragon-cli/commit/a0f997c07b2e347a850d07c8a616c47a2962b741), so we should test dao install still works
- updates `fs-extra` which has a lot of changes to the `copy()` functions, so we should test that the artifacts are copied correctly during `apm publish`
- updates `ganache-core` so we should test if our aragen snapshot is compatible (`aragon run` should be enough)
- updates truffle & yargs & web3 

#464 
- fixes the `tmp-promise` version I updated by mistake & adds more node versions to `travis.yml` ([v12 is not working](https://github.com/aragon/aragon-cli/issues/461))

#463 
- updates the rest of `create-aragon-app` and adds the `e2e-tests` package to greenkeeper

**Comment by 0x6431346e** [comment]
As per @sohkai 's suggestion we can explore using https://dependabot.com/ as an alternative to greenkeeper

**Comment by 0xGabi** [comment]
I think we can close this issue now and create specific issues for particular updates or fixes needed
