### ISSUE TITLE
Code owners

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#412]
https://help.github.com/en/articles/about-code-owners

**Comment by sohkai** [comment]
We actually had a conversation last week about this, and how we should apply it throughout the Aragon project's github organization.

Will keep you posted, but we'll likely be adding this (amongst other recommendations) to most repos :).

**Comment by sohkai** [comment]
We actually had a conversation last week about this, and how we should apply it throughout the Aragon project's github organization.

Will keep you posted, but we'll likely be adding this (amongst other recommendations) to most repos :).

**Comment by sohkai** [comment]
@0x6431346e I believe this has been completed as part of https://github.com/aragon/aragon-cli/pull/428?

I have yet to go through the Aragon org repos to align them all to have the appropriate code owners though... :(

**Comment by 0xGabi** [comment]
Close with #428
