### ISSUE TITLE
Solidity parser ignore @notice strings on modifiers

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#427]
This issue was funded with **75 DAI**, see more issues on our dao [projects app](https://rinkeby.aragon.org/#/meshteam.aragonid.eth/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8).
---
Example:
```
@notice modifier to check if coin is not issued yet
    modifier isIssued() {
```
Currently, it throws: `→ Cannot read property '1' of null`

https://github.com/aragon/aragon-cli/blob/3cf24ad0f2b7d7cfce20dc2a7f4c39cfc32a0035/packages/aragon-cli/src/helpers/solidity-extractor.js#L18

We could also come up with a better error message.

**Comment by sembrestels** [comment]
Also when a function is commented, such as:
```solidity
    /**
     * @notice Increment the counter by `step`
     * @param step Amount to increment by
     */
    // function increment(uint256 step) external auth(INCREMENT_ROLE) {
    //     value = value.add(step);
    //     emit Increment(msg.sender, step);
    // }
```

It throws the exact same message.
