### ISSUE TITLE
Solidity extractor has false positives on multiline function declarations

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#43]
Multi-line declarations like

```sol
    function _makePaymentTransaction(
        ERC20 _token,
        address _receiver,
        uint256 _amount,
        uint256 _paymentId
        ) internal
    {
        ...
    }
```

Are treated as `public` by the regex.

Unfortunately the [antr4 grammar](https://github.com/solidityj/solidity-antlr4) doesn't support natspec yet, but maybe we should be looking at something more robust for this...

**Comment by onbjerg** [comment]
We used to use a package Jorge made called `solidity-extractor`, but it was broken or something so we tried to simplify it with regex

**Comment by izqui** [comment]
@sohkai maybe we could create an issue to migrate away from our `solidity-extractor` and use a proper parser, though I'm worried about how we could support many solc versions with potentially different ASTs (the parsers may break)

**Comment by sohkai** [comment]
Yes... we'd have to be strict about which cli versions support which solc versions. Ideally after 0.5 solc won't be including breaking changes in the AST.

**Comment by sohkai** [comment]
AFAIK this isn't fixed; the artifact.json in finance still has non-public functions being included due to the multi-line issue.
