### ISSUE TITLE
Move off of deprecated @aragon/messenger

### ISSUE THREAD

**Issue by MidnightLightning** [aragon/aragon-cli#441]
This issue was funded with **45 DAI**, see more issues on our dao [projects app](https://rinkeby.aragon.org/#/meshteam.aragonid.eth/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8).
---
## 🐛 Bug Report

When installing `aragon-cli` via `npm install -g @aragon/cli`, there is a deprecation warning that appears:

```
npm WARN deprecated @aragon/messenger@1.0.0: @aragon/messenger has been renamed to @aragon/rpc-messenger and now relies on RxJS 6. Please update your package.json and migrate from RxJS 5.
```

The `@aragon/messenger`/`@aragon/rpc-messenger` library is from this same team, so having this tool be behind enough to be using a deprecated version doesn't seem to be the best for stability nor security.

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes

#### Mainnet or testnet?

N/A

#### Organization

N/A

#### Environment
Windows 10 running Docker version 18.09.2, using Aragon inside a `node:latest` container.

## To Reproduce
Run `docker run --rm --name=aragon node:latest npm install -g @aragon/cli`

## Expected behavior
Install the application with no warnings

## Actual Behavior
Warnings output that deprecated packages are being used.

**Comment by 0x6431346e** [comment]
I think the breaking change here (besides the naming) is that it now uses `rxjs@6`, so we need to upgrade to that syntax as well.

Would you like to tackle this issue an open a PR?

We could definitely use some help and we plan on adding bounties to a bunch of issues soon!

**Comment by MidnightLightning** [comment]
I could possibly take a stab at it; I'm just getting started with Aragon development trying to contribute to an existing project using Aragon. In setting up my development environment, I noticed there's several deprecated warnings in the aragon-cli setup that should probably be addressed, but thought this one was particularly suspicious, since it's a tool from the same toolchain/team.

**Comment by sohkai** [comment]
@0x6431346e AFAIK aragonCLI uses almost zero rxjs directly (all of it just comes from subscribing to its observables in `aragonjs-wrapper.js`) so the upgrade should be fairly seamless and just involve updating the package versions.

The other API changes from `@aragon/wrapper@3` to `@aragon/wrapper@5` also shouldn't be a problem here, since the CLI doesn't run apps.

**Comment by 0x6431346e** [comment]
> @0x6431346e AFAIK aragonCLI uses almost zero rxjs directly (all of it just comes from subscribing to its observables in `aragonjs-wrapper.js`) so the upgrade should be fairly seamless and just involve updating the package versions.
> 
> The other API changes from `@aragon/wrapper@3` to `@aragon/wrapper@5` also shouldn't be a problem here, since the CLI doesn't run apps.

Oh ok, I thought we might use an operator here and there.

**Comment by sohkai** [comment]
@0xGabi I believe this has been fixed now, since the CLI is using `@aragon/wrapper@5`?
