### ISSUE TITLE
Split ipfs rpc options

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#445]
## 🚀 Feature

Split the `apm.ipfs.rpc` option into two:
- Allow specifying an ipfs gateway to read from
- Allow specifying an ipfs node to write to

## Motivation

Power users interacting with their DAO on rinkeby or mainnet have trouble finding the artifacts for these apps. That's because the CLI uses the `localhost` node by default, which does not bundle ALL the versions of the apps. See https://github.com/aragon/aragon-cli/issues/419

Currently, specifying the aragon ipfs node helps:
```
aragon apm info voting --environment aragon:mainnet --apm.ipfs.rpc https://ipfs.eth.aragon.network/ipfs 
```

This works, surprisingly, but only on some commands, because `apm.js` uses an old version of the `ipfs-api` package.
Note: some commands don't even pass along the apmOptions to the wrapper (only the ens option), e.g.: `dao apps`.

This shouldn't work at all because `https://ipfs.eth.aragon.network/ipfs` does not expose the API (port `5001`), but only the gateway (port `8080`), for obvious reasons.

## Pitch

1. We should do the reading only from the gateway option.
2. It should default to `localhost:5001` and `localhost:8080`, so that `aragon run` and other commands that rely on local assets would still work as expected.

As a second iteration we could include these options in `environments` 🤔.

**Comment by 0xGabi** [comment]
> As a second iteration we could include these options in environments 🤔.

Definitly, we should include more configurations (e.g. gas-limit) for each environment on the `arrap.json`.

**Comment by 0x6431346e** [comment]
> This works, surprisingly, but only on some commands, because `apm.js` uses an old version of the `ipfs-api` package.
> Note: some commands don't even pass along the apmOptions to the wrapper (only the ens option), e.g.: `dao apps`.
> 
> This shouldn't work at all because `https://ipfs.eth.aragon.network/ipfs` does not expose the API (port `5001`), but only the gateway (port `8080`), for obvious reasons.

So apparently is not working because is using an old version, but rather it is possible to connect to gateways in a `read-only` kind of way: https://github.com/ipfs/js-ipfs-http-client/issues/787#issuecomment-398005605

Not very useful, but the good thing is that apm takes a `gateway` option and can download files using `http`: https://github.com/aragon/apm.js/blob/master/src/providers/ipfs.js#L24

which made this easier to implement in #519.

I wonder if we can add a [progress bar to the CLI](https://www.npmjs.com/package/progress#download), hopefully the gateways sends the `content-length` headers.
