### ISSUE TITLE
Bundle cli-commons into a package

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#448]
This issue was funded with **105 DAI**, see more issues on our dao [projects app](https://rinkeby.aragon.org/#/meshteam.aragonid.eth/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8).
---
## 🚀 Feature

As part of moving the cli functionality to aragen (see https://github.com/aragon/aragon-cli/pull/394 and https://github.com/aragon/aragen/pull/24/) the `@aragon/cli` now depends on `aragen` for the `ConsoleReporter` which feels weird.

Also, `create-aragon-app` duplicates these files.

We should bundle any shared code between different CLIs to make things more maintainable.

**Comment by 0xGabi** [comment]
This is already done with `@aragon/cli-utils` package
