### ISSUE TITLE
On major deployments, add `methods` from old versions' artifact.jsons

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#450]
This is now an issue with our Finance app, where we used to have a method named `newPayment()` but has since been split out into two methods (`newScheduledPayment()` and `newImmediatePayment()`).

It would be nice if the CLI automatically consulted old versions' `artifact.jsons and included them as part of a versioned list of old methods, so radspec descriptions can still work on breaking upgrades.

**Comment by 0xGabi** [comment]
@sohkai I would like to confirm with you about the approach before going forward. We discuss it with @0x6431346e and we think this could be a new property in the `artifact.json`:
```
 "old-functions" : {
 "1.0.0": [{}]
 "2.0.0": [{}]
}
```
If we follow this path then `aragon.js` needs to change to look into this new property.

Can you pointing out to me where radspec make use of this, as an example. Thanks

**Comment by sohkai** [comment]
@0xGabi Yep, you found the relevant bit :).

I think that makes sense; a few suggestions:

- Perhaps `oldFunctions` is better as the key, as everything else in the `artifact.json` file should be in camel case
- Perhaps it would make sense to only include functions that are not in the current list of functions (tested via their function signatures), to avoid duplicates

**Comment by 0xGabi** [comment]
Perfect!

**Comment by sohkai** [comment]
@0xGabi As it turns out... we actually need the abi for radspec evaluation to work as well. Maybe we can modify the `methods` declarations so it comes with an `abi` for the method too (some slight duplication, since we have the current version's abi, but this makes it consistent between the current `methods` and previous `methods`).

Currently:

```json
{
  "abi": [ ... ],
  "functions": [
    {
      "sig": "...",
      "roles": [ ... ],
      "notice": ""
     },
     ...
  ]
}
```

What we could have:

```diff
{
  "abi": [ ... ],
  "functions": [
    {
      "sig": "...",
      "roles": [ ... ],
      "notice": "",
+    "abi": [ ... ]
     },
     ...
  ],
+ "oldFunctions": [
+   "v1.0.0": [
+     {
+       "sig": "...",
+       "roles": [ ... ],
+       "notice": "",
+      "abi": [ ... ]
+      },
+   ]
}
```

**Comment by 0xGabi** [comment]
Oh great, thanks for the heads up, also I decide rename `oldFunctions to `deprecated` or `deprecatedFunctions` otherwise.
