### ISSUE TITLE
Output proxy app address when installing app with dao install

### ISSUE THREAD

**Issue by lkngtn** [aragon/aragon-cli#451]
## 🚀 Feature

When deploying organizations with the cli, its common to have to install and app and then use the apps proxy address in subsequent commands. This would be much easier if the proxy address was included in the install output. 

In order to get the proxy address you have to use `dao apps [dao] --all` and then look for the app under permissionless apps

## Motivation

reduce commands necessary to deploy a dao

## Pitch

less commands is better than more commands. 🙃

---
This issue is funded with **60 DAI**, see more issues on our dao [projects app](https://rinkeby.aragon.org/#/meshteam.aragonid.eth/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8).

**Comment by 0xGabi** [comment]
Reopen to close the issue on the dao

**Comment by 0xGabi** [comment]
@fabriziovigevani  Thank you for you work. Can you provide me with a mainnet address?

**Comment by fabriziovigevani** [comment]
my mainnet address is 0x902B5924759BdCCA3ff85099c2A11c4a79f4BEd0 
Thank you!
