### ISSUE TITLE
Allow declaring external contract dependencies

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#452]
From the chat:

mike.calvanese 7:59 PM
>I added a library to our aragon app contract, and now getting an error trying to deploy ... `The data field must be HEX encoded data`
wondering if it's something similar to this issue in zos with library linking https://github.com/zeppelinos/zos/issues/751
the contract I'm trying to deploy is https://github.com/levelkdev/futarchy-app/blob/aragon-upgrades/contracts/Futarchy.sol

mike.calvanese 10:09 PM
>I implemented a workaround https://github.com/levelkdev/futarchy-app/commit/9a97599ca218167d24f9f34b257c5990f658a0de but definitely not ideal. is there support for something like truffle's `link()` in aragon that I'm missing?

sohkai Established Member 11:17 AM
>Hmm indeed, we definitely don't handle libraries well in aragonCLI cc @0x6431346e  @0xGabi . We could perhaps have a "linking" mapping in the arapp.json's environments, since each environment would have a different library address. You'd still have to deploy the library yourself via a script, but afterwards it'd be more seamless.

**Comment by cslarson** [comment]
I've [taken a stab](https://github.com/daonuts/aragon-cli/commit/a271826d20ba4a4c8bb6fb65f53917ce1e803cb3) at adding this feature to aragon-cli. I'd be happy to make further modifications, add test coverage, etc, if it would help/be considered for pulling into the main aragon-cli.

My approach is as follows:

1. add `links` array in arapp.json' environments. links have `name` and `address` attributes.
1. pass `module` to deploy task to make `module.environments` available there
1. add `expandLink` function, exported from utils. adds appropriate regex and bytes version of address (removes `0x`)
1. in deploy task, executes replace on the bytecode for each link placeholder

**Comment by 0xGabi** [comment]
@cslarson I took a look and seems like a good solution. Please submit a PR so we can further review it and add this functionality

**Comment by 0xGabi** [comment]
This feature was included in #804
