### ISSUE TITLE
aragon run gets stuck at applying version bump

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#457]
## 🐛 Bug Report

Using the version `5.7.1` and doing `aragon run` throws:
```
(node:758) UnhandledPromiseRejectionWarning: Error: Node error: {"message":"Method [object Object] not supported.","code":-32000,"data":{"stack":"Error: Method [object Object] not supported.\n    at Get
```

**Comment by 0x6431346e** [comment]
Why was it working when building locally?

Because `web3@1.0.0-beta.34` was pinned in `@aragon/cli` and `npm` deduped it in `@aragon/aragen`:

```
± % npm ls web3                                                                                                           !10690
@aragon/cli@5.7.1 /home/daniel/repos/aragon/aragon-cli/packages/aragon-cli
├─┬ @aragon/apps-finance@2.1.0
│ └─┬ @aragon/os@4.0.0
│   └─┬ truffle-hdwallet-provider@0.0.3
│     └── web3@0.18.4 
├─┬ @aragon/apps-vault@3.0.0
│ └─┬ @aragon/os@4.0.0
│   └─┬ truffle-hdwallet-provider@0.0.3
│     └── web3@0.18.4 
├─┬ @aragon/aragen@4.0.2
│ └── web3@1.0.0-beta.34  deduped
├─┬ @aragon/os@4.2.0
│ └─┬ truffle-hdwallet-provider@0.0.3
│   ├── web3@0.18.4 
│   └─┬ web3-provider-engine@8.6.1
│     └── web3@0.16.0 
├─┬ @aragon/wrapper@5.0.0-rc.5
│ ├─┬ ethereum-ens@0.7.4
│ │ └── web3@0.19.1 
│ └── web3@1.0.0-beta.33 
├─┬ ganache-core@2.2.1
│ └── web3@1.0.0-beta.34 
├─┬ truffle-hdwallet-provider@1.0.8
│ └── web3@1.0.0-beta.37 
├─┬ truffle-hdwallet-provider-privkey@0.3.0
│ └── web3@0.20.7 
└── web3@1.0.0-beta.34 
```

Project install:
```
± % npm ls web3                                                                               !10695
foo@1.0.0 /home/daniel/repos/aragon/pg/foo
├─┬ @aragon/cli@5.7.1
│ ├─┬ @aragon/aragen@4.0.2
│ │ └── web3@1.0.0-beta.54 
│ ├─┬ @aragon/wrapper@5.0.0-rc.5
│ │ ├─┬ ethereum-ens@0.7.4
│ │ │ └── web3@0.19.1 
│ │ └── web3@1.0.0-beta.33 
│ ├─┬ ganache-core@2.2.1
│ │ └── web3@1.0.0-beta.34 
│ ├─┬ truffle-hdwallet-provider@1.0.8
│ │ └── web3@1.0.0-beta.37 
│ ├─┬ truffle-hdwallet-provider-privkey@0.3.0
│ │ └── web3@0.20.7 
│ └── web3@1.0.0-beta.34 
├─┬ @aragon/os@4.2.0
│ └─┬ truffle-hdwallet-provider@0.0.3
│   ├── web3@0.18.4 
│   └─┬ web3-provider-engine@8.6.1
│     └── web3@0.16.0 
├─┬ solidity-coverage@0.5.11
│ └── web3@0.18.4 
└── web3@1.0.0-beta.34 
```

Related to: #354

**Comment by sohkai** [comment]
🤦‍♂web3

@0x6431346e @0xGabi Wondering if you two feel confident enough about the tests to see if we could migrate to a newer version of web3 for the CLI?

**Comment by 0x6431346e** [comment]
> web3
> 
> @0x6431346e @0xGabi Wondering if you two feel confident enough about the tests to see if we could migrate to a newer version of web3 for the CLI?

Not really :sweat_smile:, I will focus this week on adding tests and coverage so we can finally update all deps and let greenkeeper do its thing.

We still need to pin `web3` to something lower than `1.0.0-beta.54` as it is broken.
Not sure about `ganache-core`, I think we might finally be able to unpin `2.2.1`.

**Comment by sohkai** [comment]
Was it only broken because there were two conflicting versions?

**Comment by 0x6431346e** [comment]
> Was it only broken because there were two conflicting versions? In any case, web3.js is moving quickly towards a stable implementation quite soon so let's report anything odd that we see :).

Oh, haven't thought about that, it might be a conflict solvable by upgrading `ganache-core`. We currently use `2.2.1` and that version pins `web3` to `beta.34`: https://github.com/trufflesuite/ganache-core/blob/v2.2.1/npm-shrinkwrap.json#L4818

I've reported it here: https://github.com/ethereum/web3.js/issues/2800
