### ISSUE TITLE
Support node v12

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#461]
This issue was funded with **60 DAI**, see more issues on our dao [projects app](https://rinkeby.aragon.org/#/meshteam.aragonid.eth/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8).
---
See the travis builds: 

https://travis-ci.org/aragon/aragon-cli/builds/532301139?utm_source=github_status&utm_medium=notification

Specifically this error:

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v12.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v12.2.0/bin/node" "/home/travis/.nvm/versions/node/v12.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/aragon/aragon-cli/packages/aragon-cli/node_modules/ganache-core/node_modules/scrypt
gyp ERR! node -v v12.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```

We could try after updating `ganache-core`.
Related: https://github.com/trufflesuite/ganache-core/issues/425

**Comment by sohkai** [comment]
@0xGabi We've been able to upgrade ganache-core; could we retest this to see if node 12 now works (and run CI on node 12 as well)?

**Comment by 0xGabi** [comment]
I just tested it and the install worked 🥳 anyways I got some build errors with node-gyp. 

I'll test it a bit more and also try to install in a linux vm as well. Install is going to be much better once we separate ganache-core to his own package

**Comment by sohkai** [comment]
Looks like those build errors are for the native modules, and [keccak and secp256k1 specifically](https://github.com/trufflesuite/truffle/issues/1584).

They have fallback JS implementations so it's not going to break, but the situation is not ideal. Let's add node12 to the CI but keep advertising that users use node 10.

**Comment by 0xGabi** [comment]
Check with a Linux vm and it worked as well, I'll close this issue
