### ISSUE TITLE
Aragon run command hanging on "generating transaction..."

### ISSUE THREAD

**Issue by dstreppa** [aragon/aragon-cli#468]
## 🐛 Bug Report

Hi, I am pretty new with Aragon and I've started to play with it. I have a problem when I launch `aragon run`: the command hangs indefinitely on the `Generating transaction` phase.

Instead if I create simple dapps inside your https://github.com/aragon/aragon-react-boilerplate project I realize to correctly launch dapps and playing with them (command `npx aragon run --template Template --template-init @ARAGON_ENS`).

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?
Yes

#### Mainnet or testnet?

Devchain

#### Environment

- OS and OS version: Ubuntu 18.04.2 LTS
- Browser and browser version: Firefox 66.0.5
- Add any other context about the problem here.
<pre>
# aragon  -v
5.7.1
</pre>

## To Reproduce

<pre>
# npx create-aragon-app ds01 react
npx: installed 157 in 6.119s
 ✔ Preparing initialization
 ✔ Cloning app template
 ✔ Preparing template
 ✔ Installing package dependencies
 ✔ Created new application ds01.aragonpm.eth in ds01.
# cd ds01
# aragon run
 ✔ Start a local Ethereum network
 ✔ Check IPFS
 ❯ Publish app to APM
   ✔ Applying version bump (major)
   ✔ Deploy contract
   ✔ Determine contract address for version
   ✔ Building frontend
   ✔ Prepare files for publishing
   ✔ Generate application artifact
   ❯ Publish ds01.aragonpm.eth
     ⠙ Generating transaction
       → Fetching DAO at 0x983b4Df4E8458D56CFDC51B9d2149381AF80308A...
       Sending transaction
     Fetch published repo
   Create DAO
   Open DAO
</pre>

## Expected behavior

The command should correctly end instead to hang

## Actual Behavior

There are no errors/warnings in the output. The problem is the command hanging.

## Reproducible Demo

See the commands above

**Comment by 0x6431346e** [comment]
Hey @dstreppa , we released a fix for this ~6hrs ago.

Could you try re-installing the project dependencies?

1. `rm -rf node_modules package-lock.json`
2. `npm install`

After this, you doing `npm ls @aragon/wrapper` should print the correct version `5.0.0-rc.7`.

**Comment by dstreppa** [comment]
@0x6431346e thank you for the fix, I've done the updates but nothing has changed. I've also created a new project (see the output below), but with no results. There is always the hanging. I've also printed the npm and node version, maybe it can help.

<pre>
# npx create-aragon-app ds02 react
npx: installed 157 in 5.057s
 ✔ Preparing initialization
 ✔ Cloning app template
 ✔ Preparing template
 ✔ Installing package dependencies
 ✔ Created new application ds02.aragonpm.eth in ds02.
# cd ds02
# aragon run
 ✔ Start a local Ethereum network
 ✔ Check IPFS
 ❯ Publish app to APM
   ✔ Applying version bump (major)
   ✔ Deploy contract
   ✔ Determine contract address for version
   ✔ Building frontend
   ✔ Prepare files for publishing
   ✔ Generate application artifact
   ❯ Publish ds02.aragonpm.eth
     ⠼ Generating transaction
       → Fetching DAO at 0x983b4Df4E8458D56CFDC51B9d2149381AF80308A...
       Sending transaction
     Fetch published repo
   Create DAO
   Open DAO
^C
# npm ls @aragon/wrapper
ds02@1.0.0 /home/dstreppa/development/solidity/ds02
└─┬ @aragon/cli@5.7.1
  └── @aragon/wrapper@5.0.0-rc.7 
# node --version
v11.8.0
# npm --version
6.9.0

</pre>

**Comment by 0x6431346e** [comment]
> aragon run

It's because when you're doing `aragon run` without the `npx` prefix, it will run the CLI you have installed globally, and not the one installed in your project.

You can confirm by doing:
```
npm ls -g @aragon/wrapper
```

My suggestion is to reinstall the global package as well:
```
npm un -g @aragon/cli
npm i -g @aragon/cli
```

**Comment by dstreppa** [comment]
Ok, now using `npx aragon run` it works. 
@0x6431346e I prefer to have a specific installations for each projects, avoiding to use the global packages.

Thank you very much for the help.

**Comment by 0x6431346e** [comment]
Awesome!
