### ISSUE TITLE
Allow manual configuration of gas price when using aragonCLI in Terminal

### ISSUE THREAD

**Issue by chrishobcroft** [aragon/aragon-cli#499]
## 🚀 Feature

When using aragonCLI within `Terminal`, I would like to be able to manually configure the gas price.

Currently, it appears that this is hard coded to a gas price of 10 gwei, which for example made the installation of an app to a DAO (0.00783171 Ether = $1.87 at time of writing) more expensive than installing many paid-for apps from Apple App Store onto an iPhone. Furthermore, using `dao acl` to create new permissions using CLI is similarly expensive, which means that configuring apps with many permissions on acl is not feasible.

I understand from @0x6431346e that you can specify `gasPrice` in the truffle network, however as a non-user of truffle (like many end users), I cannot use this, so I appear to be stuck with the expensive hardcoded 10 gwei gas price, which makes all my aragonCLI calls very expensive.

Related: https://github.com/aragon/aragon-cli/issues/353
Related: https://github.com/aragon/aragon-cli/issues/346

## Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes.

## Motivation

To reduce the cost of configuring a mainnet DAO using aragonCLI - right now it's waay too expensive.

Furthermore, as referenced by @luisivan in [this issue](https://github.com/aragon/aragon-cli/issues/353), running `dao new` on mainnet comes at high costs.

## Pitch

Currently, to install an app into a DAO using aragonCLI, it costs $1.87 in gas, using a hard-coded gas price of 10 gwei.

Recommended gas price right now as per ethgasstation.info is 1 gwei, which means that the total cost could have been $0.187 - _a reduction of 90% in operating costs_.

This limits my freedom due to high costs of operating on the Aragon network.

By implementing such a feature, it will reduce the costs and lower the barriers to entry for users.

**Comment by sohkai** [comment]
It would be nice if the command prompted the user to suggest a gas price or defaulted to an api (e.g. [ethgasstation](https://docs.ethgasstation.info/)). `10` should be used as the worst-case fallback if we're at a lack for a better number.

**Comment by lkngtn** [comment]
Agree strongly with this! 

I would also love to have an estimate of total cost which is confirmed by the user by default.

**Comment by chrishobcroft** [comment]
What is the solution?
