### ISSUE TITLE
Improve the reliability when downloading IPFS at installation

### ISSUE THREAD

**Issue by deamme** [aragon/aragon-cli#505]
`npm install -g @aragon/cli` doesn't work because it's stuck on downloading https://dist.ipfs.io/go-ipfs/v0.4.18/go-ipfs_v0.4.18_linux-amd64.tar.gz - which doesn't resolve

The following version does resolve: https://dist.ipfs.io/go-ipfs/v0.4.21/go-ipfs_v0.4.21_linux-amd64.tar.gz

**Comment by deamme** [comment]
Seems like it's working now, although it can sometimes be unreliable since @osarrouy experienced this too before

**Comment by 0xGabi** [comment]
@deamme is this still an issue for you? I checked both Mac and Linux and seems to be fixed

**Comment by 0x6431346e** [comment]
Last week I bumped into this as well, I don't think there's much we can do about it though...

**Comment by 0x6431346e** [comment]
Started happening again...
I've opened an issue here: https://github.com/ipfs/go-ipfs/issues/6451

**Comment by 0xGabi** [comment]
I tried using `go-ipfs-dep` with `v0.4.21` and the issue still happening. Should we consider hosing the dependency ourselves?

**Comment by 0x6431346e** [comment]
Possible workaround:

1. Install `go-ipfs` "manually" from <https://github.com/ipfs/go-ipfs/releases/tag/v0.4.18> instead of dist.ipfs.io (make sure it's available in the PATH)
2. Install the CLI from source:
```
git clone https://github.com/aragon/aragon-cli.git
git checkout feat/make-go-ipfs-optional
npm install
npm run link
aragon --version --debug # should print whether and where it found the binary
```

**Comment by 0xGabi** [comment]
Related to https://github.com/ipfs/npm-go-ipfs-dep/issues/37

**Comment by 0x6431346e** [comment]
Should we pin the `dist.ipfs.io` website to the `ipfs.eth.aragon.network` node for redundancy?

Currently it resolves to:

```sh
$ ipfs dns dist.ipfs.io
/ipfs/QmVJL1ew9ytqZGR7Tg121tHEXPwbYVNxzHked3QzVgWEzD
```

It has `10.6` GB and if we pin it, when `dist.ipfs.io` goes down we can do:

```sh
aragon ipfs install --dist-url https://ipfs.eth.aragon.network/ipfs/QmVJL1ew9ytqZGR7Tg121tHEXPwbYVNxzHked3QzVgWEzD
```

cc: @sohkai

**Comment by sohkai** [comment]
@0x6431346e Do we download IPFS using IPFS itself? Is there a way to resolve the latest version of the go client?

Not opposed to pinning it, or just the latest version, but it's a bit of a problem if protocol labs themselves can't keep that hosted 😅.

**Comment by 0x6431346e** [comment]
> @0x6431346e Do we download IPFS using IPFS itself? Is there a way to resolve the latest version of the go client?

Using HTTP (and IPFS as well if it's not pinned).
I don't think there's a way to pin only the latest version, the `npm-go-ipfs` scripts check some metadata to see if the version exists: `https://dist.ipfs.io/go-ipfs/versions`.. (unless we write our own)

> Not opposed to pinning it, or just the latest version, but it's a bit of a problem if protocol labs themselves can't keep that hosted .

I think it would most likely happen again if there's a bug, someone makes a mistake, or their nodes are overwhelmed by traffic. 

---

On second thought, I just tried: `GO_IPFS_DIST_URL=https://ipfs.eth.aragon.network/ipfs/QmVJL1ew9ytqZGR7Tg121tHEXPwbYVNxzHked3QzVgWEzD/ npm i go-ipfs@0.4.18-hacky2`

And it installed in less than a minute. I think we can get away with not pinning it.

Same for `https://cloudflare-ipfs.com/ipfs`. 
I will add a note on the hack website.
