### ISSUE TITLE
Detect IPFS or HTTP server wasn't running and warn before fetching artifacts

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#509]
## 🚀 Feature

Posted by sohkai:
>We also discussed offline about if it made more sense to detect that the IPFS or local HTTP server wasn't running (and hence couldn't serve you the required artifact.json).

**Comment by sohkai** [comment]
With `aragon run`, we could do these preflight checks quite early, possibly even at the publishing step, and bail if the specified content wasn't available.

**Comment by 0xGabi** [comment]
@ajsantander @dapplion maybe you are already doing checks and we can close this one
