### ISSUE TITLE
Not able to start IPFS daemon

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-cli#514]
## 🐛 Bug Report

```
>aragon ipfs start
  ✖ Start IPFS
    → Unexpected token p in JSON at position 4
```

## Context

I'm using last `master` branch (version `5.9.6`)
Logging `apmOptions.ipfs.rpc` I see that it has:

```
{ protocol: 'https',
  host: 'ipfs.eth.aragon.network',
  port: null }
```
which seems different from what `--help` says:
```
  --apm.ipfs.rpc      An URI to the IPFS node used to publish files
                                      [default: "http://localhost:5001#default"]
```

If I run this instead:
```
> aragon ipfs start --apm.ipfs.rpc "http://localhost:5001#default"
```
I get the same result, and `apmOptions.ipfs.rpc` is still the same as before.

#### Environment

- OS and OS version: PureOS 8

**Comment by bingen** [comment]
May it be related to this? https://github.com/ipfs/js-ipfs-http-client/issues/779

**Comment by bingen** [comment]
If I start manually IPFS daemon and then run `aragon ipfs start --apm.ipfs.rpc "http://localhost:5001"`, then it works.

**Comment by 0xGabi** [comment]
I think this is the root cause: https://github.com/aragon/aragon-cli/commit/4bc4f36b083d87490a5bcf4a6931dbe5a8d54122

I didn't test `aragon apm publish` with a different network other than local 🤕
