### ISSUE TITLE
Add Changelog file

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#521]
## 💥 Proposal

Include a Changelog to the CD process. 

Use [chan](https://github.com/geut/chan) based on the [keepachangelog style.](https://keepachangelog.com/en/1.0.0/)

Example configuration from [lerna-travis demo](https://github.com/geut/lerna-travis-demo):
```son
"lerna:postversion": "chan release --group-changes $(node -p -e \"require('./lerna.json').version\") && git add CHANGELOG.md && git commit -m \"Update: changelog\" && git push --follow-tags",
"lerna:version": "lerna version prerelease --preid beta && yarn run lerna:postversion"
```

**Comment by sohkai** [comment]
I believe this is now done :).
