### ISSUE TITLE
Setup CI on Windows machines

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#527]
## 💥 Proposal

Using a service like [AppVeyor](https://www.appveyor.com/) or [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) in addition to Travis and GitHub Actions will let us know when the CLI stops working on Windows (I have a feeling it doesn't :sweat_smile: ).

Follow the appveyor.yml reference.

**Comment by 0xGabi** [comment]
Superseded by #1167
