### ISSUE TITLE
End-to-end test for publishing

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#536]
Would be great to have a test for `apm publish` and perhaps using the rinkeby environment as well, to tell whether it breaks.

Related: https://github.com/aragon/aragon-cli/pull/529 should fail.

And even better to snapshot the some artifacts like `manifest.json`.

**Comment by 0xGabi** [comment]
I already introduce this one in #426 🤘

**Comment by 0xGabi** [comment]
I can close this with #545
