### ISSUE TITLE
Generated artifact.json does not include public constants

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#56]
Things like [`address constant public ETH = address(0)`](https://github.com/aragon/aragon-apps/blob/f9f7a6dd579a1521748c84e1af034ea891da06f9/apps/finance/contracts/Finance.sol#L18) are not included.

**Comment by 0xGabi** [comment]
@sohkai @macor161 we were wondering with @dapplion if you know why truffle is not including this information? So to fix this one we need to manually edit the ABIs?

**Comment by macor161** [comment]
I think we can close this now. I just tested it quickly in dev and I was able to call both values from the frontend:
```solidity
    uint constant public test1 = 123;
    address constant public test2 = address(0);
```
In any case, I don't think it would be a problem with truffle though.

**Comment by sohkai** [comment]
Nice! Maybe this was transparently fixed somewhere along the way.

It may be that I noticed that these public constants are not available in the "functions" area of the artifact.json, and this would be due to our solidity parser, but there is realistically no reason to include it there anyway.
