### ISSUE TITLE
Do not deploy a minime factory for each `dao token new`

### ISSUE THREAD

**Issue by lkngtn** [aragon/aragon-cli#561]
## Reduce gas cost for deploying a new token

Currently `dao token new` deploys a minime token factory, then deploys a new token using that factory. This is quite wasteful, the point of having a factory is to re-use it. 🙃

## Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

No

## Motivation

The cost to deploy a token is toodamnhigh.jpg

## Pitch

This should significantly reduce the cost to deploy a new token from the CLI.

**Comment by sohkai** [comment]
I believe this is now fixed via a parameter to `dao token new` in https://github.com/aragon/aragon-cli/pull/555.

**Comment by lkngtn** [comment]
does #555 included a default deployed token factory? I think the default should definitely NOT be to deploy a new factory

**Comment by 0xGabi** [comment]
@lkngtn you are right. This is something that @sohkai also mention yesterday on the issue thread. What do you guys think should be the default factory addresses for Rinkeby and Mainnet?

**Comment by 0xGabi** [comment]
nvm I found what Aragon use on Mainnet and I deployed one on Rinkeby 👍
