### ISSUE TITLE
Token Manager cannot be initialized with disabled transfers

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#569]
Original issue: https://github.com/aragon/aragon-apps/issues/630
Related PR: https://github.com/aragon/aragon-cli/pull/555#issuecomment-506826079

**Comment by 0xGabi** [comment]
I tested with last version (`6.0.4`) and is working..not sure why 🤔

@0x6431346e Could it be the new `truffle-hdwallet-provider` version (https://github.com/aragon/aragon-cli/pull/577)?

**Comment by adamstallard** [comment]
@0xGabi Does this mean that if I use 6.0.4 instead of 5.9.3 that I should be able to disable transfers?

**Comment by 0xGabi** [comment]
@adamstallard yes, it worked for me twice. I was planing to keep testing to figure out why it's working now

**Comment by 0xGabi** [comment]
I'll close this as it is working on last nightly version.
