### ISSUE TITLE
Limit deploying to http only if on a localhost server

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#573]
## 🚀 Feature

Consider a private network if detected.

## Motivation

Prevent using http with Rinkeby and Mainnet.

**Comment by dapplion** [comment]
Should this check only affect the `aragon deploy` command or some other subcommand I might not be aware of?

**Comment by 0xGabi** [comment]
@ajsantander @dapplion is this still relevant on the buidler plugin?

**Comment by dapplion** [comment]
It may still apply but we haven't got to that point yet. However, using HTTP does not necessarily mean insecure. In DAppNode all node endpoints are HTTP but since you are connected with a VPN to an internal docker network it's okay.
