### ISSUE TITLE
Shrinkwrap file mismatch

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#593]
## 🐛 Bug Report

On master we have [this shrinkwrap file](https://github.com/aragon/aragon-cli/blob/%40aragon/cli%406.0.2/packages/aragon-cli/npm-shrinkwrap.json):

```json
    "eth-block-tracker": {
      "version": "2.3.1",
      "resolved": "https://registry.npmjs.org/eth-block-tracker/-/eth-block-tracker-2.3.1.tgz",
      "integrity": "sha512-NamWuMBIl8kmkJFVj8WzGatySTzQPQag4Xr677yFxdVtIxACFbL/dQowk0MzEqIKk93U1TwY3MjVU6mOcwZnKA==",
      "requires": {
        "async-eventemitter": "github:ahultgren/async-eventemitter#fa06e39e56786ba541c180061dbf2c0a5bbf951c",
  ...
```

But on npm, [this is published](https://unpkg.com/@aragon/cli@6.0.2/npm-shrinkwrap.json):

```json
    "eth-block-tracker": {
      "version": "2.3.1",
      "resolved": "https://registry.npmjs.org/eth-block-tracker/-/eth-block-tracker-2.3.1.tgz",
      "integrity": "sha512-NamWuMBIl8kmkJFVj8WzGatySTzQPQag4Xr677yFxdVtIxACFbL/dQowk0MzEqIKk93U1TwY3MjVU6mOcwZnKA==",
      "requires": {
        "async-eventemitter": "async-eventemitter@github:ahultgren/async-eventemitter#fa06e39e56786ba541c180061dbf2c0a5bbf951c",
  ...
```

This is a [known issue](https://npm.community/t/could-not-install-from-module-as-it-does-not-contain-a-package-json-file-but-it-does/8311), which we solve with our [custom made script](https://github.com/aragon/aragon-cli/blob/master/packages/aragon-cli/scripts/fix-lockfile), (see the [Dependencies](https://github.com/aragon/aragon-cli/blob/master/docs-internal/Dependencies.md#lock-files) doc for more). 

The issue here is that `lerna`, during the publish process, changes these files...
You can see it in action here: https://travis-ci.org/aragon/aragon-cli/jobs/555428095#L2511

Temporary solution:

```
cd packages/aragon-cli
npm version patch
git add -A
git commit -m "Bump version"
npm publish --tag nightly
```

Reported this in the lerna repo: https://github.com/lerna/lerna/issues/2168

**Comment by 0xGabi** [comment]
@0x6431346e I think we can close this one now
