### ISSUE TITLE
Replace coveralls with codecov

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#650]
## 🚀 Feature

Coveralls can be very annoying sometimes reporting a coverage change when there are no code changes...perhaps we are not using it right, but https://codecov.io seems much nicer. E.g.: 
![image](https://user-images.githubusercontent.com/26041347/61535082-01691600-aa3a-11e9-989c-e454bcd177ef.png)

**Comment by sohkai** [comment]
I've added aragonCLI to codecov and installed its Github app as well.

@0x6431346e are you able to access https://codecov.io/gh/aragon/aragon-cli?

**Comment by 0x6431346e** [comment]
> I've added aragonCLI to codecov and installed its Github app as well.
> 
> @0x6431346e are you able to access [codecov.io/gh/aragon/aragon-cli](https://codecov.io/gh/aragon/aragon-cli)?

Yes, I can access it, thanks!

Closed by #878 

I think the detailed report is great: https://github.com/aragon/aragon-cli/pull/877#issuecomment-551132650
