### ISSUE TITLE
Merge AppProxy's ABI into artifact.abi

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#659]
## 🚀 Feature

Most developers deploying Aragon apps do so by first deploying a base contract and then proxy contracts on top of this. Usually you never inherit from `AppProxy` directly in these base contracts (and you probably shouldn't!), but this means that any functions or events declared by the `AppProxy` do not get included in the final artifact for the app.

We should attempt to merge the functions and events from `AppProxy` into this final artifact, and warn the user if there's a clash (if there was, the base contract's function would _never_ get called; this was a [previously recognized security vulnerability](https://medium.com/nomic-labs-blog/malicious-backdoors-in-ethereum-proxies-62629adf3357)).

## Motivation

Provide all functions and events available in a contract to the app developer in their frontend

**Comment by 0xGabi** [comment]
Related to #751

**Comment by sohkai** [comment]
Closing for https://github.com/aragon/aragon.js/issues/423 and https://github.com/aragon/aragon-cli/issues/1303.

Merging makes more sense at run time; checking should be done ahead of / during artifact generation.
