### ISSUE TITLE
Rename project to 'aragon-cli'

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-cli#71]
As @Smokyish pointed out for consistency with other project names would be a good idea to rename. 

Also this tool has been expanding a little bit in scope to the point it is not only useful to develop and publish Aragon apps, but to inspect and interact with DAOs from a CLI.

We will proceed with the rename in 36h if no objections are raised here.

**Comment by luisivan** [comment]
I agree

**Comment by sohkai** [comment]
All aboard.

**Comment by izqui** [comment]
Repo renamed and removed `aragon-dev-cli` entrypoint https://github.com/aragon/aragon-cli/commit/2f509aa4208c90007f6ab55afbe685fc67ba2678
