### ISSUE TITLE
Revert reason not available in tests

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#718]
## 🐛 Bug Report

When running `npm test` on an app freshly bootstrapped by `create-aragon-app`, the assertRevert helper is not able to retrieve revert reasons.

Revert reasons do work if the truffle.js file's contents are replaced by:
```
module.exports = require("@aragon/os/truffle-config")
```
as it is done in the Aragon apps.

**Comment by 0xGabi** [comment]
This was fixed with https://github.com/aragon/aragon-react-boilerplate/pull/74
