### ISSUE TITLE
Update truffle to v5

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#719]
## 🚀 Feature

Considerations commented by Brett:

>The only thing would be the format of the truffle config, since there's a few small differences between truffle@4 and truffle@5 (I think truffle@5's is a strict superset over 4's though), and I imagine aragonCLI may want to use the newer version (for things like networks)?
>It would also break tests for people who've relied on the bundled truffle in aragonCLI (should not be the case with packages that have declared their own truffle dependency).

**Comment by sohkai** [comment]
As a note, if we were to do this, we should update the boilerplates to use truffle@5.

**Comment by 0xGabi** [comment]
Solved with #1060
