### ISSUE TITLE
Counter app doesn't get resolved

### ISSUE THREAD

**Issue by listenaddress** [aragon/aragon-cli#730]
### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes.

#### Mainnet or testnet?

Aragon dev chain

#### Environment

- OS and OS version: MacOS 10.14.3
- Browser and browser version: Chrome 76.0.3809.100
- Aragon-cli: 6.2.5

## To Reproduce

I went through the steps on the Getting Started page (https://hack.aragon.org/docs/getting-started).

1. `npx create-aragon-app first-dao.aragonpm.eth`
2. `cd first-dao`
3. `npx aragon run`

## Expected behavior

I expected to see the counter app working.

## Actual Behavior

I get this error when I click on the counter app: ```ipfs resolve -r /ipfs/QmYqyHDUuZFdmKF3fKhBd5Wm4DikdFqwTVM9uHPpzSnNJB/index.html: no link named "index.html" under QmYqyHDUuZFdmKF3fKhBd5Wm4DikdFqwTVM9uHPpzSnNJB```

![Screen Shot 2019-08-19 at 5 21 31 PM](https://user-images.githubusercontent.com/8434548/63306364-375b1d80-c2b8-11e9-8236-324811ec8191.png)

**Comment by listenaddress** [comment]
I'll try updating the CLI tomorrow to see if that helps.

**Comment by listenaddress** [comment]
Actually I am running 6.2.5. Updating my message from yesterday.

**Comment by 0xGabi** [comment]
@listenaddress thank you for the feedback, this actually is an issue with not updating the documentation. The command should be `npx aragon run --files dist`. But actually you can also do `npm start` and that should work fine.

Let me know if that work and feel free to open the issue again otherwise

**Comment by listenaddress** [comment]
Yep, that works! Thanks Gabriel.
