### ISSUE TITLE
Is the react-kit boilerplate active?

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#736]
I noticed that the `aragon-react-kit-boilerplate` repo is archived: https://github.com/aragon/aragon-react-kit-boilerplate

However, in the `create-aragon-app` readme, it is listed as a valid boilerplate option: https://github.com/aragon/aragon-cli/tree/master/packages/create-aragon-app#command

**Comment by sohkai** [comment]
The react-kit boilerplate has been merged with the react boilerplate and we should update any outdated documentation :).

**Comment by 0xGabi** [comment]
Nice catch Ale, thanks. Closed with #739
