### ISSUE TITLE
aragon apm publish --dry-run

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#760]
## 🚀 Feature

It would great if `aragon apm publish` were able to do a dry run and log the transaction data that needs to be sent to propagate the package publish.

In cases where a deployment **must** be completed without down time or signed later, this feature would allow someone to obtain the necessary transactions ahead of time.

## Motivation

Publishing is tricky and ideally should not lead to downtime if multiple package publishes are necessary. Having all of the transaction data up front would make it easier to ensure that a sequence of publishes will happen regardless of any issues or bugs in the CLI during the publish.

**Comment by 0xGabi** [comment]
Duplicated of https://github.com/aragon/buidler-aragon/issues/69 this feature will be available on the publish task of buidler plugin
