### ISSUE TITLE
CLI installation and setup confusion

### ISSUE THREAD

**Issue by burrrata** [aragon/aragon-cli#770]
## 🐛 Bug Report

Followed the instuctions to use a unique mnemonic 
- https://hack.aragon.org/docs/guides-faq#set-a-private-key

Then ran `aragon devchain`. The default mnemonic was used, not the one I just added to `mnemonic.json`.

**Comment by 0xGabi** [comment]
You are right @burrrata also as we are using a snapshot for the `devchain` we are not able to update the mnemonic as you usually could from ganache server cause the snapshot already was initialized with the default mnemonic. Hope this make sense

**Comment by burrrata** [comment]
@0xGabi Thanks for clearing that up :)
