### ISSUE TITLE
create-aragon-app should not be recursively looking up the path for a truffle.js

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#78]

**Comment by dapplion** [comment]
Is this issue still relevant? Why does the create-react-app CLI need the `truffle.js` file?

**Comment by sohkai** [comment]
@dapplion AFAIK I remember having this problem, but it may have been for a really old version (when `aragon init` used to do the scaffolding).

If you've tried `create-aragon-app` recently, in a file path that had no truffle file recursively available, then let's close this!

**Comment by dapplion** [comment]
Awesome! Please @0xGabi close this issue when possible.
