### ISSUE TITLE
aragon contracts output cut off

### ISSUE THREAD

**Issue by macor161** [aragon/aragon-cli#783]
## 🐛 Bug Report

`aragon contracts` commands cut off the output when it is too large.
Bug reported by @mikec 

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes

#### Mainnet or testnet?

N/A

#### Organization

LevelK 

#### Environment

- aragonCLI: Latest
- OS and OS version: Mac and Linux

**Comment by dapplion** [comment]
Is there any specific truffle command to be passed to `aragon contracts` to recreate this issue?

**Comment by 0xGabi** [comment]
Maybe @mikec can provide a good example. But probably trying to use `aragon contracts exec` with a script with a couple of parameters might be a good way to reproduce

**Comment by mikec** [comment]
@dapplion, @0xGabi .. I just repro'd it on https://github.com/levelkdev/futarchy-app like so:

1) add an extra `@param` to one of the function comments in https://github.com/levelkdev/futarchy-app/blob/master/contracts/Futarchy.sol, so the compiler will throw a `DocstringParsingError`.
2) run `npm run compile` (or `aragon contracts compile`)
3) run `npm run compile:truffle` (or `truffle compile`)

On my environment, the output of `aragon contracts compile` gets cut off after about 390 lines, and the `DocstringParsingError` is never output. `truffle compile` includes the full output.

I noticed that this happens only when the compiler outputs warnings. It seems that syntax errors (missing a `;` for example) don't output warnings.

**Comment by dapplion** [comment]
Could you please paste the output of 
```
aragon contracts version
```
and
```
truffle version
```

----

On my machine I have different versions which arrange the warning errors in a different way.
```
> truffle version
Truffle v5.0.32 (core: 5.0.32)
Solidity - 0.4.24 (solc-js)
Node v10.15.3
Web3.js v1.2.1
```
```
> aragon contracts version
ℹ Passing the command to Truffle
Truffle v4.1.14 (core: 4.1.14)
Solidity v0.4.24 (solc-js)

```

**Comment by mikec** [comment]
@dapplion 

```
truffle version

Truffle v4.1.14 (core: 4.1.14)
Solidity v0.4.24 (solc-js)
```

```
aragon contracts version

 ℹ Passing the command to Truffle
Truffle v4.1.14 (core: 4.1.14)
Solidity v0.4.24 (solc-js)
```

`aragon contracts compile` output: https://pastebin.com/KyLkxz7F
`truffle compile` output: https://pastebin.com/2b3idSJU

**Comment by mikec** [comment]
@dapplion @0xGabi, looks like there's something odd happening at line 208 in the `aragon contracts compile` output https://pastebin.com/KyLkxz7F

```
,/Users/mfcalvanese/dev/eth/futarchy-app/contracts/Futarchy.sol:209:80: Warning: This function only accepts a single "bytes" argument. Please use "abi.encodePacked(...)" or a similar function to encode the data.
    OutcomeTokenBalances storage outcomeTCompiling ./contracts/DecisionLib.sol...
```

the `OutcomeTokenBalances storage outcomeT` gets cut off and the compile output repeats `Compiling ./contracts/DecisionLib.sol...` then concludes with the same truncated output `OutcomeTokenBalances storage outcomeT` on line 414.

**Comment by dapplion** [comment]
@mikec Thank you for providing all the info! Kudos

The output of `aragon contracts compile` is duplicated because of the process stdout being piped to the main process while it's accumulated in the errMsg variable; which in case of error it's printed out. The big question is **why** the process stops at that apparent random point 
```
OutcomeTokenBalances storage outcomeT
```

I see that @0xGabi and @luisivan developed this code last year. Is there a reason to reprint the output despite piping both stdout and stderr to the main process?

**Comment by 0xGabi** [comment]
Not relevant anymore as we remove the `aragon contracts` command completely
