### ISSUE TITLE
apm publish: gas price used is not the same as the variable passed to --gas-price 

### ISSUE THREAD

**Issue by chrishobcroft** [aragon/aragon-cli#803]
## Bug Report

When using `aragon-cli`, and setting the flag `--gas-price 8`, the actual gas price used was 8.80022 Gwei

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes.

#### Mainnet or testnet?

Mainnet

#### Organization

ethimpact.aragonid.eth

#### Environment

- Operating system: `Ubuntu 19.04`
- `aragon-cli` version: `6.2.6`
- Add any other context about the problem here.

## To Reproduce

Run a cli command with `--gas-price 8` as an argument / flag, and then validate what gas price i actually used.

## Expected behavior

I would expect that the gas price for the transaction when broadcast should be exactly the same as configured in the cli command.

## Actual Behavior

The actual gas price used was 8.80022 Gwei, as verified using etherscan:

![image](https://user-images.githubusercontent.com/2212651/65787853-c548e480-e151-11e9-9093-86a99d3ed32a.png)

**Comment by 0xGabi** [comment]
Thanks @chrishobcroft will take a look

**Comment by macor161** [comment]
Hi @chrishobcroft, I wasn't able to reproduce the problem. I've tried with a few commands like the following:
```bash
dao install 0x529fF5Dee5b970aa604e3345d5E9755e641D2e85 token-manager --gas-price 8 --app-init none --env aragon:rinkeby
```
Can you give me the command that you used when you encountered the bug?
Thanks!

**Comment by sohkai** [comment]
@chrishobcroft Were you using a signer or did you have a key supplied directly to the CLI (would not advise for mainnet)?

**Comment by chrishobcroft** [comment]
Key supplied direct to CLI.

**Comment by macor161** [comment]
Thanks @chrishobcroft, going to have a second look at this.

**Comment by sohkai** [comment]
@macor161 wondering if we were able to have a second look at this? I assume this was probably fixed with v7 or one of the many re-writes we may have done...?

**Comment by macor161** [comment]
All commands that I've tested support `--gas-price` and use the correct value. 
@chrishobcroft Feel free to open this issue if you encounter the bug again. Thanks!
