### ISSUE TITLE
create-aragon-app: help user with next steps

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#831]
From https://github.com/aragon/aragon-cli/issues/203#issuecomment-545178492:

> Would be great if the output actually specified the next steps, eg "The bones of your Aragon app are ready, but you still need to add the muscle and bring it to life with: `cd my-aragon-app` and run `npm install` and then `npm start`" or something like that.

We could even offer to make it interactive and ask the user "would you like to install and set it everything up now?"

**Comment by dapplion** [comment]
Running `npx create-aragon-app` already installs the app dependencies right?

Also, would it be good idea to add a link to the documentation? If so, is https://hack.aragon.org/docs/cli-main-commands a good URL or do you have a shorter editable url for this purpose.

**Comment by 0xGabi** [comment]
>Running npx create-aragon-app already installs the app dependencies right?

Yes, it install the dependencies and check if IPFS is available, installing it globally if not.

>Also, would it be good idea to add a link to the documentation?

Yes, good idea. About the link, I like that URL as start. I don't think we have a shorter one. You have thoughts on how to do that? 🤔
