### ISSUE TITLE
Close low hanging fruit PRs before SDK v7 refactors begin

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-cli#853]
Before we begin doing heavy refactors for SDK v7, we want to assimilate PRs that:
* Are simple enough
* Are compatible with the general direction of the upcoming refactors
* Don't add feature / complexity
* Have value and would be too complicated to include after the refactors have been implemented

## PRs included:
- [x] #833 ~~or #837~~
- [x] #839
- [x] #840
- [x] #841
- [x] ~#844~ #857
- [x] #845 (postponed)

**Comment by ajsantander** [comment]
@macor161 I wasn't able to assign you to this issue, not sure why... could you add yourself please?

**Comment by macor161** [comment]
Added https://github.com/aragon/aragon-cli/pull/854 that supersedes #833 since I have no permissions on the `aragon-cli` repo yet.

**Comment by macor161** [comment]
#845 doesn't seem to be working well. I propose we postpone it until after the refactoring.
