### ISSUE TITLE
Unable to install on Windows with Git Bash - hangs 

### ISSUE THREAD

**Issue by Swader** [aragon/aragon-cli#868]
## 🐛 Bug Report

During installing with `npm install -g @aragon/cli` the process hangs after outputting the following:

```bash
λ npm install -g @aragon/cli
npm WARN tarball tarball data for @aragon/aragen@5.3.5 (sha512-3gwDlPlmiHULV9z52TFksHcTOEj+sC+s4RUvnU5Jt/jCT3yhsjwQRL+RJ38eIZ0WOUJaGRMRzu8SRuiQ7RWzEw==) seems to be corrupted. Trying one more time.
[            ......] - extract: sill extract date-fns@2.0.0-alpha.22 extracted to C:\Program Files\nodejs\node_modules\.staging\date-fns-eff1b950 (235250ms)
```

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes.

#### Mainnet or testnet?

N/A

#### Organization

N/A

#### Environment

- OS and OS version: Windows 10 Pro, 64bit
- Browser and browser version: N/A
- Git Bash through Cmder, so just plain Git Bash
- Node version: 10.16.1.
- NPM version: 6.9.0

Other npm packages install fine.

## To Reproduce

Run `npm install -g @aragon/cli` on Windows 10 Pro 64bit inside Git Bash with npm/node globally available.

## Expected behavior

Aragon CLI would be installed.

## Actual Behavior

Installation process hangs with above message.

## Reproducible Demo

N/A

**Comment by Swader** [comment]
Installation **works with Yarn** but only if the following are executed first:

- `npm install --global --production windows-build-tools --vs2015`
- `npm config set python python2.7`

Unfortunately, this results in an error being thrown when the installed libs are invoked:

```bash
λ aragon
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'core-js/modules/es.array.slice'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Bruno\AppData\Local\Yarn\Data\global\node_modules\@aragon\cli\dist\cli.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by macor161** [comment]
Hi @Swader, aragon CLI is not very stable on Windows at the moment. I would suggest using Mac or a Ubuntu VM in the meantime.

**Comment by Swader** [comment]
Hm, can't really use Frame with a VM, and need to add apps to my DAO.

**Comment by okwme** [comment]
I get this error on Ubuntu 18
```
Cannot find module 'core-js/modules/es.array.slice'
```
To fix i install that package manually
```
yarn add core-js --save
```

**Comment by 0xGabi** [comment]
Related to #1167

**Comment by sohkai** [comment]
Closing for https://github.com/aragon/aragon-cli/issues/1167.
