### ISSUE TITLE
Inconsistent coverage

### ISSUE THREAD

**Issue by macor161** [aragon/aragon-cli#876]
## 🐛 Bug Report

Coverage generated by `npm run test:coverage` is inconsistent.
When run multiple times, I get approximately half of the time the following result:

<img width="726" alt="Screen Shot 2019-11-05 at 7 56 24 PM" src="https://user-images.githubusercontent.com/642515/68259085-db767a00-0006-11ea-9dff-8e223f043bdf.png">

And the other half:

<img width="726" alt="Screen Shot 2019-11-05 at 7 54 48 PM" src="https://user-images.githubusercontent.com/642515/68259096-e6c9a580-0006-11ea-85a7-b0a3aa11f5e4.png">

The above results are from PR #875 but every tested file seems to have the same problem on `develop` too.

#### Environment

- OS and OS version: MacOS Mojave

**Comment by 0x6431346e** [comment]
I noticed something weird too, I'm not getting 100% coverage for some reason:
![image](https://user-images.githubusercontent.com/26041347/68308096-f273a580-00b4-11ea-9046-242432a4cefb.png)

A StackOverflow answer suggets that we are missing: `babel-plugin-istanbul`, I think we need to follow this tutorial to properly install Istanbul with Babel: https://istanbul.js.org/docs/tutorials/es2015/

Perhaps with this occasion we can replace [coveralls with codecov](https://github.com/aragon/aragon-cli/issues/650) and get nice coverage comments in PRs.
