### ISSUE TITLE
Abstract away the keccak256 function

### ISSUE THREAD

**Issue by macor161** [aragon/aragon-cli#914]
## 🚀 Feature

The `keccak256` functions from `web3.utils` and `js-sha3`  don't have the exact same behavior. The former outputs a string with `0x` and the latter without `0x`. It would be interesting to abstract `keccak256` into our own function in case we have to migrate again to a different implementation. 

## Motivation

It would make it easier and less error prone to switch to another `keccak256` library in the future.

**Comment by 0xGabi** [comment]
Solved with #870
