### ISSUE TITLE
Wrong generated signature for array of contracts parameters 

### ISSUE THREAD

**Issue by macor161** [aragon/aragon-cli#931]
## 🐛 Bug Report

When calling the `solidity-extractor` helper on a file that contains a function taking an array of contracts as its parameter, the generated signature is incorrect.

## To Reproduce

Contract example:

```solidity
contract Test {

}

contract CounterApp is AragonApp {
    function initialize() public onlyInit {
        initialized();
    }

    function callTests(Test[] _tests) public {

    }
}
```

## Expected behavior

The generated json should be:

```json
		{
			"sig": "callTests(address[])",
			"roles": [],
			"notice": null
		}
```
## Actual Behavior

```json
		{
			"sig": "callTests(address)",
			"roles": [],
			"notice": null
		}
```

**Comment by 0xGabi** [comment]
We can also review how we handle the implementation of several interfaces functions. I discussed with @kevot about it and he reported that  we only include the first function on the `artifact.json`. 

Kevin, can you explain a bit more about it and idealy provide an example?
