### ISSUE TITLE
App with UI schema in aragonpm is showing with "No UI available" when installed

### ISSUE THREAD

**Issue by chrishobcroft** [aragon/aragon-cli#954]
## 🐛 Bug Report

When installing an Aragon App with a UI schema available on aragonpm, the tool fails to deploy a UI, claiming "No UI available".

Can be reproduced for livepeer.open.aragonpm.eth and ens.open.aragonpm.eth

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes.

#### Mainnet or testnet?

Rinkeby testnet

#### Organization

0x5E1BE46d9B590E080D443Df0bd14fd6a77112376

#### Environment

- OS and OS version: Ubuntu 19.04
- Add any other context about the problem here.

## To Reproduce

Case in point is livepeer.open.aragonpm.eth

0. Start with a DAO, with an Agent installed, where you have permissions to install apps
1. Run `aragon apm info livepeer.open.aragonpm.eth --environment aragon:rinkeby`
2. See that there exists a full schema for the app in the `aragonpm`
3. Install the `livepeer.open.aragonpm.eth` app in the DAO by running this command:
```
dao install <DAO-address> livepeer.open.aragonpm.eth --app-init-args <Agent-App-Address> 0x37dC71366Ec655093b9930bc816E16e6b587F968 --environment aragon:rinkeby
```
4. Add 1 permission by running this command:
```
dao acl create <DAO-address> <Livepeer-App-Proxy-Address>  REWARD_ROLE 0xffffffffffffffffffffffffffffffffffffffff 0xffffffffffffffffffffffffffffffffffffffff --environment aragon:rinkeby
```
5. Get a list of all the apps installed in the DAO, by running this command:
```
dao apps <DAO-address> --environment aragon:rinkeby --all
```
6. See that the installed Livepeer app is listed as `(No UI available)`.
7. Furthermore, when going to view the DAO on the web app, the livepeer app isn't shown.

https://rinkeby.aragon.org/#/<DAO-address>

## Expected behavior

I expect that the UI defined in the schema shown via `aragon apm info...` should be used to provide the UI for the app, and for the app to appear in the DAO on the web app.

For example - this DAO / app: https://rinkeby.aragon.org/#/livepeerdelegator/0x698af62d8cd4edb8ee6c7def4e70b6885e34f2b6/

## Actual Behavior

The app seems to be installed, but the UI is marked as `(No UI available)`.

Furthermore, the permissions that are set via the cli are not visible in the Web UI

(Write what happened. Add screenshots, if applicable.)

## Reproducible Demo

An example DAO which has had multiple instances of the livepeer app installed is `0x5E1BE46d9B590E080D443Df0bd14fd6a77112376`.

You can query the apps installed via this command:
```
dao apps 0x5E1BE46d9B590E080D443Df0bd14fd6a77112376 --environment aragon:rinkeby --all
```

You can query which permissions are assigned using this command:
```
dao acl view 0x5E1BE46d9B590E080D443Df0bd14fd6a77112376 --environment aragon:rinkeby
```

**Comment by chrishobcroft** [comment]
## To reproduce fully, follow this script:

```
Variables:

<Your-AragonCLI-Address>
<DAO-Address>
<DAO-Token-Address>
<Token-Manager-Proxy-Address>
<Voting-App-Proxy-Address>
<Agent-App-Proxy-Address>
<Livepeer-App-Proxy-Address>

Commands start here:

dao new --environment aragon:rinkeby

dao token new "HelloToken" "HELLO" 0 --environment aragon:rinkeby

dao install <DAO-Address> token-manager --app-init none --environment aragon:rinkeby

dao token change-controller <DAO-Token-Address> <Token-Manager-Proxy-Address> --environment aragon:rinkeby
dao acl create <DAO-Address> <Token-Manager-Proxy-Address> MINT_ROLE <Your-AragonCLI-Address> <Your-AragonCLI-Address> --environment aragon:rinkeby
dao exec <DAO-Address> <Token-Manager-Proxy-Address> initialize <DAO-Token-Address> true 0 --environment aragon:rinkeby
dao exec <DAO-Address> <Token-Manager-Proxy-Address> mint <Your-AragonCLI-Address> 1 --environment aragon:rinkeby
dao install <DAO-Address> voting --app-init-args <DAO-Token-Address> 500000000000000000 500000000000000000 86400 --environment aragon:rinkeby

dao acl create <DAO-Address> <Voting-App-Proxy-Address> CREATE_VOTES_ROLE <Token-Manager-Proxy-Address> <Voting-App-Proxy-Address> --environment aragon:rinkeby

dao install <DAO-Address> agent --environment aragon:rinkeby

STOP at this point, and in the next command, verify the livepeer.open.aragonpm.eth information in aragonpm:

aragon apm info livepeer.open.aragonpm.eth --environment aragon:rinkeby

It's definitely there, right?

So, on with the installation...

dao install <DAO-Address> livepeer.open.aragonpm.eth --app-init-args <Agent-App-Proxy-Address> 0x37dC71366Ec655093b9930bc816E16e6b587F968 --environment aragon:rinkeby

dao acl create <DAO-Address> <Agent-App-Proxy-Address> EXECUTE_ROLE <Livepeer-App-Proxy-Address> <Voting-App-Proxy-Address> --environment aragon:rinkeby
dao acl create <DAO-Address> <Agent-App-Proxy-Address> RUN_SCRIPT_ROLE <Livepeer-App-Proxy-Address> <Voting-App-Proxy-Address> --environment aragon:rinkeby

dao acl create <DAO-Address> <Livepeer-App-Proxy-Address> APPROVE_AND_BOND_ROLE 0xffffffffffffffffffffffffffffffffffffffff 0xffffffffffffffffffffffffffffffffffffffff --environment aragon:rinkeby

So... to see what apps we have installed in the DAO:

dao apps <DAO-Address> --environment aragon:rinkeby --all

The Livepeer app is there in the list, right, but "(No UI available)... what gives?

Go to https://rinkeby.aragon.org/#/<DAO-Address> and the Livepeer app isn't showing up... right?

And... to see what permissions each app has:

dao acl view <DAO-Address> --environment aragon:rinkeby

Go to https://rinkeby.aragon.org/#/<DAO-Address>/permissions and the Livepeer app is shown as "Unknown" right?

```

[Here is an example of this script being run, using this DAO: 0x5E1BE46d9B590E080D443Df0bd14fd6a77112376](https://github.com/aragon/aragon-cli/files/3884111/Log.Output.txt)

https://rinkeby.aragon.org/#/0x5E1BE46d9B590E080D443Df0bd14fd6a77112376

**Comment by macor161** [comment]
Hey @chrishobcroft , seems like the latest version of livepeer doesn't have the correct `appName` in its `artifact.json`: https://ipfs.eth.aragon.network/ipfs/QmRzdnYhpwDGh4DWpnEDQdVbDVApJyZDNx2Wo6xnPqdTco/artifact.json
It should be `"appName": "livepeer.open.aragonpm.eth"` instead of `"appName": "livepeer.aragonpm.eth"`.
I believe this should fix your problem :)
If you want you can install version `8.3.0` which has the correct `appName`.

**Comment by macor161** [comment]
Tested with https://rinkeby.aragon.org/#/test0011/0x95ef4916eca9617c5ccbdeef2c4a68a60e59dc96

**Comment by chrishobcroft** [comment]
Thanks @macor161 can you confirm how to deploy a previous version of the app?

Right now I'm running:
```
dao install <DAO-Address> livepeer.open.aragonpm.eth --app-init-args <Agent-App-Proxy-Address> 0x37dC71366Ec655093b9930bc816E16e6b587F968 --environment aragon:rinkeby
```

What command do I run instead?

**Comment by chrishobcroft** [comment]
Message from @willjgriff who deployed the app:

> The Default option is only used for local deployment. Is like that in the template. So the correct name for Rinkeby and Mainnet is `livepeer.open.aragonpm.eth`.
>
> `<appname>.aragonpm.eth` is reserved for main Aragon deployed apps, Voting, Finance etc.

So, how come it isn't working?

**Comment by macor161** [comment]
@chrishobcroft hmm maybe it's a deployment problem then. What I can say is that every working version have  `livepeer.open.aragonpm.eth` in their `artifact.json` except for the latest broken version. Do you know when was this version released?

To install `8.3.0`: 
`dao install <DAO> livepeer.open.aragonpm.eth "8.3.0" --app-init-args <agent address> 0x37dC71366Ec655093b9930bc816E16e6b587F968 --environment aragon:rinkeby`

**Comment by chrishobcroft** [comment]
OK, thanks @macor161, perhaps that is the culprit after all.

I will try the deployment with the downgraded version.

**Comment by macor161** [comment]
@chrishobcroft Were you able to install it with version `8.3.0`?

**Comment by chrishobcroft** [comment]
I did, yes, thank you @macor161.

It would appear that the issue here is indeed with the `appName` - you were right :)

Closing
