### ISSUE TITLE
Error after init

### ISSUE THREAD

**Issue by goodstemy** [aragon/aragon-cli#96]
I try to use `aragon-cli` and try to create and run basic app by following commands:
- `aragon init goodstemy`
- `cd goodstemy`
- `aragon run`

and getting an error in browser logs:

<img width="1440" alt="2018-05-19 19 43 13" src="https://user-images.githubusercontent.com/8494692/40271383-e54c8ed0-5b9c-11e8-8068-8cd58584dde4.png">

terminal logs:

<img width="696" alt="2018-05-19 19 42 57" src="https://user-images.githubusercontent.com/8494692/40271382-e52a124c-5b9c-11e8-8170-795b83225fa7.png">

**Comment by izqui** [comment]
Did you get it to work @goodstemy? Sometimes trying again seems to solve the issue.

Will proceed to close in a few days if there is no reply :)

**Comment by sohkai** [comment]
Closing due to no response :)
