### ISSUE TITLE
Invalid number of parameters for "newInstance". Got 0 expected 1!

### ISSUE THREAD

**Issue by vporton** [aragon/aragon-cli#963]
**Describe the bug**
`Invalid number of parameters for "newInstance". Got 0 expected 1!`
despite I do have an argument.

**Mainnet or testnet?**
localhost

**To Reproduce**

1. Clone https://github.com/vporton/aragon-template-args-bug
1. `npm run start:template`

Get message:

> Invalid number of parameters for "newInstance". Got 0 expected 1!

**Expected behavior**
`newInstance` called with `0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7` argument without an error.

**Desktop (please complete the following information):**
 - OS and OS version: Ubuntu 18.10

**Comment by macor161** [comment]
Actually this reminds me of a bug in an old version of the CLI. Can you make sure that you have the latest version installed? (`6.4.1`)
After that, there will still be one or two small changes to do in your code to make it work, I submitted a pull request to your repo fixing those. 
Let me know if you need more help.

**Comment by vporton** [comment]
Yes, it was (unsuccessfully) tested namely with `6.4.1`.

**Comment by macor161** [comment]
From what I saw in your `package-lock.json` file, the version `6.2.5` was installed: https://raw.githubusercontent.com/vporton/aragon-template-args-bug/c102c9d26a5d4503cc2f6a57a2c66826e626c90d/package-lock.json
My pull request should have also fixed this. Let me know if it worked :)

**Comment by vporton** [comment]
Oh, I had `6.2.5` installed locally and `6.4.1` locally. However, upgrading the local version does not solve the problem. `npm i @aragon/api` solves the problem reported by me.

The error message should be more understandable (like `Install recent @aragon/api`). So I don't close the bug.

**Comment by macor161** [comment]
Happy to see that upgrading the CLI solved the issue 🙂 
Adding a deprecation warning would probably be a good idea indeed, but perhaps we will wait for the v7 release before doing so. In any case, I’m going to discuss this with the team and open a new issue for it. Thanks for the suggestion @vporton

**Comment by vporton** [comment]
@macor161 But my [real software](https://github.com/vporton/courts/commit/38c1afca095812668d7e2aec209d3dc401f341ca) does not start successfully anyway, even if I apply proposed in the [discussion](https://github.com/vporton/aragon-template-args-bug/pull/1) fixes.

By the way for the "real software", the error is: `Invalid number of parameters for "undefined". Got 0 expected 1!`

Why `undefined`?

Help me to find bug(s) (either in Aragon or my software) that prevent my real software to start.

Please reopen the bug and help me to make my software to work!

**Comment by macor161** [comment]
Hi @vporton I will have a look at [your project](https://github.com/vporton/courts) today. I suspect a similar problem to the previous but if we find a bug in the CLI, I will certainly reopen the issue :) 
I will also be in the chat all day so feel free to reach out for any question.
