### ISSUE TITLE
aragon contracts test doesn't seem to be erroring or displaying test results properly

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-cli#97]
Trying `aragon contracts test` on the current react boilerplate doesn't seem to work very well; it just says everything's fine when it should definitely be failing.

It also doesn't seem to be displaying the test output on proper runs (with the [react boilerplate's mock tests fixed](https://github.com/aragon/aragon-react-boilerplate/pull/7)).

**Comment by Quazia** [comment]
Does anybody know if this is still an issue? If no response will be checking to see if the issue is still present.

**Comment by sohkai** [comment]
@0xGabi Could we retest this with failing tests to see if we're returning the proper output and exit codes?

**Comment by 0xGabi** [comment]
This is working correctly now 🚀
