### ISSUE TITLE
Create 'aragon start' command using wrapper's 'npm run start:dev'

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-cli#98]
- [ ] Implement `aragon start [git-ref]`
- [ ] `aragon run` should use `aragon start` to start wrapper

See https://github.com/aragon/aragon/pull/241

**Comment by galactusss** [comment]
Hi I'm trying to tackle this issue. I been researching and I have some questions:

1. I need to create a totally new aragon command (like aragon run, aragon init, etc) for start?
2. The second task, it means to add the new aragon start command as a new task in aragon run TaskList?

**Comment by sohkai** [comment]
@galactusss Yup :).

It's likely to involve making the [`Open DAO`](https://github.com/aragon/aragon-cli/blob/master/src/commands/run.js#L247) tasks its own command and then calling it in `aragon run` like [how we do a few of the other commands](https://github.com/aragon/aragon-cli/blob/master/src/commands/run.js#L161).

**Comment by galactusss** [comment]
Thank you for your answer @sohkai it helped me to keep forward. I kind of start understanding yargs. 

I would like to have some guide about the positional argument [git-ref] My guess is that 'git-ref' is the git repo of the wrapper, but I'm not sure.

**Comment by sohkai** [comment]
`[git-ref]` would be a commit hash, branch name, or tag name. Basically something that can be used with `git checkout`.

**Comment by izqui** [comment]
Actually `aragon start` should use the new flags `aragon run` accepts for configuring how the client is run: `--client-version` (what was referred here as `[git-ref]`), `--client-port` and `--client-path`

**Comment by 0x6431346e** [comment]
Perhaps we could name this `aragon start-client` ?
