### ISSUE TITLE
Token contract not verified on Mainnet

### ISSUE THREAD

**Issue by GriffGreen** [aragon/aragon-cli#980]
## 🐛 Bug Report

Used the CLI to deploy our 2 token DAO and the very important token being actively used by the Commons Stack community is not verified on etherscan
https://etherscan.io/token/0xd53b50a6213ee7ff2fcc41a7cf69d22ded0a43b3#readContract

This is not an isolated bug for my org... on Nov 5th @macor161 also said he had a similar isue in the dev channel on rocket chat/riot

@sohkai theorized "The CLI must still be using a version of the factory that’s not optimized."

Maybe related to #776 

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

yes

#### Organization

https://mainnet.aragon.org/#/commonsstackorg/0xac104c988ff9c90dafc7754b2fb9072e25f93507

#### Environment

not sure what was used to deploy, my guess is that it was a newer mac 

## To Reproduce

Deploy a 2 token dao with the CLI

## Expected behavior

I thought the contract would be verified on etherscan

## Actual Behavior

it wasn't verified, and now everyone is going to think i'm a scammer with a sh!tcoin :-(

**Comment by GriffGreen** [comment]
I like the bot :-D

**Comment by 0xGabi** [comment]
Hi @GriffGreen sorry about having to deal with this issue. It should be fixed on the new aragonCLI version.

We can help you verify the contract you share. I'll try to do it the next couple of days

**Comment by 0xGabi** [comment]
Hey @GriffGreen the contract was verified with the help of @sohkai 🙏 

In the end the contract deployed was optimized with 10k run.
